function result = simulate_motion_case(params, motion)
%SIMULATE_MOTION_CASE Generate one moving-point-target azimuth experiment.
%
%   result = simulate_motion_case(params, motion)
%
% Geometry follows the model used in Wang et al. (2023):
%
%   R^2(eta) =
%       H^2
%       + (x0 + vr*eta + 0.5*ar*eta^2)^2
%       + (vsar*eta - va*eta - 0.5*aa*eta^2)^2
%
% A stationary target is obtained with vr=ar=va=aa=0.
%
% The function returns:
%
%   1) exact moving/static range histories,
%   2) raw azimuth phase histories,
%   3) the motion-induced residual phase factor
%
%        exp[-j*4*pi/lambda*(R_move-R_static)],
%
%   4) a matched-filter azimuth profile generated by correlating the moving
%      azimuth echo with the stationary-target reference.
%
% This is a mechanism-level azimuth simulation. It does not synthesize the
% complete 2-D range-azimuth raw SAR data.

    eta = params.eta(:).';
    w = params.window(:).';

    H = params.H;
    x0 = params.x0;
    vsar = params.vsar;
    lambda = params.lambda;

    vr = motion.vr;
    ar = motion.ar;
    va = motion.va;
    aa = motion.aa;

    %% Exact range histories
    R_static = sqrt( ...
        H^2 ...
        + x0^2 ...
        + (vsar*eta).^2 );

    R_move = sqrt( ...
        H^2 ...
        + (x0 + vr*eta + 0.5*ar*eta.^2).^2 ...
        + ((vsar-va)*eta - 0.5*aa*eta.^2).^2 );

    %% Raw azimuth phase histories
    raw_static = w .* exp(-1j * 4*pi/lambda * R_static);
    raw_move = w .* exp(-1j * 4*pi/lambda * R_move);

    %% Motion-induced residual phase
    delta_R = R_move - R_static;

    residual_signal = ...
        w .* exp(-1j * 4*pi/lambda * delta_R);

    %% Stationary-reference matched filtering
    %
    % Linear correlation:
    %
    %   y = s_move (*) s_static
    %
    % implemented as convolution with conjugated time reversal.
    matched_filter = conj(fliplr(raw_static));

    az_profile = conv(raw_move, matched_filter, 'full');
    az_profile_static = conv(raw_static, matched_filter, 'full');

    N = numel(eta);
    lags = (-(N-1):(N-1)) / params.PRF;

    %% Package outputs
    result = struct();

    result.R_static = R_static;
    result.R_move = R_move;
    result.delta_R = delta_R;

    result.raw_static = raw_static;
    result.raw_move = raw_move;
    result.residual_signal = residual_signal;

    result.az_profile = az_profile;
    result.az_profile_static = az_profile_static;
    result.lags = lags;
end
