%% exp04_fast_fine_tradeoff.m
% EXP04: Fast / Fine / Traditional refocusing under spatial variation
%
% Reproduction + controlled extension of:
%
%   Wang et al.,
%   "Fast and Accurate Refocusing for Moving Ships in SAR Imagery
%   Based on FrFT", Remote Sensing, 2023.
%
% -------------------------------------------------------------------------
% PAPER-SUPPORTED PART
%
% The paper assumes that under favorable sea conditions a linearly moving
% ship has highly redundant defocus information among its azimuth lines:
%
%       p_opt(n) ~= p_best
%
% Based on this property:
%
%   Traditional:
%       calculate the optimal FrFT order for every azimuth line.
%
%   Fast:
%       calculate only p_best and use it for every azimuth line.
%
%   Fine:
%       calculate p_best first, then use p_best as the initial value for
%       a local minimum-entropy refinement of every other azimuth line.
%
% -------------------------------------------------------------------------
% OUR CONTROLLED EXTENSION
%
% We introduce:
%
%       sigma_p
%
% to control the spatial dispersion of true optimal FrFT orders:
%
%       p_true(n) = p0 + sigma_p * z(n)
%
% where z(n) is a fixed normalized spatial pattern.
%
% This allows us to continuously move from:
%
%       sigma_p = 0
%           ideal linear-motion / order-redundant case
%
% to:
%
%       sigma_p large
%           increasingly spatial-variant defocus.
%
% The purpose is to study:
%
%       focus quality
%            vs
%       computational burden
%            vs
%       spatial variation.
%
% -------------------------------------------------------------------------
% IMPORTANT
%
% 1) This is a controlled signal-level reproduction/extension.
%    It does NOT claim to reproduce the exact scattering geometry of a
%    real ship.
%
% 2) Each azimuth line is generated as a normalized LFM whose true FrFT
%    optimal order is known analytically.
%
% 3) Runtime is only relative because frft_direct.m is the transparent
%    O(N^2) implementation used in EXP01-EXP03.
%
% 4) The cleaner computational metric remains:
%
%       number of FrFT evaluations.
%
% -------------------------------------------------------------------------

clear;
clc;
close all;

rng(42);

%% 0. Resolve project paths

script_fullpath = mfilename('fullpath');

exp_dir = fileparts(script_fullpath);
code_dir = fileparts(exp_dir);
paper_dir = fileparts(code_dir);

functions_dir = fullfile( ...
    code_dir, ...
    'functions');

results_dir = fullfile( ...
    paper_dir, ...
    'results', ...
    'exp04_fast_fine_tradeoff');

if ~exist(functions_dir, 'dir')
    error( ...
        'Functions directory not found: %s', ...
        functions_dir);
end

if ~exist(results_dir, 'dir')
    mkdir(results_dir);
end

addpath(functions_dir);

required_functions = { ...
    'frft_direct', ...
    'signal_entropy', ...
    'minimum_entropy_search', ...
    'two_stage_peak_search'};

for ii = 1:numel(required_functions)

    if exist(required_functions{ii}, 'file') ~= 2
        error( ...
            'Required function not found: %s.m', ...
            required_functions{ii});
    end

end

fprintf('============================================================\n');
fprintf('EXP04: Fast / Fine refocusing under spatial variation\n');
fprintf('Experiment folder : %s\n', exp_dir);
fprintf('Functions folder  : %s\n', functions_dir);
fprintf('Results folder    : %s\n', results_dir);
fprintf('============================================================\n\n');

%% 1. Recover the physical baseline optimal order from EXP02
%
% We use the same controlled SAR geometry and the same azimuth-velocity
% state va = 20 m/s.
%
% The physical model is used only to determine the center order p0.
% The multi-line experiment itself is generated in normalized FrFT
% coordinates.

c = 299792458;

fc = 3e9;
lambda = c / fc;

PRF = 188;

H = 3000;
x0 = 3000;

vsar = 150;
va = 20;

Lant = 2;

R0 = hypot(H, x0);

az_beamwidth = lambda / Lant;

Tap_est = ...
    R0 * az_beamwidth / vsar;

N_phys = round(Tap_est * PRF);

if mod(N_phys, 2) == 0
    N_phys = N_phys + 1;
end

eta_phys = ...
    ((0:N_phys-1) - (N_phys-1)/2) / PRF;

eta_scale = ...
    max(abs(eta_phys)) / 4;

Ka_static = ...
    -2 * vsar^2 / ...
    (lambda * R0);

Ka_move = ...
    -2 * (vsar-va)^2 / ...
    (lambda * R0);

K_res = ...
    Ka_move - Ka_static;

kappa0 = ...
    K_res * eta_scale^2;

alpha0 = ...
    atan2(1, -kappa0);

p0 = ...
    2 * alpha0 / pi;

fprintf('Baseline derived from EXP02 azimuth-velocity case:\n');
fprintf('  R0                 = %.3f m\n', R0);
fprintf('  K_res              = %.6f Hz/s\n', K_res);
fprintf('  normalized kappa0  = %.6f\n', kappa0);
fprintf('  baseline p0        = %.6f\n\n', p0);

%% 2. Synthetic multi-azimuth-line ship
%
% Keep the signal length moderate because EXP04 requires thousands of FrFT
% evaluations when the traditional method is repeated for every line.

N = 193;

t = linspace(-4, 4, N);
u = t;

M = 21;                  % number of ship azimuth lines / range cells

line_index = 1:M;
best_idx = (M+1)/2;

% Hann aperture
w = ...
    0.5 ...
    - 0.5*cos( ...
    2*pi*(0:N-1)/(N-1));

%% 3. Ship scattering-energy envelope
%
% The central line is deliberately made the strongest line so that it
% becomes the "best azimuth line" as defined in the paper.

range_scale = 4.5;

amplitude = ...
    0.30 ...
    + 0.70 * ...
    exp( ...
    -0.5 * ...
    ((line_index-best_idx)/range_scale).^2);

% Guarantee a unique strongest line.
amplitude(best_idx) = ...
    max(amplitude) + 0.05;

%% 4. Fractional-frequency positions of ship scattering lines
%
% Different center-frequency terms make focused peaks appear at different
% fractional coordinates, producing a simple 2-D ship-like scattering
% structure rather than putting every line at exactly the same u.

f0 = ...
    linspace(-0.22, 0.22, M);

% Small deterministic nonlinearity to avoid a perfectly straight pattern.
f0 = ...
    f0 ...
    + 0.035 * ...
    sin( ...
    2*pi*(line_index-1)/(M-1));

%% 5. Fixed spatial pattern of order variation
%
% z is generated ONCE and reused for every sigma_p.
% Therefore increasing sigma_p changes only the amount of spatial
% variation, not its shape.

z = randn(1, M);

% Smooth the random pattern to resemble spatially correlated motion.
kernel = [1 2 3 2 1];
kernel = kernel / sum(kernel);

z = conv( ...
    z, ...
    kernel, ...
    'same');

% Force the strongest / best line to remain the representative center:
%
%       p_true(best_idx) = p0

z = ...
    z - z(best_idx);

% Normalize standard deviation.
if std(z) > 0
    z = z / std(z);
end

z(best_idx) = 0;

%% 6. Spatial-variation sweep
%
% sigma_p is the standard scale of optimal-order dispersion.
%
% sigma_p = 0:
%   all lines have exactly the same optimal order.
%
% Larger sigma_p:
%   increasing spatial variation.

sigma_list = [ ...
    0.0000, ...
    0.0025, ...
    0.0050, ...
    0.0100, ...
    0.0200, ...
    0.0400, ...
    0.0800];

n_sigma = numel(sigma_list);

%% 7. Noise setting

SNR_dB = 35;

fprintf('Synthetic ship configuration:\n');
fprintf('  azimuth lines M        = %d\n', M);
fprintf('  samples per line N     = %d\n', N);
fprintf('  best line index        = %d\n', best_idx);
fprintf('  SNR                    = %.1f dB\n', SNR_dB);
fprintf('  number of sigma cases  = %d\n\n', n_sigma);

%% 8. Search settings
%
% Same search steps used in EXP03 / paper:
%
%   coarse = 0.1
%   fine   = 0.005

p_bounds = [0.02, 1.98];

p_initial = 1.0;

h_coarse = 0.1;
h_fine = 0.005;

%% 9. Preallocate ALL numerical results
%
% IMPORTANT:
% We deliberately avoid struct arrays here.
% This prevents the MATLAB field-mismatch errors encountered in EXP02/03.

p_true_all = ...
    zeros(n_sigma, M);

p_best_est = ...
    zeros(n_sigma, 1);

p_fast_all = ...
    zeros(n_sigma, M);

p_fine_all = ...
    zeros(n_sigma, M);

p_trad_all = ...
    zeros(n_sigma, M);

entropy_fast_line = ...
    zeros(n_sigma, M);

entropy_fine_line = ...
    zeros(n_sigma, M);

entropy_trad_line = ...
    zeros(n_sigma, M);

concentration_fast_line = ...
    zeros(n_sigma, M);

concentration_fine_line = ...
    zeros(n_sigma, M);

concentration_trad_line = ...
    zeros(n_sigma, M);

image_entropy_fast = ...
    zeros(n_sigma, 1);

image_entropy_fine = ...
    zeros(n_sigma, 1);

image_entropy_trad = ...
    zeros(n_sigma, 1);

mean_entropy_fast = ...
    zeros(n_sigma, 1);

mean_entropy_fine = ...
    zeros(n_sigma, 1);

mean_entropy_trad = ...
    zeros(n_sigma, 1);

order_rmse_fast = ...
    zeros(n_sigma, 1);

order_rmse_fine = ...
    zeros(n_sigma, 1);

order_rmse_trad = ...
    zeros(n_sigma, 1);

calls_fast = ...
    zeros(n_sigma, 1);

calls_fine = ...
    zeros(n_sigma, 1);

calls_trad = ...
    zeros(n_sigma, 1);

runtime_fast = ...
    zeros(n_sigma, 1);

runtime_fine = ...
    zeros(n_sigma, 1);

runtime_trad = ...
    zeros(n_sigma, 1);

best_search_calls = ...
    zeros(n_sigma, 1);

% Store the largest-sigma example for visual comparison.
example_input = [];
example_fast = [];
example_fine = [];
example_trad = [];
example_p_true = [];

%% 10. Sweep sigma_p

fprintf('Starting spatial-variation sweep...\n\n');

for is = 1:n_sigma

    sigma_p = sigma_list(is);

    fprintf('------------------------------------------------------------\n');
    fprintf( ...
        'sigma_p = %.4f\n', ...
        sigma_p);

    %% ---------------------------------------------------------
    % 10.1 True optimal orders

    p_true = ...
        p0 ...
        + sigma_p * z;

    % Keep orders safely inside the FrFT interval.
    p_true = ...
        min( ...
        max(p_true, 0.08), ...
        1.92);

    p_true(best_idx) = p0;

    p_true_all(is, :) = p_true;

    %% ---------------------------------------------------------
    % 10.2 Generate the multi-line ship signal
    %
    % For a FrFT order p:
    %
    %       alpha = p*pi/2
    %
    % The chirp rate satisfying the chosen kernel convention is:
    %
    %       kappa = -cot(alpha)
    %
    % Each line:
    %
    %       x_n(t) =
    %           A_n w(t)
    %           exp(j*pi*kappa_n*t^2)
    %           exp(j*2*pi*f0_n*t)
    %           exp(j*phi_n)
    %           + noise

    X_ship = ...
        zeros(M, N);

    for im = 1:M

        alpha_true = ...
            p_true(im) * pi/2;

        kappa_true = ...
            -cot(alpha_true);

        phase0 = ...
            2*pi*rand;

        clean_line = ...
            amplitude(im) .* ...
            w .* ...
            exp( ...
            1j*pi*kappa_true*t.^2) .* ...
            exp( ...
            1j*2*pi*f0(im)*t) .* ...
            exp(1j*phase0);

        signal_power = ...
            mean(abs(clean_line).^2);

        noise_power = ...
            signal_power / ...
            (10^(SNR_dB/10));

        noise = ...
            sqrt(noise_power/2) .* ...
            ( ...
            randn(1,N) ...
            + 1j*randn(1,N));

        X_ship(im, :) = ...
            clean_line + noise;

    end

    %% ---------------------------------------------------------
    % 10.3 Identify the best azimuth line exactly as paper principle:
    %      maximum line energy.

    line_energy = ...
        sum( ...
        abs(X_ship).^2, ...
        2);

    [~, best_detected_idx] = ...
        max(line_energy);

    if best_detected_idx ~= best_idx

        warning( ...
            ['Detected best line (%d) differs from intended ', ...
             'best line (%d).'], ...
            best_detected_idx, ...
            best_idx);

    end

    x_best = ...
        X_ship(best_detected_idx, :);

    %% ---------------------------------------------------------
    % 10.4 Estimate best-line order ONCE
    %
    % This search cost is shared by both Fast and Fine.

    best_result = ...
        minimum_entropy_search( ...
        x_best, ...
        t, ...
        u, ...
        p_initial, ...
        h_coarse, ...
        h_fine, ...
        p_bounds);

    p_best = ...
        best_result.p_opt;

    p_best_est(is) = p_best;

    best_search_calls(is) = ...
        best_result.n_frft;

    fprintf( ...
        '  true best-line order      = %.6f\n', ...
        p_true(best_detected_idx));

    fprintf( ...
        '  estimated best-line order = %.6f\n', ...
        p_best);

    fprintf( ...
        '  best-line search calls    = %d\n', ...
        best_result.n_frft);

    %% =========================================================
    % 10.5 FAST METHOD
    %
    % Every line uses exactly the same p_best.
    %
    % Total FrFT cost:
    %
    %       best-line search
    %       +
    %       one refocusing FrFT for every line

    tic;

    Y_fast = ...
        zeros(M, N);

    for im = 1:M

        p_fast_all(is, im) = ...
            p_best;

        Y = ...
            frft_direct( ...
            X_ship(im, :), ...
            t, ...
            p_best, ...
            u);

        Y_fast(im, :) = ...
            Y(:).';

        entropy_fast_line(is, im) = ...
            signal_entropy(Y);

        P = abs(Y).^2;

        concentration_fast_line(is, im) = ...
            max(P) / sum(P);

    end

    runtime_fast(is) = toc;

    calls_fast(is) = ...
        best_result.n_frft ...
        + M;

    %% =========================================================
    % 10.6 FINE METHOD
    %
    % Best line:
    %       directly use p_best.
    %
    % Other lines:
    %       start at p_best and move with ONLY the fine step.
    %
    % This reproduces the important logic of the paper:
    %
    %       no full coarse search for every line.

    tic;

    Y_fine = ...
        zeros(M, N);

    fine_search_calls_total = 0;

    for im = 1:M

        if im == best_detected_idx

            p_i = p_best;

        else

            fine_result = ...
                local_entropy_search( ...
                X_ship(im, :), ...
                t, ...
                u, ...
                p_best, ...
                h_fine, ...
                p_bounds);

            p_i = ...
                fine_result.p_opt;

            fine_search_calls_total = ...
                fine_search_calls_total ...
                + fine_result.n_frft;

        end

        p_fine_all(is, im) = ...
            p_i;

        Y = ...
            frft_direct( ...
            X_ship(im, :), ...
            t, ...
            p_i, ...
            u);

        Y_fine(im, :) = ...
            Y(:).';

        entropy_fine_line(is, im) = ...
            signal_entropy(Y);

        P = abs(Y).^2;

        concentration_fine_line(is, im) = ...
            max(P) / sum(P);

    end

    runtime_fine(is) = toc;

    calls_fine(is) = ...
        best_result.n_frft ...
        + fine_search_calls_total ...
        + M;

    %% =========================================================
    % 10.7 TRADITIONAL METHOD
    %
    % Every line performs:
    %
    %       complete two-stage peak search
    %
    % followed by:
    %
    %       one refocusing FrFT.
    %
    % No struct arrays are used: each search result is kept only as a
    % temporary scalar struct.

    tic;

    Y_trad = ...
        zeros(M, N);

    trad_search_calls_total = 0;

    for im = 1:M

        trad_result = ...
            two_stage_peak_search( ...
            X_ship(im, :), ...
            t, ...
            u, ...
            h_coarse, ...
            h_fine, ...
            p_bounds);

        p_i = ...
            trad_result.p_opt;

        p_trad_all(is, im) = ...
            p_i;

        trad_search_calls_total = ...
            trad_search_calls_total ...
            + trad_result.n_frft;

        Y = ...
            frft_direct( ...
            X_ship(im, :), ...
            t, ...
            p_i, ...
            u);

        Y_trad(im, :) = ...
            Y(:).';

        entropy_trad_line(is, im) = ...
            signal_entropy(Y);

        P = abs(Y).^2;

        concentration_trad_line(is, im) = ...
            max(P) / sum(P);

    end

    runtime_trad(is) = toc;

    calls_trad(is) = ...
        trad_search_calls_total ...
        + M;

    %% ---------------------------------------------------------
    % 10.8 Quality metrics

    mean_entropy_fast(is) = ...
        mean( ...
        entropy_fast_line(is, :));

    mean_entropy_fine(is) = ...
        mean( ...
        entropy_fine_line(is, :));

    mean_entropy_trad(is) = ...
        mean( ...
        entropy_trad_line(is, :));

    image_entropy_fast(is) = ...
        global_image_entropy(Y_fast);

    image_entropy_fine(is) = ...
        global_image_entropy(Y_fine);

    image_entropy_trad(is) = ...
        global_image_entropy(Y_trad);

    order_rmse_fast(is) = ...
        sqrt( ...
        mean( ...
        ( ...
        p_fast_all(is,:) ...
        - p_true ...
        ).^2));

    order_rmse_fine(is) = ...
        sqrt( ...
        mean( ...
        ( ...
        p_fine_all(is,:) ...
        - p_true ...
        ).^2));

    order_rmse_trad(is) = ...
        sqrt( ...
        mean( ...
        ( ...
        p_trad_all(is,:) ...
        - p_true ...
        ).^2));

    fprintf( ...
        '  image entropy: Fast / Fine / Trad = %.4f / %.4f / %.4f\n', ...
        image_entropy_fast(is), ...
        image_entropy_fine(is), ...
        image_entropy_trad(is));

    fprintf( ...
        '  order RMSE   : Fast / Fine / Trad = %.5f / %.5f / %.5f\n', ...
        order_rmse_fast(is), ...
        order_rmse_fine(is), ...
        order_rmse_trad(is));

    fprintf( ...
        '  FrFT calls   : Fast / Fine / Trad = %d / %d / %d\n', ...
        calls_fast(is), ...
        calls_fine(is), ...
        calls_trad(is));

    %% ---------------------------------------------------------
    % Store the strongest spatial-variation example

    if is == n_sigma

        example_input = X_ship;
        example_fast = Y_fast;
        example_fine = Y_fine;
        example_trad = Y_trad;

        example_p_true = p_true;

    end

end

fprintf('\nSpatial-variation sweep completed.\n\n');

%% 11. Figure 1: true optimal-order distributions

selected_sigma_idx = [ ...
    1, ...
    ceil(n_sigma/2), ...
    n_sigma];

fig1 = figure( ...
    'Name', ...
    'EXP04 - Optimal order distributions', ...
    'Color', ...
    'w');

tiledlayout( ...
    1, ...
    3, ...
    'Padding', ...
    'compact', ...
    'TileSpacing', ...
    'compact');

for kk = 1:numel(selected_sigma_idx)

    is = selected_sigma_idx(kk);

    nexttile;

    plot( ...
        line_index, ...
        p_true_all(is,:), ...
        'o-', ...
        'LineWidth', ...
        1.3);

    hold on;

    yline( ...
        p_best_est(is), ...
        '--', ...
        'Estimated p_{best}', ...
        'LineWidth', ...
        1.2);

    plot( ...
        best_idx, ...
        p_true_all(is,best_idx), ...
        's', ...
        'MarkerSize', ...
        9, ...
        'LineWidth', ...
        1.5);

    hold off;

    grid on;

    xlabel('Azimuth-line index');
    ylabel('True optimal FrFT order');

    title( ...
        sprintf( ...
        '\\sigma_p = %.4f', ...
        sigma_list(is)));

end

sgtitle( ...
    'Controlled spatial variation of optimal FrFT orders');

exportgraphics( ...
    fig1, ...
    fullfile( ...
    results_dir, ...
    'fig01_optimal_order_spatial_variation.png'), ...
    'Resolution', ...
    180);

%% 12. Figure 2: image entropy versus spatial variation

fig2 = figure( ...
    'Name', ...
    'EXP04 - Image entropy tradeoff', ...
    'Color', ...
    'w');

plot( ...
    sigma_list, ...
    image_entropy_trad, ...
    'o-', ...
    'LineWidth', ...
    1.5);

hold on;

plot( ...
    sigma_list, ...
    image_entropy_fast, ...
    's-', ...
    'LineWidth', ...
    1.5);

plot( ...
    sigma_list, ...
    image_entropy_fine, ...
    '^-', ...
    'LineWidth', ...
    1.5);

hold off;

grid on;

xlabel( ...
    'Spatial order dispersion \sigma_p');

ylabel( ...
    'Refocused image entropy');

title( ...
    'Focusing quality versus spatial variation');

legend( ...
    'Traditional', ...
    'Fast', ...
    'Fine', ...
    'Location', ...
    'best');

exportgraphics( ...
    fig2, ...
    fullfile( ...
    results_dir, ...
    'fig02_image_entropy_vs_spatial_variation.png'), ...
    'Resolution', ...
    180);

%% 13. Figure 3: order-estimation RMSE

fig3 = figure( ...
    'Name', ...
    'EXP04 - Order RMSE', ...
    'Color', ...
    'w');

plot( ...
    sigma_list, ...
    order_rmse_trad, ...
    'o-', ...
    'LineWidth', ...
    1.5);

hold on;

plot( ...
    sigma_list, ...
    order_rmse_fast, ...
    's-', ...
    'LineWidth', ...
    1.5);

plot( ...
    sigma_list, ...
    order_rmse_fine, ...
    '^-', ...
    'LineWidth', ...
    1.5);

hold off;

grid on;

xlabel( ...
    'Spatial order dispersion \sigma_p');

ylabel( ...
    'Order RMSE');

title( ...
    'Optimal-order mismatch versus spatial variation');

legend( ...
    'Traditional', ...
    'Fast', ...
    'Fine', ...
    'Location', ...
    'best');

exportgraphics( ...
    fig3, ...
    fullfile( ...
    results_dir, ...
    'fig03_order_rmse_vs_spatial_variation.png'), ...
    'Resolution', ...
    180);

%% 14. Figure 4: FrFT evaluation counts

fig4 = figure( ...
    'Name', ...
    'EXP04 - FrFT calls', ...
    'Color', ...
    'w');

plot( ...
    sigma_list, ...
    calls_trad, ...
    'o-', ...
    'LineWidth', ...
    1.5);

hold on;

plot( ...
    sigma_list, ...
    calls_fast, ...
    's-', ...
    'LineWidth', ...
    1.5);

plot( ...
    sigma_list, ...
    calls_fine, ...
    '^-', ...
    'LineWidth', ...
    1.5);

hold off;

grid on;

xlabel( ...
    'Spatial order dispersion \sigma_p');

ylabel( ...
    'Total FrFT evaluations');

title( ...
    'Computational burden versus spatial variation');

legend( ...
    'Traditional', ...
    'Fast', ...
    'Fine', ...
    'Location', ...
    'best');

exportgraphics( ...
    fig4, ...
    fullfile( ...
    results_dir, ...
    'fig04_frft_calls_vs_spatial_variation.png'), ...
    'Resolution', ...
    180);

%% 15. Figure 5: runtime

fig5 = figure( ...
    'Name', ...
    'EXP04 - Runtime', ...
    'Color', ...
    'w');

plot( ...
    sigma_list, ...
    runtime_trad, ...
    'o-', ...
    'LineWidth', ...
    1.5);

hold on;

plot( ...
    sigma_list, ...
    runtime_fast, ...
    's-', ...
    'LineWidth', ...
    1.5);

plot( ...
    sigma_list, ...
    runtime_fine, ...
    '^-', ...
    'LineWidth', ...
    1.5);

hold off;

grid on;

xlabel( ...
    'Spatial order dispersion \sigma_p');

ylabel( ...
    'Runtime (s)');

title( ...
    'Runtime versus spatial variation');

legend( ...
    'Traditional', ...
    'Fast', ...
    'Fine', ...
    'Location', ...
    'best');

exportgraphics( ...
    fig5, ...
    fullfile( ...
    results_dir, ...
    'fig05_runtime_vs_spatial_variation.png'), ...
    'Resolution', ...
    180);

%% 16. Figure 6: quality-cost plane
%
% This is particularly relevant to our later project:
%
%       lower entropy = better focusing
%       fewer calls    = lower computation

fig6 = figure( ...
    'Name', ...
    'EXP04 - Quality cost plane', ...
    'Color', ...
    'w');

scatter( ...
    calls_trad, ...
    image_entropy_trad, ...
    60, ...
    'filled');

hold on;

scatter( ...
    calls_fast, ...
    image_entropy_fast, ...
    60, ...
    'filled');

scatter( ...
    calls_fine, ...
    image_entropy_fine, ...
    60, ...
    'filled');

for is = 1:n_sigma

    text( ...
        calls_fast(is), ...
        image_entropy_fast(is), ...
        sprintf(' %.3f', sigma_list(is)));

    text( ...
        calls_fine(is), ...
        image_entropy_fine(is), ...
        sprintf(' %.3f', sigma_list(is)));

end

hold off;

grid on;

xlabel( ...
    'Total FrFT evaluations');

ylabel( ...
    'Refocused image entropy');

title( ...
    'Focusing-quality / computation trade-off');

legend( ...
    'Traditional', ...
    'Fast', ...
    'Fine', ...
    'Location', ...
    'best');

exportgraphics( ...
    fig6, ...
    fullfile( ...
    results_dir, ...
    'fig06_quality_cost_plane.png'), ...
    'Resolution', ...
    180);

%% 17. Figure 7: largest-sigma refocusing example
%
% Display energy matrices in dB.
%
% These are not literal SAR intensity images. They are controlled
% multi-azimuth-line FrFT outputs used to visualize whether each line has
% been concentrated successfully.

example_input_power = ...
    abs(example_input).^2;

example_fast_power = ...
    abs(example_fast).^2;

example_fine_power = ...
    abs(example_fine).^2;

example_trad_power = ...
    abs(example_trad).^2;

example_input_dB = ...
    10*log10( ...
    example_input_power / ...
    max(example_input_power(:)) ...
    + eps);

example_fast_dB = ...
    10*log10( ...
    example_fast_power / ...
    max(example_fast_power(:)) ...
    + eps);

example_fine_dB = ...
    10*log10( ...
    example_fine_power / ...
    max(example_fine_power(:)) ...
    + eps);

example_trad_dB = ...
    10*log10( ...
    example_trad_power / ...
    max(example_trad_power(:)) ...
    + eps);

fig7 = figure( ...
    'Name', ...
    'EXP04 - Strong spatial variation example', ...
    'Color', ...
    'w');

tiledlayout( ...
    2, ...
    2, ...
    'Padding', ...
    'compact', ...
    'TileSpacing', ...
    'compact');

nexttile;

imagesc( ...
    t, ...
    line_index, ...
    example_input_dB);

axis xy;

xlabel('Normalized slow time');
ylabel('Azimuth-line index');

title('Original spatially variant LFM lines');

clim([-35 0]);

nexttile;

imagesc( ...
    u, ...
    line_index, ...
    example_fast_dB);

axis xy;

xlabel('Fractional coordinate u');
ylabel('Azimuth-line index');

title('Fast refocusing');

clim([-35 0]);

nexttile;

imagesc( ...
    u, ...
    line_index, ...
    example_fine_dB);

axis xy;

xlabel('Fractional coordinate u');
ylabel('Azimuth-line index');

title('Fine refocusing');

clim([-35 0]);

nexttile;

imagesc( ...
    u, ...
    line_index, ...
    example_trad_dB);

axis xy;

xlabel('Fractional coordinate u');
ylabel('Azimuth-line index');

title('Traditional refocusing');

clim([-35 0]);

sgtitle( ...
    sprintf( ...
    'Largest spatial variation: \\sigma_p = %.4f', ...
    sigma_list(end)));

cb = colorbar;
ylabel(cb, 'Normalized energy (dB)');

exportgraphics( ...
    fig7, ...
    fullfile( ...
    results_dir, ...
    'fig07_strong_spatial_variation_example.png'), ...
    'Resolution', ...
    180);

%% 18. Numerical summary table

SigmaP = ...
    sigma_list(:);

BestOrderEstimate = ...
    p_best_est;

ImageEntropyTraditional = ...
    image_entropy_trad;

ImageEntropyFast = ...
    image_entropy_fast;

ImageEntropyFine = ...
    image_entropy_fine;

MeanLineEntropyTraditional = ...
    mean_entropy_trad;

MeanLineEntropyFast = ...
    mean_entropy_fast;

MeanLineEntropyFine = ...
    mean_entropy_fine;

OrderRMSETraditional = ...
    order_rmse_trad;

OrderRMSEFast = ...
    order_rmse_fast;

OrderRMSEFine = ...
    order_rmse_fine;

FrFTCallsTraditional = ...
    calls_trad;

FrFTCallsFast = ...
    calls_fast;

FrFTCallsFine = ...
    calls_fine;

RuntimeTraditional_s = ...
    runtime_trad;

RuntimeFast_s = ...
    runtime_fast;

RuntimeFine_s = ...
    runtime_fine;

FastCallReductionPercent = ...
    100 * ...
    ( ...
    1 ...
    - FrFTCallsFast ./ ...
    FrFTCallsTraditional);

FineCallReductionPercent = ...
    100 * ...
    ( ...
    1 ...
    - FrFTCallsFine ./ ...
    FrFTCallsTraditional);

summary_table = table( ...
    SigmaP, ...
    BestOrderEstimate, ...
    ImageEntropyTraditional, ...
    ImageEntropyFast, ...
    ImageEntropyFine, ...
    MeanLineEntropyTraditional, ...
    MeanLineEntropyFast, ...
    MeanLineEntropyFine, ...
    OrderRMSETraditional, ...
    OrderRMSEFast, ...
    OrderRMSEFine, ...
    FrFTCallsTraditional, ...
    FrFTCallsFast, ...
    FrFTCallsFine, ...
    FastCallReductionPercent, ...
    FineCallReductionPercent, ...
    RuntimeTraditional_s, ...
    RuntimeFast_s, ...
    RuntimeFine_s);

disp(' ');
disp('================ EXP04 SUMMARY TABLE ================');
disp(summary_table);

%% 19. Console interpretation

fprintf('\n');
fprintf('================ EXP04 INTERPRETATION ================\n');

fprintf( ...
    'Baseline true best-line order p0 = %.6f\n\n', ...
    p0);

for is = 1:n_sigma

    fprintf( ...
        'sigma_p = %.4f\n', ...
        sigma_list(is));

    fprintf( ...
        '  image entropy T/Fast/Fine = %.4f / %.4f / %.4f\n', ...
        image_entropy_trad(is), ...
        image_entropy_fast(is), ...
        image_entropy_fine(is));

    fprintf( ...
        '  order RMSE   T/Fast/Fine = %.5f / %.5f / %.5f\n', ...
        order_rmse_trad(is), ...
        order_rmse_fast(is), ...
        order_rmse_fine(is));

    fprintf( ...
        '  FrFT calls   T/Fast/Fine = %d / %d / %d\n', ...
        calls_trad(is), ...
        calls_fast(is), ...
        calls_fine(is));

    fprintf( ...
        '  Fast call reduction       = %.2f %%\n', ...
        FastCallReductionPercent(is));

    fprintf( ...
        '  Fine call reduction       = %.2f %%\n\n', ...
        FineCallReductionPercent(is));

end

fprintf('Expected mechanism:\n');
fprintf('  sigma_p ~= 0:\n');
fprintf('    Fast, Fine and Traditional should have similar quality.\n\n');

fprintf('  sigma_p increases:\n');
fprintf('    Fast order RMSE should increase and focusing should degrade.\n\n');

fprintf('  Fine:\n');
fprintf('    should remain close to Traditional for moderate spatial variation,\n');
fprintf('    while requiring substantially fewer FrFT evaluations.\n\n');

fprintf('Research interpretation:\n');
fprintf('  Increasing sigma_p provides a controlled bridge from the\n');
fprintf('  single-order linear-motion assumption toward spatial-variant\n');
fprintf('  defocusing, where the later MC-LFM model becomes necessary.\n');

fprintf('=======================================================\n');

%% 20. Save

save( ...
    fullfile( ...
    results_dir, ...
    'exp04_summary.mat'), ...
    'p0', ...
    'sigma_list', ...
    'z', ...
    'amplitude', ...
    'f0', ...
    'p_true_all', ...
    'p_best_est', ...
    'p_fast_all', ...
    'p_fine_all', ...
    'p_trad_all', ...
    'summary_table', ...
    'example_input', ...
    'example_fast', ...
    'example_fine', ...
    'example_trad', ...
    'example_p_true');

writetable( ...
    summary_table, ...
    fullfile( ...
    results_dir, ...
    'exp04_summary.csv'));

fprintf('\nSaved EXP04 results to:\n%s\n', results_dir);

%% ========================================================================
% LOCAL FUNCTION 1
% Fine refocusing search around p_best
% ========================================================================

function result = local_entropy_search( ...
    x, ...
    t, ...
    u, ...
    p_initial, ...
    h, ...
    p_bounds)

%LOCAL_ENTROPY_SEARCH
% Fine-only directional minimum-entropy search.
%
% Unlike minimum_entropy_search.m:
%
%   - there is no global coarse stage;
%   - p_best is already supplied as the initial value;
%   - only the fine step h is used.
%
% This mirrors the central computational idea of the paper's Fine approach:
%
%       use p_best as initial value
%       -> avoid coarse search for every other azimuth line.

    p_min = p_bounds(1);
    p_max = p_bounds(2);

    p0 = ...
        min( ...
        max(p_initial, p_min), ...
        p_max);

    n_frft = 0;

    %% Evaluate initial point

    E0 = evaluate_entropy(p0);

    %% First test positive direction

    h_direction = abs(h);

    p1 = ...
        p0 + h_direction;

    if p1 > p_max

        h_direction = ...
            -h_direction;

        p1 = ...
            p0 + h_direction;

    end

    if p1 < p_min || p1 > p_max

        result.p_opt = p0;
        result.entropy_opt = E0;
        result.n_frft = n_frft;

        return;

    end

    E1 = ...
        evaluate_entropy(p1);

    %% If positive direction is uphill, try negative direction

    if E1 >= E0

        h_direction = ...
            -h_direction;

        p1 = ...
            p0 + h_direction;

        if p1 < p_min || p1 > p_max

            result.p_opt = p0;
            result.entropy_opt = E0;
            result.n_frft = n_frft;

            return;

        end

        E1 = ...
            evaluate_entropy(p1);

        %% If both sides are uphill, initial point is already a local min

        if E1 >= E0

            result.p_opt = p0;
            result.entropy_opt = E0;
            result.n_frft = n_frft;

            return;

        end

    end

    %% Continue downhill

    p_current = p1;
    E_current = E1;

    while true

        p_next = ...
            p_current + h_direction;

        if p_next < p_min || p_next > p_max
            break;
        end

        E_next = ...
            evaluate_entropy(p_next);

        if E_next >= E_current
            break;
        end

        p_current = p_next;
        E_current = E_next;

    end

    result.p_opt = ...
        p_current;

    result.entropy_opt = ...
        E_current;

    result.n_frft = ...
        n_frft;

    %% Nested entropy evaluator

    function H = evaluate_entropy(p)

        Xp = ...
            frft_direct( ...
            x, ...
            t, ...
            p, ...
            u);

        H = ...
            signal_entropy(Xp);

        n_frft = ...
            n_frft + 1;

    end

end

%% ========================================================================
% LOCAL FUNCTION 2
% Global 2-D energy entropy
% ========================================================================

function H = global_image_entropy(Y)

%GLOBAL_IMAGE_ENTROPY
%
% Shannon entropy of the normalized energy distribution of the full
% multi-line refocused result:
%
%       P(m,n) = |Y(m,n)|^2
%
%       p(m,n) = P(m,n) / sum(P(:))
%
%       H = -sum p log p
%
% This follows the same general energy-concentration principle used by the
% paper for image entropy.

    power_Y = ...
        abs(Y).^2;

    total_energy = ...
        sum(power_Y(:));

    if total_energy <= 0

        H = NaN;
        return;

    end

    p = ...
        power_Y(:) / ...
        total_energy;

    p = ...
        p(p > 0);

    H = ...
        -sum( ...
        p .* log(p));

end