function cfg = config_exp09c3b1_3()
%CONFIG_EXP09C3B1_3
% EXP009 / Pilot-01 / C3-B1.3
% State-Conditioned Harm-Aware Fallback Allocation
%
% C3-B1.2 established:
%   1) Physical state is reproducible.
%   2) Beneficial fate remains difficult to predict within state.
%   3) Harmful fate is strongly observable from q-landscape morphology.
%
% C3-B1.3 therefore asks whether the asymmetric decomposition
%
%       opportunity(state)  -  harm_risk(morphology)
%
% can allocate fallback computation better than:
%   - StateOnly;
%   - direct State+feature fusion.
%
% IMPORTANT:
%   This experiment does NOT rerun signal generation.
%   It consumes C3-B1.2 rich trial banks and reconstructs the same
%   cross-fitted state prior.

%% Reproducibility
cfg.seed = 20260909;

%% Input / output
cfg.input_dir = '';
cfg.output_dir = '';

%% State prior -- must match C3-B1 / C3-B1.2
cfg.state_utility_smooth_window = 7;

%% Primary morphology features
% Chosen from the C3-B1.2 mechanism result:
%   local curvature, peak competition, peak width, q-geometry.
% We keep prominence/entropy as low-level context because MorphologyOnly
% in C3-B1.2 was trained with them.
cfg.morphology_features = { ...
    'cheap_prominence', ...
    'cheap_entropy', ...
    'peak_second_ratio', ...
    'peak_margin_norm', ...
    'top2_q_separation', ...
    'width50_q', ...
    'local_curvature_norm', ...
    'local_asymmetry', ...
    'peak_robust_z'};

%% All realization observables (for direct StateAll baseline)
cfg.all_observable_features = { ...
    'cheap_prominence', ...
    'cheap_entropy', ...
    'peak_second_ratio', ...
    'peak_margin_norm', ...
    'top2_q_separation', ...
    'width50_q', ...
    'local_curvature_norm', ...
    'local_asymmetry', ...
    'peak_robust_z', ...
    'strong_q_response_ratio', ...
    'strong_q_neighborhood_fraction', ...
    'peak_to_strong_q_distance', ...
    'strong_spec_peak_fraction', ...
    'strong_spec_local_fraction', ...
    'strong_spec_entropy', ...
    'subap_q_std_norm', ...
    'subap_q_range_norm', ...
    'subap_consensus_fraction', ...
    'subap_prominence_cv'};

%% Predictive models
cfg.ridge_lambda = 0.10;
cfg.irls_max_iter = 100;
cfg.irls_tol = 1e-8;
cfg.prob_clip = 1e-6;

%% OOF tuning
% Fold by sequence_id, shared across Smooth / Abrupt.
% Thus the same MC index is held out in both regimes.
cfg.num_folds = 5;

%% Harm-aware score families
% OpportunityMinusHarm:
%
%   score = z(state_prior) - lambda * p_H
%
% lambda is selected from OOF TRAIN only.
cfg.lambda_grid = (0:0.10:4.00).';

% Hard-veto threshold is chosen from OOF p_H quantiles.
cfg.veto_quantile_grid = (0.10:0.05:0.90).';

% Large ranking penalty used by the hard-veto and oracle-harm-veto
% policies. It only changes ordering, never labels.
cfg.veto_rank_penalty = 100;

%% Budget
cfg.budget_grid = unique([ ...
    (0:0.025:0.50), ...
    (0.55:0.05:1.00)]).';

cfg.primary_budget = 0.25;
cfg.report_budgets = [0.10 0.25 0.50];

%% Policy names
cfg.policy_names = { ...
    'StateOnly', ...
    'HarmOnlyMorph', ...
    'StateMorphDirect', ...
    'StateAllDirect', ...
    'OpportunityMinusHarm', ...
    'OpportunityHardVeto', ...
    'OracleHarmVeto', ...
    'TrialOracle', ...
    'RandomExpected'};

%% Figures
cfg.figure_visible = 'off';

end
