function cfg = config_exp09c3b1_1()
%CONFIG_EXP09C3B1_1
% EXP009-C3-B1.1: State + Instantaneous Realization Complementarity
%
% Diagnostic objective:
%   Does instantaneous residual evidence add useful within-state
%   information beyond the signal-generated line/state prior?
%
% No new signal simulation is run here. This experiment reuses the
% independent TRAIN/TEST signal-level banks generated by C3-B1.

%% Reproducibility
cfg.seed = 20260909;

%% Input
% Leave empty to use the standard C3-B1 output directory.
cfg.c3b1_result_dir = '';

%% State prior
% Same short smoothing used by C3-B1.
cfg.state_utility_smooth_window = 7;

% TRAIN state priors are CROSS-FITTED:
% for each training sequence, its own outcome is excluded from the
% line-level utility curve used as that sequence's state feature.
cfg.crossfit_train_state = true;

%% Instantaneous observables
% Keep the first diagnostic intentionally small.
cfg.instant_features = { ...
    'cheap_prominence', ...
    'cheap_entropy'};

%% Predictive model
% Two logistic heads:
%   pB = P(Beneficial | features)
%   pH = P(Harmful    | features)
%
% allocation score:
%   V = pB - pH
%
% Four nested feature sets:
%   StateOnly
%   InstantOnly
%   Additive
%   Interaction
%
% Interaction adds state*risk_prom and state*risk_entropy.
cfg.model_names = { ...
    'StateOnly', ...
    'InstantOnly', ...
    'Additive', ...
    'Interaction'};

% Small fixed ridge penalty. This is a diagnostic experiment; we avoid
% hyperparameter searching that could obscure the feature-complementarity
% question.
cfg.ridge_lambda = 0.10;

cfg.irls_max_iter = 100;
cfg.irls_tol = 1e-8;
cfg.prob_clip = 1e-6;

%% Budget evaluation
cfg.budget_grid = (0:0.05:1).';
cfg.report_budgets = [0.10 0.25 0.50];

% Primary matched-budget operating point used in the complementarity
% summary. Kept identical to the C1/C2/C3 diagnostic convention.
cfg.tune_budget = 0.25;

%% Conditional diagnostics
cfg.num_state_bins = 5;

%% Practical GO diagnostics (reported, not hard-coded as claims)
cfg.delta_auc_notice = 0.01;
cfg.delta_recall_notice = 0.005;
cfg.within_line_auc_notice = 0.55;

%% Figures
cfg.figure_visible = 'off';

%% Output
cfg.output_dir = '';

end
