function results = exp09c3b1_signal_level_continuous_state()
%EXP09C3B1_SIGNAL_LEVEL_CONTINUOUS_STATE
% EXP009 / Pilot-01 / Experiment C3-B1
%
% Signal-Level Continuous Azimuth-State Validation
%
% -------------------------------------------------------------------------
% Research question
% -------------------------------------------------------------------------
% C3-A showed, in a bootstrap Markov-state experiment, that:
%
%   persistent latent risk state
%       -> history improves observability
%       -> history improves computation allocation
%       -> abrupt state change causes EMA lag
%       -> innovation reset mitigates that lag.
%
% C3-B1 asks whether the same chain appears when the "state" is no longer
% imposed by a Markov sampler, but is generated by the signal model itself.
%
% -------------------------------------------------------------------------
% Signal-level state
% -------------------------------------------------------------------------
% Across neighboring azimuth lines k:
%
%   A_w/A_s(k)
%   q_s(k)-q_w
%
% vary continuously.
%
% For every line, the complete controlled weak-stage chain is rerun:
%
%   strong LFM + weak LFM + AWGN
%       -> Cheap fixed-notch strong residual
%       -> weak q search
%
% and independently:
%
%   original mixture
%       -> off-grid parametric strong refit
%       -> weak q search.
%
% Thus:
%
%   Beneficial(k,mc)
%   Harmful(k,mc)
%
% are generated from the actual signal-processing chain rather than from
% an imposed state label.
%
% -------------------------------------------------------------------------
% Important controlled boundary
% -------------------------------------------------------------------------
% q_strong is still treated as known/oracle at each line.
%
% This preserves the same weak-stage isolation used in A/B/C1 and prevents
% dominant-q tracking error from being mixed into the C3 history question.
%
% C3-B2 can later replace q_strong by practical estimation/tracking.
%
% -------------------------------------------------------------------------
% Two regimes
% -------------------------------------------------------------------------
% Smooth:
%   continuously varying weak ratio and q separation.
%
% Abrupt:
%   same baseline trajectory, plus one physical parameter jump.
%
% -------------------------------------------------------------------------
% History policies
% -------------------------------------------------------------------------
% InstantPE:
%   percentile risk from Cheap prominence + entropy.
%
% EMA:
%   causal exponential history aggregation.
%
% EMAReset:
%   EMA with innovation-triggered history reset.
%
% PhysicalStatePrior:
%   diagnostic line-level state oracle:
%       score(k) = TRAIN-estimated smoothed
%                  P(Beneficial|k)-P(Harmful|k)
%   It knows line/state, but not the TEST realization fate.
%
% TrialOracle:
%   knows TEST beneficial labels.
%
% -------------------------------------------------------------------------
% Main validation hierarchy
% -------------------------------------------------------------------------
% B1-1:
%   Does continuous physical parameter variation create a reproducible
%   line-dependent fallback-utility state?
%
% B1-2:
%   Does EMA improve observability of that signal-generated state?
%
% B1-3:
%   Does improved state observability improve Beneficial Capture and
%   Weak Recovery at matched computation?
%
% B1-4:
%   Does an abrupt physical-state change create EMA lag, and does reset
%   reduce that transition error?
%
% Run:
%   results = exp09c3b1_signal_level_continuous_state;

cfg = config_exp09c3b1();

%% Resolve paths
this_file = mfilename('fullpath');
this_dir = fileparts(this_file);
code_dir = fileparts(this_dir);
paper_root = fileparts(code_dir);

if isempty(cfg.output_dir)
    out_dir = fullfile(paper_root,'results','exp09_pilot01', ...
        'exp09c3b1_signal_level_continuous_state');
else
    out_dir = cfg.output_dir;
end

if ~exist(out_dir,'dir')
    mkdir(out_dir);
end

fprintf('\n============================================================\n');
fprintf(' EXP009-C3-B1 / Signal-Level Continuous State Validation\n');
fprintf('============================================================\n');
fprintf('Output: %s\n',out_dir);
fprintf('Lines/sequence: %d\n',cfg.num_lines);
fprintf('Train MC/regime: %d\n',cfg.num_train_mc);
fprintf('Test  MC/regime: %d\n',cfg.num_test_mc);
fprintf('SNR: %.1f dB\n\n',cfg.snr_db);

%% Common signal/search setup
N = cfg.N;
n = 0:N-1;
t = (n-N/2)/N;

q_search = cfg.q_search_min:cfg.q_search_step:cfg.q_search_max;
D_search = build_dechirp_dictionary(q_search,t,cfg);

%% Build physical trajectories
traj_smooth = build_trajectory("Smooth",cfg);
traj_abrupt = build_trajectory("Abrupt",cfg);

writetable(traj_smooth, ...
    fullfile(out_dir,'trajectory_smooth.csv'));

writetable(traj_abrupt, ...
    fullfile(out_dir,'trajectory_abrupt.csv'));

%% Precompute deterministic signal components for each regime
det_smooth = precompute_deterministic_chain( ...
    traj_smooth,t,cfg);

det_abrupt = precompute_deterministic_chain( ...
    traj_abrupt,t,cfg);

%% Generate TRAIN signal-level banks
rng(cfg.seed,'twister');

tic;
train_smooth = run_signal_mc_bank( ...
    det_smooth,traj_smooth,cfg.num_train_mc, ...
    cfg.seed+100,D_search,q_search,t,cfg);
time_train_smooth = toc;

tic;
train_abrupt = run_signal_mc_bank( ...
    det_abrupt,traj_abrupt,cfg.num_train_mc, ...
    cfg.seed+200,D_search,q_search,t,cfg);
time_train_abrupt = toc;

%% Generate independent TEST banks
tic;
test_smooth = run_signal_mc_bank( ...
    det_smooth,traj_smooth,cfg.num_test_mc, ...
    cfg.seed+1100,D_search,q_search,t,cfg);
time_test_smooth = toc;

tic;
test_abrupt = run_signal_mc_bank( ...
    det_abrupt,traj_abrupt,cfg.num_test_mc, ...
    cfg.seed+1200,D_search,q_search,t,cfg);
time_test_abrupt = toc;

%% Save raw signal-level trial banks
writetable(train_smooth, ...
    fullfile(out_dir,'train_trials_smooth.csv'));

writetable(train_abrupt, ...
    fullfile(out_dir,'train_trials_abrupt.csv'));

writetable(test_smooth, ...
    fullfile(out_dir,'test_trials_smooth.csv'));

writetable(test_abrupt, ...
    fullfile(out_dir,'test_trials_abrupt.csv'));

%% ------------------------------------------------------------------------
% C3-B1-1: Does physical continuity create a reproducible risk state?
state_smooth = estimate_line_state( ...
    train_smooth,test_smooth,cfg);

state_abrupt = estimate_line_state( ...
    train_abrupt,test_abrupt,cfg);

state_smooth.regime = repmat("Smooth",height(state_smooth),1);
state_abrupt.regime = repmat("Abrupt",height(state_abrupt),1);

state_summary = [state_smooth;state_abrupt];
state_summary = movevars(state_summary,'regime','Before',1);

writetable(state_summary, ...
    fullfile(out_dir,'signal_level_state_summary.csv'));

rho_state_repro_smooth = spearman_manual( ...
    state_smooth.train_utility_smooth, ...
    state_smooth.test_utility_smooth);

rho_state_repro_abrupt = spearman_manual( ...
    state_abrupt.train_utility_smooth, ...
    state_abrupt.test_utility_smooth);

rmse_state_smooth = sqrt(mean( ...
    (state_smooth.train_utility_smooth - ...
     state_smooth.test_utility_smooth).^2));

rmse_state_abrupt = sqrt(mean( ...
    (state_abrupt.train_utility_smooth - ...
     state_abrupt.test_utility_smooth).^2));

if rho_state_repro_smooth < cfg.min_train_test_state_rho_warning
    warning(['Smooth train/test state utility is weakly reproducible ' ...
        '(rho=%.3f). Interpret history results cautiously.'], ...
        rho_state_repro_smooth);
end

if rho_state_repro_abrupt < cfg.min_train_test_state_rho_warning
    warning(['Abrupt train/test state utility is weakly reproducible ' ...
        '(rho=%.3f). Interpret history results cautiously.'], ...
        rho_state_repro_abrupt);
end

%% Attach TRAIN-estimated state targets to all trial banks
[train_smooth,test_smooth] = attach_state_target( ...
    train_smooth,test_smooth,state_smooth);

[train_abrupt,test_abrupt] = attach_state_target( ...
    train_abrupt,test_abrupt,state_abrupt);

%% Instantaneous PE calibration
% Use SMOOTH TRAIN only. Abrupt regime therefore tests generalization
% rather than receiving a separate feature-distribution calibration.
calib = build_instantaneous_calibration(train_smooth);

train_smooth = add_instant_score(train_smooth,calib);
test_smooth  = add_instant_score(test_smooth,calib);

train_abrupt = add_instant_score(train_abrupt,calib);
test_abrupt  = add_instant_score(test_abrupt,calib);

%% ------------------------------------------------------------------------
% Tune EMA alpha on SMOOTH TRAIN only.
alpha_grid = cfg.alpha_grid(:);
alpha_recall = nan(numel(alpha_grid),1);
alpha_state_rho = nan(numel(alpha_grid),1);

for ia = 1:numel(alpha_grid)
    a = alpha_grid(ia);

    T = apply_history(train_smooth,a,NaN);

    alpha_recall(ia) = policy_recall_at_budget( ...
        T,'ema_score',cfg.tune_budget);

    alpha_state_rho(ia) = spearman_manual( ...
        T.ema_score,T.state_utility_norm);
end

[~,best_alpha_idx] = max(alpha_recall);
best_alpha = alpha_grid(best_alpha_idx);

alpha_sweep = table( ...
    alpha_grid,alpha_recall,alpha_state_rho, ...
    'VariableNames',{ ...
    'alpha','train_recall_at_tune_budget', ...
    'train_state_rho'});

writetable(alpha_sweep, ...
    fullfile(out_dir,'alpha_sweep.csv'));

%% Tune reset threshold on ABRUPT TRAIN with alpha fixed.
abrupt_ema_train = apply_history( ...
    train_abrupt,best_alpha,NaN);

innovation_abs = abs(abrupt_ema_train.innovation);
innovation_abs = innovation_abs(isfinite(innovation_abs));

reset_q = cfg.reset_quantile_grid(:);
reset_thr = nan(numel(reset_q),1);
reset_recall = nan(numel(reset_q),1);
reset_jump_error = nan(numel(reset_q),1);

for iq = 1:numel(reset_q)
    thr = empirical_quantile(innovation_abs,reset_q(iq));
    reset_thr(iq) = thr;

    T = apply_history(train_abrupt,best_alpha,thr);

    reset_recall(iq) = policy_recall_at_budget( ...
        T,'reset_score',cfg.tune_budget);

    reset_jump_error(iq) = post_jump_tracking_error( ...
        T,cfg,5);
end

% Primary tuning criterion remains global recovery at the selected budget.
% In exact ties, prefer the smaller post-jump tracking error.
best_reset_idx = select_reset_candidate( ...
    reset_recall,reset_jump_error);

best_reset_quantile = reset_q(best_reset_idx);
best_reset_threshold = reset_thr(best_reset_idx);

reset_sweep = table( ...
    reset_q,reset_thr,reset_recall,reset_jump_error, ...
    'VariableNames',{ ...
    'reset_quantile','reset_threshold', ...
    'train_recall_at_tune_budget', ...
    'train_post_jump_tracking_error'});

writetable(reset_sweep, ...
    fullfile(out_dir,'reset_sweep.csv'));

%% Apply selected history policies
train_smooth = apply_history( ...
    train_smooth,best_alpha,best_reset_threshold);

test_smooth = apply_history( ...
    test_smooth,best_alpha,best_reset_threshold);

train_abrupt = apply_history( ...
    train_abrupt,best_alpha,best_reset_threshold);

test_abrupt = apply_history( ...
    test_abrupt,best_alpha,best_reset_threshold);

%% ------------------------------------------------------------------------
% C3-B1-2: state observability
diag_smooth = state_observability_diagnostics( ...
    train_smooth,test_smooth,"Smooth");

diag_abrupt = state_observability_diagnostics( ...
    train_abrupt,test_abrupt,"Abrupt");

state_diagnostics = [diag_smooth;diag_abrupt];

writetable(state_diagnostics, ...
    fullfile(out_dir,'state_observability_diagnostics.csv'));

%% ------------------------------------------------------------------------
% C3-B1-3: budget allocation
budget_curves = table();

policies = { ...
    'instant_score',"InstantPE"; ...
    'ema_score',"EMA"; ...
    'reset_score',"EMAReset"; ...
    'state_prior_score',"PhysicalStatePrior"};

regimes = ["Smooth","Abrupt"];
train_sets = {train_smooth,train_abrupt};
test_sets  = {test_smooth,test_abrupt};

for ir = 1:2
    Ttr = train_sets{ir};
    Tte = test_sets{ir};

    for ip = 1:size(policies,1)
        C = evaluate_score_policy_curve( ...
            Ttr,Tte,policies{ip,1},cfg.budget_grid);

        C.regime = repmat(regimes(ir),height(C),1);
        C.policy = repmat(policies{ip,2},height(C),1);

        budget_curves = [budget_curves;C]; %#ok<AGROW>
    end

    Cto = trial_oracle_curve(Tte,cfg.budget_grid);
    Cto.regime = repmat(regimes(ir),height(Cto),1);
    Cto.policy = repmat("TrialOracle",height(Cto),1);

    Cr = random_expected_curve(Tte,cfg.budget_grid);
    Cr.regime = repmat(regimes(ir),height(Cr),1);
    Cr.policy = repmat("RandomExpected",height(Cr),1);

    budget_curves = [budget_curves;Cto;Cr]; %#ok<AGROW>
end

budget_curves = movevars( ...
    budget_curves,{'regime','policy'},'Before',1);

writetable(budget_curves, ...
    fullfile(out_dir,'signal_level_budget_curves.csv'));

%% Highlighted operating points
point_rows = {};

for ir = 1:2
    regime = regimes(ir);
    Creg = budget_curves(budget_curves.regime==regime,:);

    pols = unique(Creg.policy,'stable');

    for ip = 1:numel(pols)
        Cp = Creg(Creg.policy==pols(ip),:);

        for ib = 1:numel(cfg.report_budgets)
            b = cfg.report_budgets(ib);
            [~,ii] = min(abs(Cp.target_budget-b));

            point_rows(end+1,:) = { ... %#ok<AGROW>
                char(regime),char(pols(ip)),b, ...
                Cp.actual_trigger_rate(ii), ...
                Cp.policy_recall(ii), ...
                Cp.beneficial_capture(ii), ...
                Cp.benefit_precision(ii), ...
                Cp.harmful_fraction_among_triggers(ii), ...
                Cp.normalized_q_search_budget(ii)};
        end
    end
end

budget_points = cell2table(point_rows, ...
    'VariableNames',{ ...
    'regime','policy','target_budget','actual_trigger_rate', ...
    'policy_recall','beneficial_capture','benefit_precision', ...
    'harmful_fraction_among_triggers', ...
    'normalized_q_search_budget'});

writetable(budget_points, ...
    fullfile(out_dir,'reported_budget_points.csv'));

%% ------------------------------------------------------------------------
% C3-B1-4: abrupt-transition diagnostics
jump_line = traj_abrupt.line_index( ...
    traj_abrupt.is_jump_start);

% Robust physical-jump utility change: compare short TRAIN windows before
% and after the jump rather than adjacent smoothed samples.
jpre = max(1,jump_line-5):(jump_line-1);
jpost = jump_line:min(cfg.num_lines,jump_line+4);

jump_state_change = abs( ...
    mean(state_abrupt.train_utility_raw(jpost),'omitnan') - ...
    mean(state_abrupt.train_utility_raw(jpre),'omitnan'));

if jump_state_change < cfg.min_jump_utility_change_warning
    warning(['The chosen physical parameter jump generated only a small ' ...
        'TRAIN utility change (%.3f). Reset results may be inconclusive.'], ...
        jump_state_change);
end

jump_diag = jump_diagnostics( ...
    test_abrupt,cfg,5);

writetable(jump_diag, ...
    fullfile(out_dir,'jump_tracking_diagnostics.csv'));

%% Runtime summary
runtime_summary = table( ...
    ["TrainSmooth";"TrainAbrupt";"TestSmooth";"TestAbrupt"], ...
    [time_train_smooth;time_train_abrupt; ...
     time_test_smooth;time_test_abrupt], ...
    'VariableNames',{'bank','runtime_seconds'});

writetable(runtime_summary, ...
    fullfile(out_dir,'runtime_summary.csv'));

%% Save representative TEST sequence
rep_smooth = test_smooth(test_smooth.sequence_id==1,:);
rep_abrupt = test_abrupt(test_abrupt.sequence_id==1,:);

writetable(rep_smooth, ...
    fullfile(out_dir,'representative_smooth_sequence.csv'));

writetable(rep_abrupt, ...
    fullfile(out_dir,'representative_abrupt_sequence.csv'));

%% Console summary
fprintf('================ C3-B1 STATE REPRODUCIBILITY ================\n');
fprintf('Smooth train/test utility rho = %.3f, RMSE = %.4f\n', ...
    rho_state_repro_smooth,rmse_state_smooth);
fprintf('Abrupt train/test utility rho = %.3f, RMSE = %.4f\n', ...
    rho_state_repro_abrupt,rmse_state_abrupt);

fprintf('\n================ C3-B1 TUNING ================================\n');
fprintf('Best EMA alpha        = %.3f\n',best_alpha);
fprintf('Best reset quantile   = %.3f\n',best_reset_quantile);
fprintf('Best reset threshold  = %.6f\n',best_reset_threshold);
fprintf('Jump line             = %d\n',jump_line);
fprintf('TRAIN utility jump    = %.4f\n',jump_state_change);

fprintf('\n================ C3-B1 STATE OBSERVABILITY ==================\n');
for i = 1:height(state_diagnostics)
    fprintf(['%-7s %-20s rho_trial=%.3f rho_lineMean=%.3f ' ...
        'AUC(B)=%.3f\n'], ...
        state_diagnostics.regime{i}, ...
        state_diagnostics.policy{i}, ...
        state_diagnostics.trial_level_state_rho(i), ...
        state_diagnostics.line_mean_state_rho(i), ...
        state_diagnostics.beneficial_auc(i));
end

fprintf('\n================ C3-B1 25%% BUDGET ===========================\n');
rows25 = budget_points(abs(budget_points.target_budget-0.25)<1e-12,:);

for i = 1:height(rows25)
    fprintf(['%-7s %-20s actual=%.3f recall=%.3f ' ...
        'capture=%.3f precision=%.3f harm=%.3f\n'], ...
        rows25.regime{i},rows25.policy{i}, ...
        rows25.actual_trigger_rate(i), ...
        rows25.policy_recall(i), ...
        rows25.beneficial_capture(i), ...
        rows25.benefit_precision(i), ...
        rows25.harmful_fraction_among_triggers(i));
end

fprintf('\n================ C3-B1 JUMP TRACKING ========================\n');
disp(jump_diag);
fprintf('=============================================================\n');

%% Text summary
fid = fopen(fullfile(out_dir,'summary.txt'),'w');

fprintf(fid,'EXP009-C3-B1 Signal-Level Continuous Azimuth-State Validation\n');
fprintf(fid,'============================================================\n\n');

fprintf(fid,'Experimental boundary\n');
fprintf(fid,'---------------------\n');
fprintf(fid,['q_strong is oracle/known at every line. Weak q is fixed. ' ...
    'Weak ratio and q separation vary physically across azimuth lines.\n']);
fprintf(fid,['Cheap branch uses the same controlled strong-residual chain ' ...
    'as C1/C2.1; fallback uses the C1 off-grid parametric refit.\n\n']);

fprintf(fid,'State reproducibility\n');
fprintf(fid,'---------------------\n');
fprintf(fid,'Smooth train/test utility rho: %.6f\n',rho_state_repro_smooth);
fprintf(fid,'Smooth train/test utility RMSE: %.6f\n',rmse_state_smooth);
fprintf(fid,'Abrupt train/test utility rho: %.6f\n',rho_state_repro_abrupt);
fprintf(fid,'Abrupt train/test utility RMSE: %.6f\n\n',rmse_state_abrupt);

fprintf(fid,'Tuning\n');
fprintf(fid,'------\n');
fprintf(fid,'Best EMA alpha: %.6f\n',best_alpha);
fprintf(fid,'Best reset quantile: %.6f\n',best_reset_quantile);
fprintf(fid,'Best reset threshold: %.6f\n',best_reset_threshold);
fprintf(fid,'Jump line: %d\n',jump_line);
fprintf(fid,'Train utility jump magnitude: %.6f\n\n',jump_state_change);

fprintf(fid,'State observability\n');
fprintf(fid,'-------------------\n');
for i = 1:height(state_diagnostics)
    fprintf(fid, ...
        ['%s %s trialRho=%.6f lineMeanRho=%.6f ' ...
         'aucB=%.6f\n'], ...
        state_diagnostics.regime{i}, ...
        state_diagnostics.policy{i}, ...
        state_diagnostics.trial_level_state_rho(i), ...
        state_diagnostics.line_mean_state_rho(i), ...
        state_diagnostics.beneficial_auc(i));
end

fprintf(fid,'\nHighlighted budget points\n');
fprintf(fid,'-------------------------\n');
for i = 1:height(budget_points)
    fprintf(fid, ...
        ['%s %s target=%.3f actual=%.6f recall=%.6f ' ...
         'capture=%.6f precision=%.6f harm=%.6f budget=%.6f\n'], ...
        budget_points.regime{i}, ...
        budget_points.policy{i}, ...
        budget_points.target_budget(i), ...
        budget_points.actual_trigger_rate(i), ...
        budget_points.policy_recall(i), ...
        budget_points.beneficial_capture(i), ...
        budget_points.benefit_precision(i), ...
        budget_points.harmful_fraction_among_triggers(i), ...
        budget_points.normalized_q_search_budget(i));
end

fprintf(fid,'\nJump tracking\n');
fprintf(fid,'-------------\n');
for i = 1:height(jump_diag)
    fprintf(fid, ...
        '%s postJumpMAE=%.6f globalMAE=%.6f\n', ...
        jump_diag.policy{i}, ...
        jump_diag.mean_post_jump_state_abs_error(i), ...
        jump_diag.mean_global_state_abs_error(i));
end

fprintf(fid,'\nRuntime\n');
fprintf(fid,'-------\n');
for i = 1:height(runtime_summary)
    fprintf(fid,'%s %.3f s\n', ...
        runtime_summary.bank{i}, ...
        runtime_summary.runtime_seconds(i));
end

fclose(fid);

%% Figures
make_figures( ...
    out_dir,cfg,traj_smooth,traj_abrupt, ...
    state_smooth,state_abrupt,state_diagnostics, ...
    budget_curves,budget_points, ...
    rep_smooth,rep_abrupt,test_smooth,test_abrupt,jump_diag, ...
    alpha_sweep,reset_sweep,jump_line);

%% Save
results = struct();
results.cfg = cfg;
results.state_summary = state_summary;
results.state_diagnostics = state_diagnostics;
results.budget_curves = budget_curves;
results.budget_points = budget_points;
results.jump_diag = jump_diag;
results.alpha_sweep = alpha_sweep;
results.reset_sweep = reset_sweep;
results.runtime_summary = runtime_summary;

results.best_alpha = best_alpha;
results.best_reset_quantile = best_reset_quantile;
results.best_reset_threshold = best_reset_threshold;

results.rho_state_repro_smooth = rho_state_repro_smooth;
results.rho_state_repro_abrupt = rho_state_repro_abrupt;

save(fullfile(out_dir,'exp09c3b1_results.mat'), ...
    'results','-v7.3');

fprintf('\nSaved EXP009-C3-B1 outputs to:\n%s\n\n',out_dir);

end

%% ========================================================================
function T = build_trajectory(regime,cfg)
L = cfg.num_lines;

line_index = (1:L).';
x = linspace(0,1,L).';

weak_ratio = ...
    cfg.weak_ratio_center + ...
    cfg.weak_ratio_sin1*sin(2*pi*x - 0.30) + ...
    cfg.weak_ratio_sin2*sin(4*pi*x + 0.70);

signed_sep = ...
    cfg.sep_center + ...
    cfg.sep_sin1*sin(2*pi*x + 0.80) + ...
    cfg.sep_sin2*sin(6*pi*x - 0.40);

is_jump_start = false(L,1);

if string(regime)=="Abrupt"
    jump_line = max(2,min(L,round(cfg.jump_fraction*L)));
    idx = line_index>=jump_line;

    weak_ratio(idx) = ...
        weak_ratio(idx) + cfg.jump_weak_ratio_step;

    signed_sep(idx) = ...
        signed_sep(idx) + cfg.jump_sep_step;

    is_jump_start(jump_line) = true;
end

weak_ratio = min(max( ...
    weak_ratio,cfg.weak_ratio_min), ...
    cfg.weak_ratio_max);

signed_sep = min(max( ...
    signed_sep,cfg.sep_min), ...
    cfg.sep_max);

q_strong = cfg.q_weak + signed_sep;

snr_db = cfg.snr_db*ones(L,1);

T = table( ...
    line_index,x,weak_ratio,signed_sep,q_strong,snr_db,is_jump_start);

end

%% ========================================================================
function det = precompute_deterministic_chain(traj,t,cfg)
L = height(traj);
N = cfg.N;

Sstrong = complex(zeros(L,N));
Sweak = complex(zeros(L,N));
Estrong = complex(zeros(L,N));

for k = 1:L
    qs = traj.q_strong(k);
    rA = traj.weak_ratio(k);

    ss = synth_lfm( ...
        cfg.A_strong,qs, ...
        cfg.f_strong,cfg.phi_strong,t,cfg);

    sw = synth_lfm( ...
        cfg.A_strong*rA,cfg.q_weak, ...
        cfg.f_weak,cfg.phi_weak,t,cfg);

    k0 = get_strong_notch_bin(ss,qs,t,cfg);

    es = apply_fixed_notch_operator( ...
        ss,qs,k0,cfg.notch_halfwidth_bins,t,cfg);

    Sstrong(k,:) = ss(:).';
    Sweak(k,:) = sw(:).';
    Estrong(k,:) = es(:).';
end

det = struct();
det.Sstrong = Sstrong;
det.Sweak = Sweak;
det.Estrong = Estrong;

end

%% ========================================================================
function Tbank = run_signal_mc_bank( ...
    det,traj,num_mc,seed,D_search,q_search,t,cfg)

rng(seed,'twister');

L = height(traj);
N = cfg.N;
nRows = L*num_mc;

sequence_id = zeros(nRows,1);
line_index = zeros(nRows,1);

weak_ratio = nan(nRows,1);
signed_sep = nan(nRows,1);
q_strong = nan(nRows,1);
snr_db = nan(nRows,1);

cheap_q_hat = nan(nRows,1);
fallback_q_hat = nan(nRows,1);

cheap_prominence = nan(nRows,1);
cheap_entropy = nan(nRows,1);

cheap_success = false(nRows,1);
fallback_success = false(nRows,1);

beneficial = false(nRows,1);
harmful = false(nRows,1);

allocation_tiebreak = rand(nRows,1);

% Strong-referenced SNR convention used in B/C experiments.
s_ref = synth_lfm( ...
    cfg.A_strong,cfg.q_weak-0.05, ...
    cfg.f_strong,cfg.phi_strong,t,cfg);

Pstrong = mean(abs(s_ref).^2);
noise_var = Pstrong/(10^(cfg.snr_db/10));

row0 = 0;

for imc = 1:num_mc
    noise = sqrt(noise_var/2) * ...
        (randn(L,N)+1j*randn(L,N));

    Xcheap = det.Sweak + det.Estrong + noise;
    Xmix = det.Sstrong + det.Sweak + noise;

    [qhc,prom,ent] = ...
        search_q_features_batch( ...
        Xcheap,q_search,D_search, ...
        cfg.q_search_block_lines);

    Xrefit = refit_strong_batch( ...
        Xmix,traj.q_strong,t,cfg);

    [qhf,~,~] = ...
        search_q_features_batch( ...
        Xrefit,q_search,D_search, ...
        cfg.q_search_block_lines);

    sc = abs(qhc-cfg.q_weak) <= ...
        (cfg.tau_q+cfg.success_tol);

    sf = abs(qhf-cfg.q_weak) <= ...
        (cfg.tau_q+cfg.success_tol);

    idx = row0 + (1:L);

    sequence_id(idx) = imc;
    line_index(idx) = traj.line_index;

    weak_ratio(idx) = traj.weak_ratio;
    signed_sep(idx) = traj.signed_sep;
    q_strong(idx) = traj.q_strong;
    snr_db(idx) = traj.snr_db;

    cheap_q_hat(idx) = qhc;
    fallback_q_hat(idx) = qhf;

    cheap_prominence(idx) = prom;
    cheap_entropy(idx) = ent;

    cheap_success(idx) = sc;
    fallback_success(idx) = sf;

    beneficial(idx) = (~sc) & sf;
    harmful(idx) = sc & (~sf);

    row0 = row0 + L;
end

Tbank = table( ...
    sequence_id,line_index, ...
    weak_ratio,signed_sep,q_strong,snr_db, ...
    cheap_q_hat,fallback_q_hat, ...
    cheap_prominence,cheap_entropy, ...
    cheap_success,fallback_success,beneficial,harmful, ...
    allocation_tiebreak);

end

%% ========================================================================
function D = build_dechirp_dictionary(q_grid,t,cfg)
q_grid = q_grid(:);
t = t(:).';

mu = cfg.mu_scale*(q_grid-cfg.q_ref);

D = exp(-1j*pi*bsxfun(@times,mu,t.^2));

end

%% ========================================================================
function s = synth_lfm(A,q,f0,phi0,t,cfg)
t = t(:).';

mu = cfg.mu_scale*(q-cfg.q_ref);

s = A.*exp(1j*( ...
    pi*mu*t.^2 + ...
    2*pi*f0*t + ...
    phi0));

s = s(:).';

end

%% ========================================================================
function k0 = get_strong_notch_bin( ...
    s_strong,q_strong,t,cfg)

t = t(:).';
s_strong = s_strong(:).';

mu = cfg.mu_scale*(q_strong-cfg.q_ref);
dechirp = exp(-1j*pi*mu*t.^2);

Z = fft(s_strong.*dechirp);

[~,k0] = max(abs(Z).^2);

if ~isscalar(k0)
    error('get_strong_notch_bin must return one scalar bin index.');
end

end

%% ========================================================================
function r = apply_fixed_notch_operator( ...
    x,q_used,k_fixed,halfwidth_bins,t,cfg)

x = x(:).';
t = t(:).';

mu = cfg.mu_scale*(q_used-cfg.q_ref);

dechirp = exp(-1j*pi*mu*t.^2);
rechirp = conj(dechirp);

Z = fft(x.*dechirp);

mask = ones(1,numel(Z));

for dk = -halfwidth_bins:halfwidth_bins
    kk = mod((k_fixed-1)+dk,numel(Z))+1;
    mask(kk) = 0;
end

r = ifft(Z.*mask).*rechirp;
r = r(:).';

end

%% ========================================================================
function [q_hat,prominence,curve_entropy] = ...
    search_q_features_batch(X,q_grid,D,block_lines)

X = double_complex_guard(X,'X');

[L,N] = size(X);
[Q,ND] = size(D);

if ND~=N
    error(['search_q_features_batch dimension mismatch: ' ...
        'D has %d columns but X has %d samples.'],ND,N);
end

q_grid = q_grid(:);

if numel(q_grid)~=Q
    error('q_grid length does not match dechirp dictionary rows.');
end

q_hat = nan(L,1);
prominence = nan(L,1);
curve_entropy = nan(L,1);

D3 = reshape(D,[Q,N,1]);

for i1 = 1:block_lines:L
    i2 = min(L,i1+block_lines-1);
    idx = i1:i2;
    B = numel(idx);

    Xb = X(idx,:);

    % Explicit shape:
    %   D3: Q x N x 1
    %   X3: 1 x N x B
    X3 = reshape(Xb.',[1,N,B]);

    Y = fft(bsxfun(@times,D3,X3),[],2);

    M3 = max(abs(Y).^2,[],2);
    M = reshape(M3,[Q,B]);

    [peak,ii] = max(M,[],1);

    qhat_block = q_grid(ii(:));
    q_hat(idx) = qhat_block(:);

    floor_med = median(M,1);

    prominence(idx) = ...
        ((peak-floor_med)./max(peak,eps)).';

    denom = max(sum(M,1),eps);
    PP = bsxfun(@rdivide,M,denom);
    PP = max(PP,realmin);

    ent = -sum(PP.*log(PP),1)/log(Q);

    curve_entropy(idx) = ent.';
end

q_hat = q_hat(:);
prominence = prominence(:);
curve_entropy = curve_entropy(:);

end

%% ========================================================================
function R = refit_strong_batch(X,q_strong,t,cfg)

X = double_complex_guard(X,'X');

[L,N] = size(X);
t = t(:).';

q_strong = q_strong(:);

if numel(q_strong)~=L
    error(['refit_strong_batch: q_strong must have one value per ' ...
        'signal row.']);
end

mu = cfg.mu_scale*(q_strong-cfg.q_ref);

dechirp_phase = -1j*pi*bsxfun(@times,mu,t.^2);
D = exp(dechirp_phase);

Z = fft(X.*D,cfg.refit_nfft_factor*N,2);
P = abs(Z).^2;

[~,k0] = max(P,[],2);

nfft = size(Z,2);

lin0 = sub2ind([L,nfft],(1:L).',k0);
km = mod(k0-2,nfft)+1;
kp = mod(k0,nfft)+1;

linm = sub2ind([L,nfft],(1:L).',km);
linp = sub2ind([L,nfft],(1:L).',kp);

ym = P(linm);
y0 = P(lin0);
yp = P(linp);

den = ym - 2*y0 + yp;

delta = zeros(L,1);
valid = abs(den)>eps;
delta(valid) = 0.5*(ym(valid)-yp(valid))./den(valid);

delta = min(max(delta,-1),1);

bin0 = k0-1;
wrap = bin0>nfft/2;
bin0(wrap) = bin0(wrap)-nfft;

fhat = (bin0+delta)*(N/nfft);
fhat = fhat(:);

phase_q = bsxfun(@times,pi*mu,t.^2);
phase_f = bsxfun(@times,2*pi*fhat,t);

atom = exp(1j*(phase_q+phase_f));

den_a = sum(abs(atom).^2,2);
den_a = max(den_a,eps);

alpha = sum(conj(atom).*X,2)./den_a;

R = X - bsxfun(@times,alpha,atom);

if ~isequal(size(R),size(X))
    error('refit_strong_batch output dimension changed unexpectedly.');
end

end

%% ========================================================================
function X = double_complex_guard(X,label)
if ~ismatrix(X)
    error('%s must be a 2-D matrix.',label);
end

X = double(X);

if isempty(X)
    error('%s is empty.',label);
end
end

%% ========================================================================
function S = estimate_line_state(Ttrain,Ttest,cfg)

lines = unique(Ttrain.line_index).';
L = numel(lines);

if numel(unique(Ttest.line_index))~=L
    error('Train/test banks do not contain the same number of lines.');
end

line_index = lines(:);

weak_ratio = nan(L,1);
signed_sep = nan(L,1);
q_strong = nan(L,1);

train_cheap_recall = nan(L,1);
train_fallback_recall = nan(L,1);
train_beneficial_rate = nan(L,1);
train_harmful_rate = nan(L,1);
train_utility_raw = nan(L,1);

test_cheap_recall = nan(L,1);
test_fallback_recall = nan(L,1);
test_beneficial_rate = nan(L,1);
test_harmful_rate = nan(L,1);
test_utility_raw = nan(L,1);

for ik = 1:L
    k = line_index(ik);

    mtr = Ttrain.line_index==k;
    mte = Ttest.line_index==k;

    weak_ratio(ik) = scalar_unique( ...
        Ttrain.weak_ratio(mtr),sprintf('weak_ratio line %d',k));

    signed_sep(ik) = scalar_unique( ...
        Ttrain.signed_sep(mtr),sprintf('signed_sep line %d',k));

    q_strong(ik) = scalar_unique( ...
        Ttrain.q_strong(mtr),sprintf('q_strong line %d',k));

    train_cheap_recall(ik) = mean(Ttrain.cheap_success(mtr));
    train_fallback_recall(ik) = mean(Ttrain.fallback_success(mtr));
    train_beneficial_rate(ik) = mean(Ttrain.beneficial(mtr));
    train_harmful_rate(ik) = mean(Ttrain.harmful(mtr));

    train_utility_raw(ik) = ...
        train_beneficial_rate(ik)-train_harmful_rate(ik);

    test_cheap_recall(ik) = mean(Ttest.cheap_success(mte));
    test_fallback_recall(ik) = mean(Ttest.fallback_success(mte));
    test_beneficial_rate(ik) = mean(Ttest.beneficial(mte));
    test_harmful_rate(ik) = mean(Ttest.harmful(mte));

    test_utility_raw(ik) = ...
        test_beneficial_rate(ik)-test_harmful_rate(ik);
end

w = max(1,round(cfg.state_utility_smooth_window));

train_utility_smooth = ...
    moving_average_shrink(train_utility_raw,w);

test_utility_smooth = ...
    moving_average_shrink(test_utility_raw,w);

S = table( ...
    line_index,weak_ratio,signed_sep,q_strong, ...
    train_cheap_recall,train_fallback_recall, ...
    train_beneficial_rate,train_harmful_rate, ...
    train_utility_raw,train_utility_smooth, ...
    test_cheap_recall,test_fallback_recall, ...
    test_beneficial_rate,test_harmful_rate, ...
    test_utility_raw,test_utility_smooth);

end

%% ========================================================================
function y = moving_average_shrink(x,w)
x = double(x(:));
w = max(1,round(w));

N = numel(x);
y = nan(N,1);

left = floor((w-1)/2);
right = w-1-left;

for i = 1:N
    i1 = max(1,i-left);
    i2 = min(N,i+right);

    vals = x(i1:i2);
    y(i) = mean(vals,'omitnan');
end
end

%% ========================================================================
function [Ttrain,Ttest] = attach_state_target(Ttrain,Ttest,S)

u = double(S.train_utility_smooth(:));

umin = min(u);
umax = max(u);

if ~isfinite(umin) || ~isfinite(umax)
    error('Non-finite TRAIN state utility.');
end

if abs(umax-umin)<eps
    unorm = 0.5*ones(size(u));
else
    unorm = (u-umin)/(umax-umin);
end

Ttrain.state_utility_raw = nan(height(Ttrain),1);
Ttrain.state_utility_smooth = nan(height(Ttrain),1);
Ttrain.state_utility_norm = nan(height(Ttrain),1);
Ttrain.state_prior_score = nan(height(Ttrain),1);

Ttest.state_utility_raw = nan(height(Ttest),1);
Ttest.state_utility_smooth = nan(height(Ttest),1);
Ttest.state_utility_norm = nan(height(Ttest),1);
Ttest.state_prior_score = nan(height(Ttest),1);

for i = 1:height(S)
    k = S.line_index(i);

    mtr = Ttrain.line_index==k;
    mte = Ttest.line_index==k;

    Ttrain.state_utility_raw(mtr) = S.train_utility_raw(i);
    Ttrain.state_utility_smooth(mtr) = S.train_utility_smooth(i);
    Ttrain.state_utility_norm(mtr) = unorm(i);
    Ttrain.state_prior_score(mtr) = unorm(i);

    % TEST uses only TRAIN-estimated state utility/prior.
    Ttest.state_utility_raw(mte) = S.train_utility_raw(i);
    Ttest.state_utility_smooth(mte) = S.train_utility_smooth(i);
    Ttest.state_utility_norm(mte) = unorm(i);
    Ttest.state_prior_score(mte) = unorm(i);
end

end

%% ========================================================================
function calib = build_instantaneous_calibration(Ttrain)

prom = double(Ttrain.cheap_prominence(:));
ent = double(Ttrain.cheap_entropy(:));

prom = prom(isfinite(prom));
ent = ent(isfinite(ent));

if isempty(prom) || isempty(ent)
    error('Instantaneous feature calibration received no finite values.');
end

calib.prom_sorted = sort(prom);
calib.ent_sorted = sort(ent);

end

%% ========================================================================
function T = add_instant_score(T,calib)

N = height(T);
score = nan(N,1);

for i = 1:N
    p = double(T.cheap_prominence(i));
    e = double(T.cheap_entropy(i));

    Fp = empirical_cdf_value(calib.prom_sorted,p);
    Fe = empirical_cdf_value(calib.ent_sorted,e);

    risk_prom = 1-Fp;
    risk_ent = Fe;

    score(i) = 0.5*(risk_prom+risk_ent);
end

T.instant_score = min(max(score,0),1);

end

%% ========================================================================
function F = empirical_cdf_value(sorted_x,x)

sorted_x = double(sorted_x(:));

if isempty(sorted_x)
    F = 0.5;
    return;
end

if ~isfinite(x)
    F = 0.5;
    return;
end

N = numel(sorted_x);

nLess = sum(sorted_x<x);
nEq = sum(sorted_x==x);

F = (nLess+0.5*nEq)/N;
F = min(max(F,0),1);

if ~isscalar(F)
    error('empirical_cdf_value must return a scalar.');
end

end

%% ========================================================================
function Tout = apply_history(Tin,alpha,reset_threshold)

if alpha<=0 || alpha>1
    error('EMA alpha must lie in (0,1].');
end

Tout = Tin;

N = height(Tout);

ema_score = nan(N,1);
reset_score = nan(N,1);
innovation = nan(N,1);
reset_event = false(N,1);

seqs = unique(Tout.sequence_id).';

for is = 1:numel(seqs)
    idx = find(Tout.sequence_id==seqs(is));

    [~,ord] = sort(Tout.line_index(idx));
    idx = idx(ord);

    x = double(Tout.instant_score(idx));
    x = x(:);

    e = nan(size(x));
    r = nan(size(x));
    inn = nan(size(x));
    re = false(size(x));

    e(1) = x(1);
    r(1) = x(1);
    inn(1) = 0;

    for k = 2:numel(x)
        inn(k) = x(k)-e(k-1);

        e(k) = ...
            alpha*x(k) + ...
            (1-alpha)*e(k-1);

        if isfinite(reset_threshold)
            reset_innovation = x(k)-r(k-1);

            if abs(reset_innovation)>reset_threshold
                r(k) = x(k);
                re(k) = true;
            else
                r(k) = ...
                    alpha*x(k) + ...
                    (1-alpha)*r(k-1);
            end
        else
            r(k) = e(k);
        end
    end

    ema_score(idx) = e;
    reset_score(idx) = r;
    innovation(idx) = inn;
    reset_event(idx) = re;
end

Tout.ema_score = ema_score;
Tout.reset_score = reset_score;
Tout.innovation = innovation;
Tout.reset_event = reset_event;

end

%% ========================================================================
function recall = policy_recall_at_budget(T,score_var,budget)

score = score_with_tiebreak(T,score_var);

if budget<=0
    trigger = false(size(score));
elseif budget>=1
    trigger = true(size(score));
else
    thr = empirical_quantile(score,1-budget);
    trigger = score>=thr;
end

out = logical(T.cheap_success);
fb = logical(T.fallback_success);

out(trigger) = fb(trigger);

recall = mean(out);

end

%% ========================================================================
function score = score_with_tiebreak(T,score_var)

score = double(T.(score_var));
score = score(:);

if ismember('allocation_tiebreak',T.Properties.VariableNames)
    tb = double(T.allocation_tiebreak(:));
    score = score + 1e-9*(tb-0.5);
end

end

%% ========================================================================
function err = post_jump_tracking_error(T,cfg,H)

jump_line = max(2,min(cfg.num_lines,round(cfg.jump_fraction*cfg.num_lines)));

pol = 'reset_score';

if ~ismember(pol,T.Properties.VariableNames)
    error('post_jump_tracking_error requires reset_score.');
end

score = double(T.(pol));
target = double(T.state_utility_norm);

mask = T.line_index>=jump_line & ...
       T.line_index<=min(cfg.num_lines,jump_line+H-1);

if ~any(mask)
    err = NaN;
else
    err = mean(abs(score(mask)-target(mask)),'omitnan');
end

end

%% ========================================================================
function idx = select_reset_candidate(recall_vec,error_vec)

recall_vec = double(recall_vec(:));
error_vec = double(error_vec(:));

best = max(recall_vec);

tol = max(1e-12,1e-9*max(1,abs(best)));

cand = find(abs(recall_vec-best)<=tol);

if isempty(cand)
    [~,idx] = max(recall_vec);
    return;
end

if numel(cand)==1
    idx = cand;
    return;
end

[~,jj] = min(error_vec(cand));
idx = cand(jj);

end

%% ========================================================================
function D = state_observability_diagnostics( ...
    Ttrain,Ttest,regime) %#ok<INUSD>

score_vars = { ...
    'instant_score', ...
    'ema_score', ...
    'reset_score', ...
    'state_prior_score'};

labels = { ...
    'InstantPE', ...
    'EMA', ...
    'EMAReset', ...
    'PhysicalStatePrior'};

P = numel(score_vars);

regime_col = repmat(string(regime),P,1);
policy = strings(P,1);

trial_level_state_rho = nan(P,1);
line_mean_state_rho = nan(P,1);
beneficial_auc = nan(P,1);

for ip = 1:P
    policy(ip) = string(labels{ip});

    s = double(Ttest.(score_vars{ip}));
    target = double(Ttest.state_utility_norm);

    trial_level_state_rho(ip) = ...
        spearman_manual(s,target);

    lines = unique(Ttest.line_index).';
    mean_score = nan(numel(lines),1);
    state_line = nan(numel(lines),1);

    for ik = 1:numel(lines)
        k = lines(ik);
        mm = Ttest.line_index==k;

        mean_score(ik) = mean(s(mm),'omitnan');
        state_line(ik) = scalar_unique( ...
            target(mm),sprintf('state target line %d',k));
    end

    line_mean_state_rho(ip) = ...
        spearman_manual(mean_score,state_line);

    beneficial_auc(ip) = ...
        binary_auc(Ttest.beneficial,s);
end

D = table( ...
    cellstr(regime_col),cellstr(policy), ...
    trial_level_state_rho,line_mean_state_rho,beneficial_auc, ...
    'VariableNames',{ ...
    'regime','policy','trial_level_state_rho', ...
    'line_mean_state_rho','beneficial_auc'});

end

%% ========================================================================
function C = evaluate_score_policy_curve( ...
    Ttrain,Ttest,score_var,budgets)

train_score = score_with_tiebreak(Ttrain,score_var);
test_score = score_with_tiebreak(Ttest,score_var);

budgets = budgets(:);
nB = numel(budgets);

target_budget = budgets;
actual_trigger_rate = nan(nB,1);
policy_recall = nan(nB,1);
beneficial_capture = nan(nB,1);
benefit_precision = nan(nB,1);
harmful_fraction_among_triggers = nan(nB,1);
normalized_q_search_budget = nan(nB,1);

cheap = logical(Ttest.cheap_success);
fb = logical(Ttest.fallback_success);
beneficial = logical(Ttest.beneficial);
harmful = logical(Ttest.harmful);

nBeneficial = sum(beneficial);

for ib = 1:nB
    b = budgets(ib);

    if b<=0
        trigger = false(size(test_score));
    elseif b>=1
        trigger = true(size(test_score));
    else
        thr = empirical_quantile(train_score,1-b);
        trigger = test_score>=thr;
    end

    actual_trigger_rate(ib) = mean(trigger);

    out = cheap;
    out(trigger) = fb(trigger);

    policy_recall(ib) = mean(out);

    if nBeneficial>0
        beneficial_capture(ib) = ...
            sum(trigger & beneficial)/nBeneficial;
    end

    nTrig = sum(trigger);

    if nTrig>0
        benefit_precision(ib) = ...
            sum(trigger & beneficial)/nTrig;

        harmful_fraction_among_triggers(ib) = ...
            sum(trigger & harmful)/nTrig;
    end

    normalized_q_search_budget(ib) = ...
        1+actual_trigger_rate(ib);
end

C = table( ...
    target_budget,actual_trigger_rate,policy_recall, ...
    beneficial_capture,benefit_precision, ...
    harmful_fraction_among_triggers, ...
    normalized_q_search_budget);

end

%% ========================================================================
function C = trial_oracle_curve(Ttest,budgets)

budgets = budgets(:);

cheap_recall = mean(Ttest.cheap_success);
benefit_rate = mean(Ttest.beneficial);

nB = numel(budgets);

target_budget = budgets;
actual_trigger_rate = nan(nB,1);
policy_recall = nan(nB,1);
beneficial_capture = nan(nB,1);
benefit_precision = nan(nB,1);
harmful_fraction_among_triggers = zeros(nB,1);
normalized_q_search_budget = nan(nB,1);

for ib = 1:nB
    used = min(max(budgets(ib),0),benefit_rate);

    actual_trigger_rate(ib) = used;
    policy_recall(ib) = cheap_recall+used;

    if benefit_rate>0
        beneficial_capture(ib) = min(1,used/benefit_rate);
    end

    if used>0
        benefit_precision(ib) = 1;
    end

    normalized_q_search_budget(ib) = 1+used;
end

C = table( ...
    target_budget,actual_trigger_rate,policy_recall, ...
    beneficial_capture,benefit_precision, ...
    harmful_fraction_among_triggers, ...
    normalized_q_search_budget);

end

%% ========================================================================
function C = random_expected_curve(Ttest,budgets)

budgets = budgets(:);

cheap_recall = mean(Ttest.cheap_success);
benefit_rate = mean(Ttest.beneficial);
harm_rate = mean(Ttest.harmful);

target_budget = budgets;
actual_trigger_rate = budgets;

policy_recall = ...
    cheap_recall + ...
    budgets*(benefit_rate-harm_rate);

beneficial_capture = budgets;

benefit_precision = ...
    repmat(benefit_rate,numel(budgets),1);

harmful_fraction_among_triggers = ...
    repmat(harm_rate,numel(budgets),1);

benefit_precision(budgets==0) = NaN;
harmful_fraction_among_triggers(budgets==0) = NaN;

normalized_q_search_budget = 1+budgets;

C = table( ...
    target_budget,actual_trigger_rate,policy_recall, ...
    beneficial_capture,benefit_precision, ...
    harmful_fraction_among_triggers, ...
    normalized_q_search_budget);

end

%% ========================================================================
function D = jump_diagnostics(T,cfg,H)

score_vars = {'instant_score','ema_score','reset_score'};
labels = {'InstantPE','EMA','EMAReset'};

P = numel(score_vars);

policy = cell(P,1);
mean_post_jump_state_abs_error = nan(P,1);
mean_global_state_abs_error = nan(P,1);
mean_score_change_at_jump = nan(P,1);
reset_rate_near_jump = nan(P,1);

jump_line = max(2,min(cfg.num_lines,round(cfg.jump_fraction*cfg.num_lines)));

for ip = 1:P
    policy{ip} = labels{ip};

    score = double(T.(score_vars{ip}));
    score = score(:);

    target = double(T.state_utility_norm);
    target = target(:);

    mask_post = ...
        T.line_index>=jump_line & ...
        T.line_index<=min(cfg.num_lines,jump_line+H-1);

    mean_post_jump_state_abs_error(ip) = ...
        mean(abs(score(mask_post)-target(mask_post)),'omitnan');

    mean_global_state_abs_error(ip) = ...
        mean(abs(score-target),'omitnan');

    seqs = unique(T.sequence_id).';
    jump_change = nan(numel(seqs),1);

    for is = 1:numel(seqs)
        s = seqs(is);

        i0 = find( ...
            T.sequence_id==s & ...
            T.line_index==jump_line,1,'first');

        im = find( ...
            T.sequence_id==s & ...
            T.line_index==jump_line-1,1,'first');

        if ~isempty(i0) && ~isempty(im)
            jump_change(is) = abs(score(i0)-score(im));
        end
    end

    mean_score_change_at_jump(ip) = ...
        mean(jump_change,'omitnan');

    if strcmp(score_vars{ip},'reset_score') && ...
            ismember('reset_event',T.Properties.VariableNames)

        mask_reset = ...
            T.line_index>=max(1,jump_line-1) & ...
            T.line_index<=min(cfg.num_lines,jump_line+H-1);

        reset_rate_near_jump(ip) = ...
            mean(T.reset_event(mask_reset));
    end
end

D = table( ...
    policy,mean_post_jump_state_abs_error, ...
    mean_global_state_abs_error, ...
    mean_score_change_at_jump, ...
    reset_rate_near_jump);

end

%% ========================================================================
function auc = binary_auc(y,score)

y = logical(y(:));
score = double(score(:));

valid = isfinite(score);
y = y(valid);
score = score(valid);

nPos = sum(y);
nNeg = sum(~y);

if nPos==0 || nNeg==0
    auc = NaN;
    return;
end

r = average_ranks(score);
sumPos = sum(r(y));

auc = ...
    (sumPos - nPos*(nPos+1)/2) / ...
    (nPos*nNeg);

end

%% ========================================================================
function rho = spearman_manual(x,y)

x = double(x(:));
y = double(y(:));

valid = isfinite(x) & isfinite(y);

x = x(valid);
y = y(valid);

if numel(x)<3
    rho = NaN;
    return;
end

rx = average_ranks(x);
ry = average_ranks(y);

C = corrcoef(rx,ry);

if numel(C)<4
    rho = NaN;
else
    rho = C(1,2);
end

end

%% ========================================================================
function r = average_ranks(x)

x = double(x(:));

[xs,ord] = sort(x);
rs = nan(size(xs));

i = 1;

while i<=numel(xs)
    j = i;

    while j<numel(xs) && xs(j+1)==xs(i)
        j = j+1;
    end

    rs(i:j) = (i+j)/2;
    i = j+1;
end

r = nan(size(x));
r(ord) = rs;

end

%% ========================================================================
function q = empirical_quantile(x,p)

x = double(x(:));
x = x(isfinite(x));

if isempty(x)
    q = NaN;
    return;
end

x = sort(x);

p = min(max(double(p),0),1);

if numel(x)==1
    q = x(1);
    return;
end

pos = 1+p*(numel(x)-1);

lo = floor(pos);
hi = ceil(pos);

if lo==hi
    q = x(lo);
else
    w = pos-lo;
    q = (1-w)*x(lo)+w*x(hi);
end

if ~isscalar(q)
    error('empirical_quantile must return a scalar.');
end

end

%% ========================================================================
function v = scalar_unique(x,label)

x = double(x(:));
x = x(isfinite(x));

if isempty(x)
    error('No finite values for %s.',label);
end

v = x(1);

if any(abs(x-v)>1e-12)
    error('%s is not constant.',label);
end

end

%% ========================================================================
function [line_index,mean_score,target] = ...
    line_mean_score(T,score_var)

lines = unique(T.line_index).';

line_index = lines(:);
mean_score = nan(numel(lines),1);
target = nan(numel(lines),1);

score = double(T.(score_var));

for i = 1:numel(lines)
    k = lines(i);
    mm = T.line_index==k;

    mean_score(i) = mean(score(mm),'omitnan');

    target(i) = scalar_unique( ...
        T.state_utility_norm(mm), ...
        sprintf('state target line %d',k));
end

end

%% ========================================================================
function make_figures( ...
    out_dir,cfg,traj_smooth,traj_abrupt, ...
    state_smooth,state_abrupt,state_diag, ...
    budget_curves,budget_points, ...
    rep_smooth,rep_abrupt,test_smooth,test_abrupt,jump_diag, ...
    alpha_sweep,reset_sweep,jump_line)

%% Fig 1: train/test state reproducibility
fig = figure('Visible',cfg.figure_visible);
hold on;

scatter( ...
    state_smooth.train_utility_smooth, ...
    state_smooth.test_utility_smooth, ...
    35,'filled');

scatter( ...
    state_abrupt.train_utility_smooth, ...
    state_abrupt.test_utility_smooth, ...
    35,'filled');

vals = [ ...
    state_smooth.train_utility_smooth; ...
    state_smooth.test_utility_smooth; ...
    state_abrupt.train_utility_smooth; ...
    state_abrupt.test_utility_smooth];

mn = min(vals);
mx = max(vals);

plot([mn mx],[mn mx],'--','LineWidth',1.0);

xlabel('TRAIN line utility');
ylabel('TEST line utility');

title('C3-B1 Signal-Generated State Reproducibility');

legend('Smooth','Abrupt','y=x','Location','best');
grid on;

exportgraphics(fig, ...
    fullfile(out_dir,'fig01_state_reproducibility.png'), ...
    'Resolution',180);

close(fig);

%% Fig 2: smooth physical state trajectory
fig = figure('Visible',cfg.figure_visible);

yyaxis left;
plot( ...
    traj_smooth.line_index, ...
    traj_smooth.weak_ratio, ...
    'LineWidth',1.4);
ylabel('A_w / A_s');

yyaxis right;
plot( ...
    traj_smooth.line_index, ...
    traj_smooth.signed_sep, ...
    'LineWidth',1.4);
ylabel('q_s - q_w');

xlabel('Azimuth-line index');
title('C3-B1 Smooth Physical Parameter Trajectory');
grid on;

exportgraphics(fig, ...
    fullfile(out_dir,'fig02_smooth_physical_trajectory.png'), ...
    'Resolution',180);

close(fig);

%% Fig 3: representative smooth signal-level tracking
% The single representative TEST realization intentionally preserves the
% line-to-line observation noise, while the state target is estimated only
% from the independent TRAIN ensemble.
fig = figure('Visible',cfg.figure_visible);

plot( ...
    rep_smooth.line_index, ...
    rep_smooth.state_utility_norm, ...
    'LineWidth',1.8);
hold on;

plot( ...
    rep_smooth.line_index, ...
    rep_smooth.instant_score, ...
    'LineWidth',1.0);

plot( ...
    rep_smooth.line_index, ...
    rep_smooth.ema_score, ...
    'LineWidth',1.4);

plot( ...
    rep_smooth.line_index, ...
    rep_smooth.reset_score, ...
    'LineWidth',1.2);

xlabel('Azimuth-line index');
ylabel('Normalized risk / score');

title('C3-B1 Representative Smooth Signal-Level Tracking');

legend('TRAIN physical-state prior','InstantPE','EMA','EMAReset', ...
    'Location','best');

grid on;

exportgraphics(fig, ...
    fullfile(out_dir,'fig03_representative_smooth_tracking.png'), ...
    'Resolution',180);

close(fig);

%% Fig 4: abrupt state tracking
fig = figure('Visible',cfg.figure_visible);

plot( ...
    rep_abrupt.line_index, ...
    rep_abrupt.state_utility_norm, ...
    'LineWidth',1.8);
hold on;

plot( ...
    rep_abrupt.line_index, ...
    rep_abrupt.instant_score, ...
    'LineWidth',1.0);

plot( ...
    rep_abrupt.line_index, ...
    rep_abrupt.ema_score, ...
    'LineWidth',1.4);

plot( ...
    rep_abrupt.line_index, ...
    rep_abrupt.reset_score, ...
    'LineWidth',1.2);

xline(jump_line,':','Physical jump');

xlabel('Azimuth-line index');
ylabel('Normalized risk / score');

title('C3-B1 Representative Abrupt Signal-Level Tracking');

legend('TRAIN physical-state prior','InstantPE','EMA','EMAReset', ...
    'Location','best');

grid on;

exportgraphics(fig, ...
    fullfile(out_dir,'fig04_representative_abrupt_tracking.png'), ...
    'Resolution',180);

close(fig);

%% Fig 5: state observability
regimes = {'Smooth','Abrupt'};
policies = { ...
    'InstantPE','EMA','EMAReset','PhysicalStatePrior'};

Y = nan(numel(policies),numel(regimes));

for ip = 1:numel(policies)
    for ir = 1:numel(regimes)
        mm = strcmp(state_diag.policy,policies{ip}) & ...
             strcmp(state_diag.regime,regimes{ir});

        if any(mm)
            Y(ip,ir) = state_diag.trial_level_state_rho(mm);
        end
    end
end

fig = figure('Visible',cfg.figure_visible);
bar(Y);

ylim([-0.1 1]);

xticks(1:numel(policies));
xticklabels(policies);
xtickangle(20);

ylabel('Spearman with signal-generated state');
title('C3-B1 History and Physical-State Observability');

legend(regimes,'Location','best');
grid on;

exportgraphics(fig, ...
    fullfile(out_dir,'fig05_state_observability.png'), ...
    'Resolution',180);

close(fig);

%% Shared quality-cost policies
plot_policies = [ ...
    "InstantPE","EMA","EMAReset", ...
    "PhysicalStatePrior","TrialOracle","RandomExpected"];

%% Fig 6: smooth quality-cost
fig = figure('Visible',cfg.figure_visible);
hold on;

for ip = 1:numel(plot_policies)
    Cp = budget_curves( ...
        budget_curves.regime=="Smooth" & ...
        budget_curves.policy==plot_policies(ip),:);

    plot( ...
        Cp.normalized_q_search_budget, ...
        Cp.policy_recall, ...
        'LineWidth',1.35);
end

xlabel('Normalized q-search budget');
ylabel('Weak recovery rate');

title('C3-B1 Smooth: Quality-Cost Pareto');
legend(plot_policies,'Location','best');
grid on;

exportgraphics(fig, ...
    fullfile(out_dir,'fig06_smooth_quality_cost.png'), ...
    'Resolution',180);

close(fig);

%% Fig 7: abrupt quality-cost
fig = figure('Visible',cfg.figure_visible);
hold on;

for ip = 1:numel(plot_policies)
    Cp = budget_curves( ...
        budget_curves.regime=="Abrupt" & ...
        budget_curves.policy==plot_policies(ip),:);

    plot( ...
        Cp.normalized_q_search_budget, ...
        Cp.policy_recall, ...
        'LineWidth',1.35);
end

xlabel('Normalized q-search budget');
ylabel('Weak recovery rate');

title('C3-B1 Abrupt: Quality-Cost Pareto');
legend(plot_policies,'Location','best');
grid on;

exportgraphics(fig, ...
    fullfile(out_dir,'fig07_abrupt_quality_cost.png'), ...
    'Resolution',180);

close(fig);

%% Fig 8: 25% policy comparison
rows25 = budget_points( ...
    abs(budget_points.target_budget-0.25)<1e-12,:);

primary = ismember( ...
    string(rows25.policy), ...
    ["InstantPE","EMA","EMAReset","PhysicalStatePrior"]);

R = rows25(primary,:);

pol_order = [ ...
    "InstantPE","EMA","EMAReset","PhysicalStatePrior"];

Y = nan(numel(pol_order),2);

for ip = 1:numel(pol_order)
    mmS = strcmp(R.regime,'Smooth') & ...
          strcmp(R.policy,char(pol_order(ip)));

    mmA = strcmp(R.regime,'Abrupt') & ...
          strcmp(R.policy,char(pol_order(ip)));

    if any(mmS)
        Y(ip,1) = R.policy_recall(mmS);
    end

    if any(mmA)
        Y(ip,2) = R.policy_recall(mmA);
    end
end

fig = figure('Visible',cfg.figure_visible);
bar(Y);

ylim([0 1]);

xticks(1:numel(pol_order));
xticklabels(pol_order);
xtickangle(20);

ylabel('Weak recovery rate');
title('C3-B1 Policy Comparison at 25% Budget');

legend('Smooth','Abrupt','Location','best');
grid on;

exportgraphics(fig, ...
    fullfile(out_dir,'fig08_policy_comparison_25pct.png'), ...
    'Resolution',180);

close(fig);

%% Fig 9: jump tracking error
fig = figure('Visible',cfg.figure_visible);

bar(jump_diag.mean_post_jump_state_abs_error);

xticks(1:height(jump_diag));
xticklabels(jump_diag.policy);

ylabel('Mean |score - state|, first 5 lines after jump');
title('C3-B1 Abrupt Physical-Transition Tracking Error');
grid on;

exportgraphics(fig, ...
    fullfile(out_dir,'fig09_jump_tracking_error.png'), ...
    'Resolution',180);

close(fig);

%% Fig 10: alpha tuning
fig = figure('Visible',cfg.figure_visible);

plot( ...
    alpha_sweep.alpha, ...
    alpha_sweep.train_recall_at_tune_budget, ...
    '-o','LineWidth',1.3);

xlabel('EMA \alpha');
ylabel('Smooth TRAIN recovery at 25% budget');
title('C3-B1 EMA Alpha Tuning');
grid on;

exportgraphics(fig, ...
    fullfile(out_dir,'fig10_alpha_tuning.png'), ...
    'Resolution',180);

close(fig);

%% Fig 11: reset tuning
fig = figure('Visible',cfg.figure_visible);

plot( ...
    reset_sweep.reset_quantile, ...
    reset_sweep.train_recall_at_tune_budget, ...
    '-o','LineWidth',1.3);

xlabel('Innovation reset quantile');
ylabel('Abrupt TRAIN recovery at 25% budget');
title('C3-B1 Reset Tuning');
grid on;

exportgraphics(fig, ...
    fullfile(out_dir,'fig11_reset_tuning.png'), ...
    'Resolution',180);

close(fig);

%% Fig 12: train/test utility profiles
fig = figure('Visible',cfg.figure_visible);
hold on;

plot( ...
    state_smooth.line_index, ...
    state_smooth.train_utility_smooth, ...
    'LineWidth',1.4);

plot( ...
    state_smooth.line_index, ...
    state_smooth.test_utility_smooth, ...
    '--','LineWidth',1.2);

plot( ...
    state_abrupt.line_index, ...
    state_abrupt.train_utility_smooth, ...
    'LineWidth',1.4);

plot( ...
    state_abrupt.line_index, ...
    state_abrupt.test_utility_smooth, ...
    '--','LineWidth',1.2);

xline(jump_line,':');

xlabel('Azimuth-line index');
ylabel('Fallback utility P_B - P_H');

title('C3-B1 Signal-Generated Continuous Utility Profiles');

legend( ...
    'Smooth TRAIN','Smooth TEST', ...
    'Abrupt TRAIN','Abrupt TEST', ...
    'Location','best');

grid on;

exportgraphics(fig, ...
    fullfile(out_dir,'fig12_train_test_utility_profiles.png'), ...
    'Resolution',180);

close(fig);

%% Fig 13: smooth TEST ensemble-mean tracking
[li_s,mean_inst_s,target_s] = ...
    line_mean_score(test_smooth,'instant_score');

[~,mean_ema_s,~] = ...
    line_mean_score(test_smooth,'ema_score');

[~,mean_reset_s,~] = ...
    line_mean_score(test_smooth,'reset_score');

fig = figure('Visible',cfg.figure_visible);

plot(li_s,target_s,'LineWidth',1.8);
hold on;
plot(li_s,mean_inst_s,'LineWidth',1.0);
plot(li_s,mean_ema_s,'LineWidth',1.4);
plot(li_s,mean_reset_s,'LineWidth',1.2);

xlabel('Azimuth-line index');
ylabel('Ensemble-mean normalized risk');

title('C3-B1 Smooth TEST Ensemble-Mean State Tracking');

legend('TRAIN state target','InstantPE mean','EMA mean','EMAReset mean', ...
    'Location','best');

grid on;

exportgraphics(fig, ...
    fullfile(out_dir,'fig13_smooth_ensemble_mean_tracking.png'), ...
    'Resolution',180);

close(fig);

%% Fig 14: abrupt TEST ensemble-mean tracking
[li_a,mean_inst_a,target_a] = ...
    line_mean_score(test_abrupt,'instant_score');

[~,mean_ema_a,~] = ...
    line_mean_score(test_abrupt,'ema_score');

[~,mean_reset_a,~] = ...
    line_mean_score(test_abrupt,'reset_score');

fig = figure('Visible',cfg.figure_visible);

plot(li_a,target_a,'LineWidth',1.8);
hold on;
plot(li_a,mean_inst_a,'LineWidth',1.0);
plot(li_a,mean_ema_a,'LineWidth',1.4);
plot(li_a,mean_reset_a,'LineWidth',1.2);

xline(jump_line,':','Physical jump');

xlabel('Azimuth-line index');
ylabel('Ensemble-mean normalized risk');

title('C3-B1 Abrupt TEST Ensemble-Mean State Tracking');

legend('TRAIN state target','InstantPE mean','EMA mean','EMAReset mean', ...
    'Location','best');

grid on;

exportgraphics(fig, ...
    fullfile(out_dir,'fig14_abrupt_ensemble_mean_tracking.png'), ...
    'Resolution',180);

close(fig);

end

