%% exp03_entropy_search.m
% EXP03: Minimum-entropy advance-and-retreat search
%
% Reproduction target:
%   Wang et al., "Fast and Accurate Refocusing for Moving Ships in SAR
%   Imagery Based on FrFT", Remote Sensing, 2023.
%
% Purpose
% -------------------------------------------------------------------------
% Compare:
%
%   Method 1: Traditional two-stage FrFT peak traversal
%             - coarse traversal over the whole order interval
%             - local fine traversal around the coarse peak
%
%   Method 2: Proposed minimum-entropy advance-and-retreat search
%             - move only in the entropy-decreasing direction
%             - coarse search first
%             - local fine search second
%
% Motion cases:
%   A. Azimuth velocity    va = 20 m/s
%   B. Range acceleration ar = 10 m/s^2
%
% Both were verified in EXP02 to produce second-order residual phase / LFM.
%
% Required functions:
%   frft_direct.m
%   signal_entropy.m
%   simulate_motion_case.m
%   minimum_entropy_search.m
%   two_stage_peak_search.m
%
% IMPORTANT
% -------------------------------------------------------------------------
% Absolute runtime is NOT directly comparable with the paper because
% frft_direct.m is an O(N^2) transparent implementation used for mechanism
% verification.
%
% The meaningful quantities in EXP03 are:
%
%   1) optimal-order accuracy;
%   2) number of FrFT evaluations;
%   3) relative runtime reduction;
%   4) final focusing quality.
%
% -------------------------------------------------------------------------

clear;
clc;
close all;

%% 0. Resolve project paths
script_fullpath = mfilename('fullpath');

exp_dir = fileparts(script_fullpath);
code_dir = fileparts(exp_dir);
paper_dir = fileparts(code_dir);

functions_dir = fullfile(code_dir, 'functions');
results_dir = fullfile( ...
    paper_dir, ...
    'results', ...
    'exp03_entropy_search');

if ~exist(functions_dir, 'dir')
    error('Functions directory not found: %s', functions_dir);
end

if ~exist(results_dir, 'dir')
    mkdir(results_dir);
end

addpath(functions_dir);

required_functions = { ...
    'frft_direct', ...
    'signal_entropy', ...
    'simulate_motion_case', ...
    'minimum_entropy_search', ...
    'two_stage_peak_search'};

for ii = 1:numel(required_functions)

    if exist(required_functions{ii}, 'file') ~= 2
        error( ...
            'Required function not found: %s.m', ...
            required_functions{ii});
    end

end

fprintf('============================================================\n');
fprintf('EXP03: Minimum-entropy FrFT order search\n');
fprintf('Experiment folder : %s\n', exp_dir);
fprintf('Functions folder  : %s\n', functions_dir);
fprintf('Results folder    : %s\n', results_dir);
fprintf('============================================================\n\n');

%% 1. SAR parameters
params.c = 299792458;

params.fc = 3e9;
params.lambda = params.c / params.fc;

params.PRF = 188;
params.B = 150e6;

params.H = 3000;
params.Lant = 2;
params.vsar = 150;
params.Tp = 1.5e-6;

% Same controlled assumption as EXP02.
% The paper defines x0 but does not provide its numerical value
% in the simulation parameter table.
params.x0 = 3000;

params.R0 = hypot(params.H, params.x0);

% Same synthetic-aperture-duration estimate as EXP02.
params.az_beamwidth = ...
    params.lambda / params.Lant;

params.Tap_est = ...
    params.R0 * ...
    params.az_beamwidth / ...
    params.vsar;

N = round( ...
    params.Tap_est * ...
    params.PRF);

% Use an odd number of samples so eta = 0 is sampled.
if mod(N, 2) == 0
    N = N + 1;
end

N = max(N, 129);

eta = ...
    ((0:N-1) - (N-1)/2) / ...
    params.PRF;

params.N = N;
params.eta = eta;

% Toolbox-free Hann aperture.
params.window = ...
    0.5 ...
    - 0.5*cos( ...
    2*pi*(0:N-1)/(N-1));

fprintf('SAR / reproduction parameters:\n');
fprintf('  fc             = %.3f GHz\n', params.fc/1e9);
fprintf('  lambda         = %.6f m\n', params.lambda);
fprintf('  PRF            = %.3f Hz\n', params.PRF);
fprintf('  H              = %.1f m\n', params.H);
fprintf('  x0             = %.1f m\n', params.x0);
fprintf('  R0             = %.3f m\n', params.R0);
fprintf('  vsar           = %.1f m/s\n', params.vsar);
fprintf('  estimated Tap  = %.6f s\n', params.Tap_est);
fprintf('  N              = %d\n\n', N);

%% 2. Motion states
motions(1) = struct( ...
    'short_name', 'Azimuth velocity', ...
    'label', 'v_a = 20 m/s', ...
    'vr', 0, ...
    'ar', 0, ...
    'va', 20, ...
    'aa', 0);

motions(2) = struct( ...
    'short_name', 'Range acceleration', ...
    'label', 'a_r = 10 m/s^2', ...
    'vr', 0, ...
    'ar', 10, ...
    'va', 0, ...
    'aa', 0);

n_cases = numel(motions);

%% 3. Generate residual signals
fprintf('Generating residual signals...\n');

signals(1) = ...
    simulate_motion_case( ...
    params, motions(1));

signals = ...
    repmat( ...
    signals(1), ...
    1, ...
    n_cases);

for ic = 2:n_cases

    signals(ic) = ...
        simulate_motion_case( ...
        params, motions(ic));

end

fprintf('Residual signals generated.\n\n');

%% 4. FrFT normalized coordinates
%
% Same normalization convention as EXP02.
%
% Physical slow time eta is mapped to normalized t in [-4,4].

t_norm = ...
    eta / ...
    max(abs(eta)) * 4;

u_norm = t_norm;

eta_scale = ...
    max(abs(eta)) / 4;

%% 5. Theoretical FrFT orders from second-order SAR model
%
% Static-target azimuth Doppler rate:
%
%   Ka_static = -2*vsar^2 / (lambda*R0)
%
% Moving-target second-order Doppler rate:
%
%   Ka_move =
%       2[-ar*x0-(vsar-va)^2] / (lambda*R0)
%
% Residual:
%
%   K_res = Ka_move - Ka_static
%
% Under the normalized coordinate t_norm:
%
%   kappa_norm = K_res * eta_scale^2
%
% and
%
%   cot(alpha_opt) + kappa_norm = 0.

Ka_static = ...
    -2 * params.vsar^2 / ...
    (params.lambda * params.R0);

p_theory = ...
    zeros(n_cases, 1);

K_res = ...
    zeros(n_cases, 1);

for ic = 1:n_cases

    ar = motions(ic).ar;
    va = motions(ic).va;

    Ka_move = ...
        2 * ...
        (-ar*params.x0 ...
        - (params.vsar-va)^2) / ...
        (params.lambda * params.R0);

    K_res(ic) = ...
        Ka_move - Ka_static;

    kappa_norm = ...
        K_res(ic) * ...
        eta_scale^2;

    alpha_opt = ...
        atan2( ...
        1, ...
        -kappa_norm);

    p_theory(ic) = ...
        2 * alpha_opt / pi;

end

%% 6. Search settings
%
% Paper:
%   coarse step = 0.1
%   fine step   = 0.005
%
% FrFT order p is periodic with period 4.
% The current useful interval is approximately 0 < p < 2.

p_bounds = [0.02, 1.98];

p_initial = 1.0;

h_coarse = 0.1;
h_fine = 0.005;

fprintf('Search parameters:\n');
fprintf('  initial order = %.3f\n', p_initial);
fprintf('  coarse step   = %.3f\n', h_coarse);
fprintf('  fine step     = %.3f\n', h_fine);
fprintf( ...
    '  search bounds = [%.2f, %.2f]\n\n', ...
    p_bounds(1), ...
    p_bounds(2));

%% 7. Run proposed and traditional searches
%
% IMPORTANT:
% MATLAB struct arrays require every element to have exactly the same fields.
%
% Therefore:
%
%   1) first build a COMPLETE temporary structure prop_i / trad_i;
%   2) add runtime, X_opt, entropy and concentration;
%   3) only then initialize the struct array using Case 1 as template.

fprintf('Starting search comparison...\n\n');

for ic = 1:n_cases

    fprintf('------------------------------------------------------------\n');
    fprintf( ...
        'Case %d: %s (%s)\n', ...
        ic, ...
        motions(ic).short_name, ...
        motions(ic).label);

    fprintf( ...
        'Theoretical order = %.6f\n\n', ...
        p_theory(ic));

    x = signals(ic).residual_signal;

    %% ---------------------------------------------------------
    % Proposed minimum-entropy search

    tic;

    prop_i = ...
        minimum_entropy_search( ...
        x, ...
        t_norm, ...
        u_norm, ...
        p_initial, ...
        h_coarse, ...
        h_fine, ...
        p_bounds);

    prop_i.runtime = toc;

    %% ---------------------------------------------------------
    % Traditional two-stage peak traversal

    tic;

    trad_i = ...
        two_stage_peak_search( ...
        x, ...
        t_norm, ...
        u_norm, ...
        h_coarse, ...
        h_fine, ...
        p_bounds);

    trad_i.runtime = toc;

    %% ---------------------------------------------------------
    % Evaluate final FrFT outputs

    X_prop = ...
        frft_direct( ...
        x, ...
        t_norm, ...
        prop_i.p_opt, ...
        u_norm);

    X_trad = ...
        frft_direct( ...
        x, ...
        t_norm, ...
        trad_i.p_opt, ...
        u_norm);

    P_prop = abs(X_prop).^2;
    P_trad = abs(X_trad).^2;

    %% Complete proposed result structure

    prop_i.X_opt = X_prop;

    prop_i.final_entropy = ...
        signal_entropy(X_prop);

    prop_i.concentration = ...
        max(P_prop) / ...
        sum(P_prop);

    %% Complete traditional result structure

    trad_i.X_opt = X_trad;

    trad_i.final_entropy = ...
        signal_entropy(X_trad);

    trad_i.concentration = ...
        max(P_trad) / ...
        sum(P_trad);

    %% ---------------------------------------------------------
    % Struct-array initialization
    %
    % Only here do the temporary structures contain every field
    % required by all subsequent cases.

    if ic == 1

        proposed = ...
            repmat( ...
            prop_i, ...
            1, ...
            n_cases);

        traditional = ...
            repmat( ...
            trad_i, ...
            1, ...
            n_cases);

    else

        proposed(ic) = prop_i;
        traditional(ic) = trad_i;

    end

    %% ---------------------------------------------------------
    % Console output

    fprintf('PROPOSED minimum entropy:\n');

    fprintf( ...
        '  p_opt         = %.6f\n', ...
        proposed(ic).p_opt);

    fprintf( ...
        '  error         = %.6e\n', ...
        abs( ...
        proposed(ic).p_opt ...
        - p_theory(ic)));

    fprintf( ...
        '  FrFT calls    = %d\n', ...
        proposed(ic).n_frft);

    fprintf( ...
        '  runtime       = %.6f s\n', ...
        proposed(ic).runtime);

    fprintf( ...
        '  entropy       = %.6f\n', ...
        proposed(ic).final_entropy);

    fprintf( ...
        '  concentration = %.6f\n\n', ...
        proposed(ic).concentration);

    fprintf('TRADITIONAL two-stage peak search:\n');

    fprintf( ...
        '  p_opt         = %.6f\n', ...
        traditional(ic).p_opt);

    fprintf( ...
        '  error         = %.6e\n', ...
        abs( ...
        traditional(ic).p_opt ...
        - p_theory(ic)));

    fprintf( ...
        '  FrFT calls    = %d\n', ...
        traditional(ic).n_frft);

    fprintf( ...
        '  runtime       = %.6f s\n', ...
        traditional(ic).runtime);

    fprintf( ...
        '  entropy       = %.6f\n', ...
        traditional(ic).final_entropy);

    fprintf( ...
        '  concentration = %.6f\n\n', ...
        traditional(ic).concentration);

end

fprintf('Search comparison completed.\n\n');

%% 8. Diagnostic order curves
%
% This grid is ONLY used for visualization.
%
% These FrFT calculations are NOT included in either search benchmark.

p_diag = 0.05 : 0.02 : 1.95;

diag_entropy = ...
    zeros( ...
    n_cases, ...
    numel(p_diag));

diag_peak = ...
    zeros( ...
    n_cases, ...
    numel(p_diag));

fprintf( ...
    'Calculating diagnostic curves ' + ...
    "(not included in benchmark)...\n");

for ic = 1:n_cases

    x = signals(ic).residual_signal;

    for ip = 1:numel(p_diag)

        Xp = ...
            frft_direct( ...
            x, ...
            t_norm, ...
            p_diag(ip), ...
            u_norm);

        power_p = ...
            abs(Xp).^2;

        diag_entropy(ic, ip) = ...
            signal_entropy(Xp);

        diag_peak(ic, ip) = ...
            max(power_p);

    end

end

fprintf('Diagnostic curves completed.\n\n');

%% 9. Figure 1: entropy curve and proposed search trajectory

fig1 = figure( ...
    'Name', ...
    'EXP03 - Entropy search trajectory', ...
    'Color', ...
    'w');

tiledlayout( ...
    1, ...
    2, ...
    'Padding', ...
    'compact', ...
    'TileSpacing', ...
    'compact');

for ic = 1:n_cases

    nexttile;

    H = ...
        diag_entropy(ic, :);

    plot( ...
        p_diag, ...
        H, ...
        'LineWidth', ...
        1.5);

    hold on;

    plot( ...
        proposed(ic).p_history, ...
        proposed(ic).entropy_history, ...
        'o-', ...
        'LineWidth', ...
        1.2, ...
        'MarkerSize', ...
        5);

    xline( ...
        p_theory(ic), ...
        '--', ...
        'Theory', ...
        'LineWidth', ...
        1.2);

    xline( ...
        proposed(ic).p_opt, ...
        ':', ...
        'Proposed', ...
        'LineWidth', ...
        1.2);

    xline( ...
        traditional(ic).p_opt, ...
        '-.', ...
        'Traditional', ...
        'LineWidth', ...
        1.2);

    hold off;

    grid on;

    xlabel('FrFT order p');
    ylabel('Entropy');

    title( ...
        sprintf( ...
        '%s\n%d proposed FrFT evaluations', ...
        motions(ic).short_name, ...
        proposed(ic).n_frft));

    legend( ...
        'Entropy curve', ...
        'Visited orders', ...
        'Theory', ...
        'Proposed', ...
        'Traditional', ...
        'Location', ...
        'best');

end

sgtitle( ...
    'Advance-and-retreat minimum-entropy search');

exportgraphics( ...
    fig1, ...
    fullfile( ...
    results_dir, ...
    'fig01_entropy_search_trajectory.png'), ...
    'Resolution', ...
    180);

%% 10. Figure 2: peak curve and traditional traversal result

fig2 = figure( ...
    'Name', ...
    'EXP03 - Peak search', ...
    'Color', ...
    'w');

tiledlayout( ...
    1, ...
    2, ...
    'Padding', ...
    'compact', ...
    'TileSpacing', ...
    'compact');

for ic = 1:n_cases

    nexttile;

    peak_norm = ...
        diag_peak(ic, :) / ...
        max(diag_peak(ic, :));

    plot( ...
        p_diag, ...
        peak_norm, ...
        'LineWidth', ...
        1.5);

    hold on;

    xline( ...
        p_theory(ic), ...
        '--', ...
        'Theory', ...
        'LineWidth', ...
        1.2);

    xline( ...
        traditional(ic).p_opt, ...
        ':', ...
        'Peak search', ...
        'LineWidth', ...
        1.2);

    hold off;

    grid on;

    xlabel('FrFT order p');
    ylabel('Normalized peak');

    title( ...
        sprintf( ...
        '%s\n%d traditional FrFT evaluations', ...
        motions(ic).short_name, ...
        traditional(ic).n_frft));

end

sgtitle( ...
    'Traditional FrFT peak traversal');

exportgraphics( ...
    fig2, ...
    fullfile( ...
    results_dir, ...
    'fig02_traditional_peak_search.png'), ...
    'Resolution', ...
    180);

%% 11. Figure 3: final FrFT outputs

fig3 = figure( ...
    'Name', ...
    'EXP03 - Final refocusing comparison', ...
    'Color', ...
    'w');

tiledlayout( ...
    2, ...
    2, ...
    'Padding', ...
    'compact', ...
    'TileSpacing', ...
    'compact');

for ic = 1:n_cases

    %% Proposed

    nexttile;

    amp_prop = ...
        abs(proposed(ic).X_opt);

    amp_prop = ...
        amp_prop / ...
        max(amp_prop);

    plot( ...
        u_norm, ...
        amp_prop, ...
        'LineWidth', ...
        1.3);

    grid on;

    xlabel('Fractional coordinate u');
    ylabel('Normalized magnitude');

    title( ...
        sprintf( ...
        '%s - Proposed\np=%.4f, H=%.3f', ...
        motions(ic).short_name, ...
        proposed(ic).p_opt, ...
        proposed(ic).final_entropy));

    %% Traditional

    nexttile;

    amp_trad = ...
        abs(traditional(ic).X_opt);

    amp_trad = ...
        amp_trad / ...
        max(amp_trad);

    plot( ...
        u_norm, ...
        amp_trad, ...
        'LineWidth', ...
        1.3);

    grid on;

    xlabel('Fractional coordinate u');
    ylabel('Normalized magnitude');

    title( ...
        sprintf( ...
        '%s - Traditional\np=%.4f, H=%.3f', ...
        motions(ic).short_name, ...
        traditional(ic).p_opt, ...
        traditional(ic).final_entropy));

end

sgtitle( ...
    'Refocusing quality after different order-search methods');

exportgraphics( ...
    fig3, ...
    fullfile( ...
    results_dir, ...
    'fig03_refocusing_comparison.png'), ...
    'Resolution', ...
    180);

%% 12. Figure 4: FrFT evaluation-count comparison

counts = ...
    zeros( ...
    n_cases, ...
    2);

for ic = 1:n_cases

    counts(ic, 1) = ...
        traditional(ic).n_frft;

    counts(ic, 2) = ...
        proposed(ic).n_frft;

end

fig4 = figure( ...
    'Name', ...
    'EXP03 - FrFT evaluation counts', ...
    'Color', ...
    'w');

bar(counts);

grid on;

xticks(1:n_cases);

xticklabels({ ...
    'Azimuth velocity', ...
    'Range acceleration'});

ylabel( ...
    'Number of FrFT evaluations');

legend( ...
    'Traditional peak traversal', ...
    'Proposed minimum entropy', ...
    'Location', ...
    'best');

title( ...
    'Computational burden measured by FrFT evaluations');

exportgraphics( ...
    fig4, ...
    fullfile( ...
    results_dir, ...
    'fig04_frft_evaluation_counts.png'), ...
    'Resolution', ...
    180);

%% 13. Figure 5: runtime comparison

runtime_matrix = ...
    zeros( ...
    n_cases, ...
    2);

for ic = 1:n_cases

    runtime_matrix(ic, 1) = ...
        traditional(ic).runtime;

    runtime_matrix(ic, 2) = ...
        proposed(ic).runtime;

end

fig5 = figure( ...
    'Name', ...
    'EXP03 - Runtime comparison', ...
    'Color', ...
    'w');

bar(runtime_matrix);

grid on;

xticks(1:n_cases);

xticklabels({ ...
    'Azimuth velocity', ...
    'Range acceleration'});

ylabel( ...
    'Runtime (s)');

legend( ...
    'Traditional peak traversal', ...
    'Proposed minimum entropy', ...
    'Location', ...
    'best');

title( ...
    ['Runtime comparison using the ', ...
    'current direct FrFT implementation']);

exportgraphics( ...
    fig5, ...
    fullfile( ...
    results_dir, ...
    'fig05_runtime_comparison.png'), ...
    'Resolution', ...
    180);

%% 14. Numerical summary

MotionState = ...
    strings(n_cases, 1);

TheoryOrder = ...
    zeros(n_cases, 1);

ProposedOrder = ...
    zeros(n_cases, 1);

TraditionalOrder = ...
    zeros(n_cases, 1);

ProposedOrderError = ...
    zeros(n_cases, 1);

TraditionalOrderError = ...
    zeros(n_cases, 1);

ProposedFrFTCalls = ...
    zeros(n_cases, 1);

TraditionalFrFTCalls = ...
    zeros(n_cases, 1);

CallReductionPercent = ...
    zeros(n_cases, 1);

ProposedRuntime_s = ...
    zeros(n_cases, 1);

TraditionalRuntime_s = ...
    zeros(n_cases, 1);

RuntimeSpeedup = ...
    zeros(n_cases, 1);

ProposedEntropy = ...
    zeros(n_cases, 1);

TraditionalEntropy = ...
    zeros(n_cases, 1);

ProposedConcentration = ...
    zeros(n_cases, 1);

TraditionalConcentration = ...
    zeros(n_cases, 1);

for ic = 1:n_cases

    MotionState(ic) = ...
        string( ...
        motions(ic).short_name);

    TheoryOrder(ic) = ...
        p_theory(ic);

    ProposedOrder(ic) = ...
        proposed(ic).p_opt;

    TraditionalOrder(ic) = ...
        traditional(ic).p_opt;

    ProposedOrderError(ic) = ...
        abs( ...
        ProposedOrder(ic) ...
        - TheoryOrder(ic));

    TraditionalOrderError(ic) = ...
        abs( ...
        TraditionalOrder(ic) ...
        - TheoryOrder(ic));

    ProposedFrFTCalls(ic) = ...
        proposed(ic).n_frft;

    TraditionalFrFTCalls(ic) = ...
        traditional(ic).n_frft;

    CallReductionPercent(ic) = ...
        100 * ...
        (1 ...
        - ProposedFrFTCalls(ic) / ...
        TraditionalFrFTCalls(ic));

    ProposedRuntime_s(ic) = ...
        proposed(ic).runtime;

    TraditionalRuntime_s(ic) = ...
        traditional(ic).runtime;

    RuntimeSpeedup(ic) = ...
        TraditionalRuntime_s(ic) / ...
        ProposedRuntime_s(ic);

    ProposedEntropy(ic) = ...
        proposed(ic).final_entropy;

    TraditionalEntropy(ic) = ...
        traditional(ic).final_entropy;

    ProposedConcentration(ic) = ...
        proposed(ic).concentration;

    TraditionalConcentration(ic) = ...
        traditional(ic).concentration;

end

summary_table = table( ...
    MotionState, ...
    TheoryOrder, ...
    ProposedOrder, ...
    TraditionalOrder, ...
    ProposedOrderError, ...
    TraditionalOrderError, ...
    ProposedFrFTCalls, ...
    TraditionalFrFTCalls, ...
    CallReductionPercent, ...
    ProposedRuntime_s, ...
    TraditionalRuntime_s, ...
    RuntimeSpeedup, ...
    ProposedEntropy, ...
    TraditionalEntropy, ...
    ProposedConcentration, ...
    TraditionalConcentration);

disp(' ');
disp('================ EXP03 SUMMARY TABLE ================');
disp(summary_table);

%% 15. Console interpretation

fprintf('\n');
fprintf('================ EXP03 INTERPRETATION ================\n');

for ic = 1:n_cases

    fprintf( ...
        '\n%s:\n', ...
        motions(ic).short_name);

    fprintf( ...
        '  theory order          = %.6f\n', ...
        p_theory(ic));

    fprintf( ...
        '  proposed order        = %.6f\n', ...
        proposed(ic).p_opt);

    fprintf( ...
        '  traditional order     = %.6f\n', ...
        traditional(ic).p_opt);

    fprintf( ...
        '  proposed FrFT calls   = %d\n', ...
        proposed(ic).n_frft);

    fprintf( ...
        '  traditional calls     = %d\n', ...
        traditional(ic).n_frft);

    fprintf( ...
        '  call reduction        = %.2f %%\n', ...
        CallReductionPercent(ic));

    fprintf( ...
        '  runtime speedup       = %.3f x\n', ...
        RuntimeSpeedup(ic));

    fprintf( ...
        ['  entropy proposed/' ...
        'traditional = %.6f / %.6f\n'], ...
        ProposedEntropy(ic), ...
        TraditionalEntropy(ic));

end

fprintf('\nExpected qualitative conclusion:\n');

fprintf( ...
    ['  1. Proposed order should remain close ', ...
    'to theoretical order.\n']);

fprintf( ...
    ['  2. Final focusing quality should be close ', ...
    'to traditional search.\n']);

fprintf( ...
    ['  3. Proposed method should require ', ...
    'substantially fewer FrFT calls.\n']);

fprintf( ...
    ['  4. Absolute runtime is implementation-dependent; ', ...
    'FrFT-call count is\n']);

fprintf( ...
    ['     the cleaner algorithmic complexity indicator ', ...
    'in this experiment.\n']);

fprintf('=======================================================\n');

%% 16. Save results

save( ...
    fullfile( ...
    results_dir, ...
    'exp03_summary.mat'), ...
    'params', ...
    'motions', ...
    'signals', ...
    'proposed', ...
    'traditional', ...
    'summary_table', ...
    'p_theory', ...
    'K_res');

writetable( ...
    summary_table, ...
    fullfile( ...
    results_dir, ...
    'exp03_summary.csv'));

fprintf('\nSaved EXP03 results to:\n%s\n', results_dir);