function results = exp09_pa5g_continuous_subbin_gating()
%EXP09_PA5G_CONTINUOUS_SUBBIN_GATING
% EXP009 / PA5G
%
% Continuous Sub-Bin Estimation and Evidence-Gated Recentering
%
% Research questions
% ------------------
% RQ1. Does a continuous single-tone ML/LS estimator eliminate the
%      deterministic intermediate-offset bias of the PA5F log-parabolic
%      estimator?
%
% RQ2. In a coherent strong+weak mixture, how much apparent sub-bin shift
%      remains after replacing interpolation by continuous estimation?
%
% RQ3. Can a data-driven evidence gate suppress the eta=0 false-correction
%      problem without sacrificing the large-off-grid recentering gain?
%
% RQ4. If the gate still fails, is the remaining bottleneck model selection
%      or mixture-induced structured bias?
%
% Continuous estimator
% --------------------
% After true strong dechirping:
%
%   z[n] = A_s exp(j 2 pi nu n/N) + contamination.
%
% For a candidate nu and unknown complex amplitude c:
%
%   c_hat(nu) = arg min_c ||z-c a(nu)||^2
%
% and therefore:
%
%   nu_hat = arg max_nu |a(nu)^H z|^2.
%
% The optimization is continuous. A small deterministic coarse bracket is
% used only to locate the local interval for fminbnd; the final estimate is
% not grid-quantized.
%
% Evidence gate
% -------------
% Integer model H0:
%   nu constrained to nearest integer.
%
% Continuous model H1:
%   nu = continuous ML estimate.
%
% BIC:
%   BIC = N log(RSS/N) + k log N.
%
% The continuous model adds one real frequency parameter.
%
% To reduce mixture-induced false correction, PA5G additionally estimates
% frequency on the first and second aperture halves. Recentering is applied
% only when:
%
%   DeltaBIC = BIC_H0 - BIC_H1 > 0
%
% AND
%
%   |fractional nu_hat| > |nu_hat_left - nu_hat_right|.
%
% Thus the claimed shift must exceed the data's own split-aperture
% disagreement. No physical threshold is tuned.
%
% Groups
% ------
% G0_Baseline
% G1_OracleRecenter
% G2_ContinuousStrongOnly
% G3_ContinuousMixtureAlways
% G4_EvidenceGatedMixture
%
% Isolation
% ---------
% - true strong chirp rate for every group;
% - no noise;
% - no clutter;
% - fixed PlateauAwareTol removal semantics.
%
% Run:
%   results = exp09_pa5g_continuous_subbin_gating;

cfg = config_exp09_pa5g_continuous_subbin_gating();

validate_config_complete(cfg);
run_startup_self_tests(cfg);

%% Output path
this_dir = fileparts(mfilename('fullpath'));
code_dir = fileparts(this_dir);
paper_root = fileparts(code_dir);

if isempty(cfg.output_dir)
    out_path = fullfile( ...
        paper_root,'results','exp09_physical_validation', ...
        'exp09_pa5g_continuous_subbin_gating');
else
    out_path = cfg.output_dir;
end

if ~exist(out_path,'dir')
    mkdir(out_path);
end

%% Physical constants
lambda = cfg.c/cfg.fc_hz;
R0 = cfg.platform_height_m*cfg.slant_range_factor;

beamwidth_rad = ...
    cfg.beamwidth_scale * ...
    lambda/cfg.antenna_length_m;

vw = cfg.weak_velocity_mps;

[~,~,Kw] = residual_fm_rates( ...
    vw,R0,lambda,cfg);

aw = Kw/(cfg.prf_hz^2);

%% Apertures
T_paper = cfg.paper_aperture_time_s;
N_paper = max(32,round(cfg.prf_hz*T_paper));

T_beam = ...
    R0*beamwidth_rad/cfg.platform_velocity_mps;
N_beam = max(32,round(cfg.prf_hz*T_beam));

aperture_names = ["Paper1s","BeamDerived"];
N_list = [N_paper,N_beam];

sides = ["LowV","HighV"];

%% =======================================================================
% Track A — strong-only estimator audit
% ========================================================================
est_rows = {};

for ia = 1:numel(aperture_names)

    mode = aperture_names(ia);
    N = N_list(ia);

    for io = 1:numel(cfg.fractional_bin_offsets)

        eta = cfg.fractional_bin_offsets(io);
        b = eta/N;

        for idv = 1:numel(cfg.delta_velocity_mps)

            dv = cfg.delta_velocity_mps(idv);

            for iside = 1:numel(sides)

                side = sides(iside);

                if side=="LowV"
                    vs = vw-dv;
                else
                    vs = vw+dv;
                end

                [~,~,Ks] = residual_fm_rates( ...
                    vs,R0,lambda,cfg);

                as = Ks/(cfg.prf_hz^2);

                s0 = synth_discrete_lfm( ...
                    N,cfg.A_strong,as,b,0);

                eta_old = estimate_log_parabolic( ...
                    s0,as,cfg);

                [eta_ml,ml_diag] = ...
                    estimate_continuous_ml( ...
                        s0,as,cfg);

                err_old = fractional_error( ...
                    eta_old,eta);

                err_ml = fractional_error( ...
                    eta_ml,eta);

                [gate_diag,~] = ...
                    model_evidence_gate( ...
                        s0,as,eta_ml,cfg);

                est_rows(end+1,:) = { ... %#ok<AGROW>
                    char(mode),N,eta,dv,char(side),vs, ...
                    eta_old,err_old, ...
                    eta_ml,err_ml, ...
                    ml_diag.coarse_integer_bin, ...
                    ml_diag.objective_gain_vs_integer, ...
                    gate_diag.delta_bic, ...
                    gate_diag.split_inconsistency_bins, ...
                    double(gate_diag.bic_prefers_continuous), ...
                    double(gate_diag.primary_gate_trigger)};
            end
        end
    end
end

estimator_trials = cell2table(est_rows, ...
    'VariableNames',{ ...
    'aperture_mode','azimuth_samples', ...
    'true_eta_bins','delta_velocity_mps', ...
    'strong_velocity_side','strong_velocity_mps', ...
    'old_parabolic_eta_hat_bins', ...
    'old_parabolic_eta_error_bins', ...
    'continuous_ml_eta_hat_bins', ...
    'continuous_ml_eta_error_bins', ...
    'coarse_integer_bin', ...
    'continuous_objective_gain_vs_integer', ...
    'delta_bic', ...
    'split_inconsistency_bins', ...
    'bic_prefers_continuous', ...
    'primary_gate_trigger'});

writetable(estimator_trials, ...
    fullfile(out_path,'pa5g_strongonly_estimator_trials.csv'));

estimator_summary = ...
    summarize_strongonly_estimators( ...
        estimator_trials);

writetable(estimator_summary, ...
    fullfile(out_path,'pa5g_strongonly_estimator_summary.csv'));

%% =======================================================================
% Track B — zero-mismatch floor audit with continuous strong-only estimate
% ========================================================================
floor_groups = [ ...
    "G0_Baseline", ...
    "G1_OracleRecenter", ...
    "G2_ContinuousStrongOnly"];

floor_rows = {};

for ia = 1:numel(aperture_names)

    mode = aperture_names(ia);
    N = N_list(ia);

    for io = 1:numel(cfg.fractional_bin_offsets)

        eta = cfg.fractional_bin_offsets(io);
        b = eta/N;

        for idv = 1:numel(cfg.delta_velocity_mps)

            dv = cfg.delta_velocity_mps(idv);

            for iside = 1:numel(sides)

                side = sides(iside);

                if side=="LowV"
                    vs = vw-dv;
                else
                    vs = vw+dv;
                end

                [~,~,Ks] = residual_fm_rates( ...
                    vs,R0,lambda,cfg);

                as = Ks/(cfg.prf_hz^2);

                s0 = synth_discrete_lfm( ...
                    N,cfg.A_strong,as,b,0);

                w0 = synth_discrete_lfm( ...
                    N,1,aw,b,0);

                [eta_ml,~] = ...
                    estimate_continuous_ml( ...
                        s0,as,cfg);

                eta_ml_frac = fractional_component(eta_ml);

                eta_used_values = [ ...
                    0, ...
                    eta, ...
                    eta_ml_frac];

                for ig = 1:numel(floor_groups)

                    group = floor_groups(ig);
                    eta_used = eta_used_values(ig);

                    [s_rec,~] = recenter_signal( ...
                        s0,eta_used);

                    [w_rec,~] = recenter_signal( ...
                        w0,eta_used);

                    Ys = matched_lfm_transform( ...
                        s_rec,as);

                    for il = 1:numel( ...
                            cfg.filter_window_length_bins)

                        Lwin = ...
                            cfg.filter_window_length_bins(il);

                        [mask,mask_info] = ...
                            build_plateau_tol_mask( ...
                                Ys,Lwin,cfg);

                        [sr,wr] = ...
                            apply_fixed_mask_components( ...
                                s_rec,w_rec,as,mask);

                        L0 = ...
                            norm(sr) / ...
                            max(norm(s_rec), ...
                                cfg.small_norm_floor);

                        D0 = ...
                            norm(wr) / ...
                            max(norm(w_rec), ...
                                cfg.small_norm_floor);

                        rmin = ...
                            recoverability_floor(L0,D0);

                        floor_rows(end+1,:) = { ... %#ok<AGROW>
                            char(mode),N,eta,dv, ...
                            char(side),vs,char(group), ...
                            eta_used, ...
                            fractional_error(eta_used,eta), ...
                            Lwin,L0,D0,rmin, ...
                            mask_info.mask_bin_count};
                    end
                end
            end
        end
    end
end

floor_trials = cell2table(floor_rows, ...
    'VariableNames',{ ...
    'aperture_mode','azimuth_samples', ...
    'true_eta_bins','delta_velocity_mps', ...
    'strong_velocity_side','strong_velocity_mps', ...
    'group','eta_used_bins', ...
    'eta_used_error_bins','window_bins', ...
    'zero_mismatch_strong_leak_L0', ...
    'zero_mismatch_weak_loss_D0', ...
    'recoverability_floor_rmin', ...
    'mask_bin_count'});

writetable(floor_trials, ...
    fullfile(out_path,'pa5g_floor_trials.csv'));

floor_summary = summarize_floor(floor_trials);

writetable(floor_summary, ...
    fullfile(out_path,'pa5g_floor_summary.csv'));

best_floor_summary = ...
    summarize_best_floor(floor_summary);

writetable(best_floor_summary, ...
    fullfile(out_path,'pa5g_best_floor_summary.csv'));

%% =======================================================================
% Track C — practical coherent-mixture gating audit
% ========================================================================
groups = [ ...
    "G0_Baseline", ...
    "G1_OracleRecenter", ...
    "G2_ContinuousStrongOnly", ...
    "G3_ContinuousMixtureAlways", ...
    "G4_EvidenceGatedMixture"];

trial_rows = {};
gate_rows = {};

for ia = 1:numel(aperture_names)

    mode = aperture_names(ia);
    N = N_list(ia);

    for io = 1:numel(cfg.fractional_bin_offsets)

        eta = cfg.fractional_bin_offsets(io);
        b = eta/N;

        for idv = 1:numel(cfg.delta_velocity_mps)

            dv = cfg.delta_velocity_mps(idv);

            for iside = 1:numel(sides)

                side = sides(iside);

                if side=="LowV"
                    vs = vw-dv;
                else
                    vs = vw+dv;
                end

                [~,~,Ks] = residual_fm_rates( ...
                    vs,R0,lambda,cfg);

                as = Ks/(cfg.prf_hz^2);

                s0 = synth_discrete_lfm( ...
                    N,cfg.A_strong,as,b,0);

                w_unit = synth_discrete_lfm( ...
                    N,1,aw,b,0);

                [eta_g2_abs,~] = ...
                    estimate_continuous_ml( ...
                        s0,as,cfg);

                eta_g2 = ...
                    fractional_component(eta_g2_abs);

                for ir = 1:numel( ...
                        cfg.weak_to_strong_ratio)

                    rA = cfg.weak_to_strong_ratio(ir);

                    for ip = 1:numel( ...
                            cfg.relative_phase_rad)

                        phi = cfg.relative_phase_rad(ip);

                        w_true = ...
                            rA*exp(1j*phi)*w_unit;

                        x = s0+w_true;

                        [eta_mix_abs,mix_ml_diag] = ...
                            estimate_continuous_ml( ...
                                x,as,cfg);

                        eta_mix = ...
                            fractional_component(eta_mix_abs);

                        [gate_diag,split_diag] = ...
                            model_evidence_gate( ...
                                x,as,eta_mix_abs,cfg);

                        if gate_diag.primary_gate_trigger
                            eta_g4 = eta_mix;
                        else
                            eta_g4 = 0;
                        end

                        eta_used_values = [ ...
                            0, ...
                            eta, ...
                            eta_g2, ...
                            eta_mix, ...
                            eta_g4];

                        gate_rows(end+1,:) = { ... %#ok<AGROW>
                            char(mode),N,eta,dv, ...
                            char(side),vs,rA,phi, ...
                            eta_mix_abs,eta_mix, ...
                            fractional_error(eta_mix,eta), ...
                            mix_ml_diag.objective_gain_vs_integer, ...
                            gate_diag.nu_integer_bins, ...
                            gate_diag.rss_integer, ...
                            gate_diag.rss_continuous, ...
                            gate_diag.delta_bic, ...
                            double(gate_diag.bic_prefers_continuous), ...
                            split_diag.nu_left_bins, ...
                            split_diag.nu_right_bins, ...
                            split_diag.split_inconsistency_bins, ...
                            abs(eta_mix), ...
                            double(gate_diag.shift_exceeds_split), ...
                            double(gate_diag.primary_gate_trigger)};

                        for ig = 1:numel(groups)

                            group = groups(ig);
                            eta_used = eta_used_values(ig);

                            [x_rec,~] = ...
                                recenter_signal( ...
                                    x,eta_used);

                            [s_rec,~] = ...
                                recenter_signal( ...
                                    s0,eta_used);

                            [w_rec,~] = ...
                                recenter_signal( ...
                                    w_true,eta_used);

                            Yx = matched_lfm_transform( ...
                                x_rec,as);

                            for il = 1:numel( ...
                                    cfg.filter_window_length_bins)

                                Lwin = ...
                                    cfg.filter_window_length_bins(il);

                                [mask,mask_info] = ...
                                    build_plateau_tol_mask( ...
                                        Yx,Lwin,cfg);

                                residual = ...
                                    remove_with_mask( ...
                                        x_rec,as,mask);

                                E = ...
                                    norm(residual-w_rec) / ...
                                    max(norm(w_rec), ...
                                        cfg.small_norm_floor);

                                [sr,wr] = ...
                                    apply_fixed_mask_components( ...
                                        s_rec,w_rec,as,mask);

                                Ls = ...
                                    norm(sr) / ...
                                    max(norm(s_rec), ...
                                        cfg.small_norm_floor);

                                Dw = ...
                                    norm(wr) / ...
                                    max(norm(w_rec), ...
                                        cfg.small_norm_floor);

                                Epred = sqrt( ...
                                    (Ls/rA)^2 + Dw^2);

                                identity_err = ...
                                    abs(E-Epred);

                                bweak_after = ...
                                    (eta-eta_used)/N;

                                [weak_ok,weak_ratio] = ...
                                    weak_stage_readiness( ...
                                        residual,aw, ...
                                        bweak_after,cfg);

                                trial_rows(end+1,:) = { ... %#ok<AGROW>
                                    char(mode),N,eta,dv, ...
                                    char(side),vs,rA,phi, ...
                                    char(group), ...
                                    eta_used, ...
                                    fractional_error( ...
                                        eta_used,eta), ...
                                    double(gate_diag.primary_gate_trigger), ...
                                    gate_diag.delta_bic, ...
                                    split_diag.split_inconsistency_bins, ...
                                    Lwin,E, ...
                                    double(E<= ...
                                        cfg.error_feasible_threshold), ...
                                    double(weak_ok), ...
                                    weak_ratio,Ls,Dw,Epred, ...
                                    identity_err, ...
                                    mask_info.mask_bin_count};
                            end
                        end
                    end
                end
            end
        end
    end
end

gate_trials = cell2table(gate_rows, ...
    'VariableNames',{ ...
    'aperture_mode','azimuth_samples', ...
    'true_eta_bins','delta_velocity_mps', ...
    'strong_velocity_side','strong_velocity_mps', ...
    'weak_to_strong_ratio','relative_phase_rad', ...
    'continuous_mix_eta_hat_abs_bins', ...
    'continuous_mix_fractional_eta_hat_bins', ...
    'continuous_mix_eta_error_bins', ...
    'continuous_objective_gain_vs_integer', ...
    'integer_model_nu_bins', ...
    'rss_integer','rss_continuous', ...
    'delta_bic','bic_prefers_continuous', ...
    'split_eta_left_bins','split_eta_right_bins', ...
    'split_inconsistency_bins', ...
    'estimated_shift_magnitude_bins', ...
    'shift_exceeds_split', ...
    'primary_gate_trigger'});

writetable(gate_trials, ...
    fullfile(out_path,'pa5g_gate_trials.csv'));

gate_summary = summarize_gate(gate_trials);

writetable(gate_summary, ...
    fullfile(out_path,'pa5g_gate_summary.csv'));

contrast_gate_summary = ...
    summarize_gate_by_contrast(gate_trials);

writetable(contrast_gate_summary, ...
    fullfile(out_path,'pa5g_gate_by_contrast.csv'));

practical_trials = cell2table(trial_rows, ...
    'VariableNames',{ ...
    'aperture_mode','azimuth_samples', ...
    'true_eta_bins','delta_velocity_mps', ...
    'strong_velocity_side','strong_velocity_mps', ...
    'weak_to_strong_ratio','relative_phase_rad', ...
    'group','eta_used_bins','eta_used_error_bins', ...
    'primary_gate_trigger','delta_bic', ...
    'split_inconsistency_bins','window_bins', ...
    'practical_error_ratio', ...
    'error_feasible_E_le_1', ...
    'weak_stage_success','weak_stage_peak_ratio', ...
    'strong_leak_ratio','weak_projection_loss_ratio', ...
    'predicted_error_ratio','identity_abs_error', ...
    'mask_bin_count'});

writetable(practical_trials, ...
    fullfile(out_path,'pa5g_practical_trials.csv'));

practical_summary = ...
    summarize_practical(practical_trials);

writetable(practical_summary, ...
    fullfile(out_path,'pa5g_practical_summary.csv'));

best_practical_summary = ...
    summarize_best_practical( ...
        practical_summary);

writetable(best_practical_summary, ...
    fullfile(out_path,'pa5g_best_practical_summary.csv'));

identity_summary = ...
    summarize_identity( ...
        practical_trials,cfg);

writetable(identity_summary, ...
    fullfile(out_path,'pa5g_projection_identity_summary.csv'));

%% Improvement and decision
improvement_summary = ...
    summarize_improvement( ...
        best_practical_summary);

writetable(improvement_summary, ...
    fullfile(out_path,'pa5g_improvement_summary.csv'));

decision_summary = ...
    build_decision_summary( ...
        estimator_summary, ...
        gate_summary, ...
        best_practical_summary, ...
        identity_summary,cfg);

writetable(decision_summary, ...
    fullfile(out_path,'pa5g_decision_summary.csv'));

%% Text summary
write_summary( ...
    out_path,cfg,lambda,R0, ...
    estimator_summary,best_floor_summary, ...
    gate_summary,best_practical_summary, ...
    identity_summary,decision_summary);

%% Figures
make_figures( ...
    out_path,cfg, ...
    estimator_summary,gate_summary, ...
    contrast_gate_summary, ...
    best_practical_summary, ...
    practical_summary);

%% Save
results = struct();
results.cfg = cfg;
results.lambda = lambda;
results.R0 = R0;
results.estimator_trials = estimator_trials;
results.estimator_summary = estimator_summary;
results.floor_trials = floor_trials;
results.floor_summary = floor_summary;
results.best_floor_summary = best_floor_summary;
results.gate_trials = gate_trials;
results.gate_summary = gate_summary;
results.contrast_gate_summary = contrast_gate_summary;
results.practical_trials = practical_trials;
results.practical_summary = practical_summary;
results.best_practical_summary = best_practical_summary;
results.identity_summary = identity_summary;
results.improvement_summary = improvement_summary;
results.decision_summary = decision_summary;

save(fullfile(out_path,'exp09_pa5g_results.mat'), ...
    'results','-v7.3');

fprintf('\n============================================================\n');
fprintf(' EXP009 PA5G / Continuous Sub-Bin Estimation + Gating\n');
fprintf('============================================================\n');
disp(estimator_summary);
disp(gate_summary);
disp(best_floor_summary);
disp(best_practical_summary);
disp(decision_summary);
fprintf('============================================================\n');
fprintf('Saved to:\n%s\n\n',out_path);

end

%% ========================================================================
function validate_config_complete(cfg)

required = { ...
    'c', ...
    'fc_hz', ...
    'prf_hz', ...
    'bandwidth_hz', ...
    'platform_height_m', ...
    'antenna_length_m', ...
    'platform_velocity_mps', ...
    'pulse_width_s', ...
    'slant_range_factor', ...
    'paper_aperture_time_s', ...
    'beamwidth_scale', ...
    'weak_velocity_mps', ...
    'delta_velocity_mps', ...
    'A_strong', ...
    'weak_to_strong_ratio', ...
    'num_relative_phases', ...
    'relative_phase_rad', ...
    'fractional_bin_offsets', ...
    'filter_window_length_bins', ...
    'peak_semantics', ...
    'frac_domain_peak_gate', ...
    'tie_eps_multiplier', ...
    'old_subbin_estimator', ...
    'log_power_floor', ...
    'subbin_delta_clip', ...
    'ml_search_halfwidth_bins', ...
    'ml_bracket_points', ...
    'ml_tolx_bins', ...
    'ml_max_fun_evals', ...
    'bic_k_integer', ...
    'bic_k_continuous', ...
    'bic_eps_multiplier', ...
    'split_min_samples', ...
    'weak_stage_peak_gate', ...
    'weak_stage_center_tolerance_bins', ...
    'error_feasible_threshold', ...
    'small_norm_floor', ...
    'continuous_solver_rmse_gate_bins', ...
    'identity_gate', ...
    'figure_visible', ...
    'output_dir'};

missing = required(~isfield(cfg,required));

if ~isempty(missing)
    error('EXP009:PA5G:MissingConfigField', ...
        'Missing config field(s): %s', ...
        strjoin(missing,', '));
end

end

%% ========================================================================
function run_startup_self_tests(cfg)
% Fail early before the long sweep.

%% Test 1 — continuous estimator on all target offsets
N = 188;
a = 0.001731;

for eta = cfg.fractional_bin_offsets

    x = synth_discrete_lfm( ...
        N,1,a,eta/N,0);

    [ehat,~] = ...
        estimate_continuous_ml(x,a,cfg);

    e = abs(fractional_error(ehat,eta));

    if e>cfg.continuous_solver_rmse_gate_bins
        error('EXP009:PA5G:ContinuousEstimatorSelfTestFailed', ...
            ['Continuous estimator self-test failed at eta=%g. ' ...
             'Error=%g bins.'],eta,e);
    end
end

%% Test 2 — BIC gate must stay OFF for an exact on-grid single tone
x0 = synth_discrete_lfm(N,1,a,0,0);

[e0,~] = estimate_continuous_ml(x0,a,cfg);

[g0,s0diag] = model_evidence_gate( ...
    x0,a,e0,cfg);

% Interface-contract guard: callers may use either the first-output gate
% structure or the second-output split structure. Both must expose the
% split diagnostic explicitly. This prevents field-routing regressions.
required_gate_fields = { ...
    'delta_bic', ...
    'bic_prefers_continuous', ...
    'nu_left_bins', ...
    'nu_right_bins', ...
    'split_inconsistency_bins', ...
    'shift_exceeds_split', ...
    'primary_gate_trigger'};

for ii = 1:numel(required_gate_fields)
    if ~isfield(g0,required_gate_fields{ii})
        error('EXP009:PA5G:GateInterfaceSelfTestFailed', ...
            'Gate output is missing field: %s', ...
            required_gate_fields{ii});
    end
end

required_split_fields = { ...
    'nu_left_bins', ...
    'nu_right_bins', ...
    'split_inconsistency_bins'};

for ii = 1:numel(required_split_fields)
    if ~isfield(s0diag,required_split_fields{ii})
        error('EXP009:PA5G:SplitInterfaceSelfTestFailed', ...
            'Split output is missing field: %s', ...
            required_split_fields{ii});
    end
end

if g0.primary_gate_trigger
    error('EXP009:PA5G:OnGridGateSelfTestFailed', ...
        ['Evidence gate triggered on an exact single on-grid tone. ' ...
         'DeltaBIC=%g, split=%g, frac=%g.'], ...
        g0.delta_bic, ...
        g0.split_inconsistency_bins, ...
        abs(fractional_component(e0)));
end

%% Test 3 — gate must turn ON for an exact strong-only quarter-bin tone
eta1 = 0.25;

x1 = synth_discrete_lfm( ...
    N,1,a,eta1/N,0);

[e1,~] = estimate_continuous_ml(x1,a,cfg);

[g1,~] = model_evidence_gate( ...
    x1,a,e1,cfg);

if ~g1.primary_gate_trigger
    error('EXP009:PA5G:OffGridGateSelfTestFailed', ...
        ['Evidence gate failed on an exact strong-only quarter-bin tone. ' ...
         'DeltaBIC=%g, split=%g, frac=%g.'], ...
        g1.delta_bic, ...
        g1.split_inconsistency_bins, ...
        abs(fractional_component(e1)));
end

end

%% ========================================================================
function [K_A,K_SAR,K_res] = ...
    residual_fm_rates(v,R0,lambda,cfg)

V = cfg.platform_velocity_mps;

K_A = -2*(V-v).^2/(lambda*R0);
K_SAR = 2*V^2/(lambda*R0);
K_res = K_SAR.^2./(K_A-K_SAR)+K_SAR;

end

%% ========================================================================
function x = synth_discrete_lfm(N,A,a,b,phi)

m = 0:N-1;

x = A.*exp(1j*2*pi*( ...
    0.5*a*m.^2+b*m)+1j*phi);

x = x(:).';

end

%% ========================================================================
function Y = matched_lfm_transform(x,a)

x = x(:).';

N = numel(x);
m = 0:N-1;

z = x.*exp(-1j*pi*a*m.^2);

Y = fftshift(fft(z))/sqrt(N);

end

%% ========================================================================
function x = inverse_matched_lfm_transform(Y,a)

Y = Y(:).';

N = numel(Y);
m = 0:N-1;

z = ifft(ifftshift(Y))*sqrt(N);

x = z.*exp(1j*pi*a*m.^2);

end

%% ========================================================================
function z = dechirp_signal(x,a)

x = x(:).';

N = numel(x);
m = 0:N-1;

z = x.*exp(-1j*pi*a*m.^2);

end

%% ========================================================================
function eta_hat = ...
    estimate_log_parabolic(x,a,cfg)
% PA5F estimator retained only for bias comparison.

if ~strcmpi(cfg.old_subbin_estimator, ...
        'LogPowerParabolic3')
    error('Unknown old estimator: %s', ...
        cfg.old_subbin_estimator);
end

Y = matched_lfm_transform(x,a);
P = abs(Y).^2;

N = numel(P);
[~,i0] = max(P);

im = mod(i0-2,N)+1;
ip = mod(i0,N)+1;

pmax = max(P);

Lm = log(max(P(im), ...
    cfg.log_power_floor*pmax));

L0 = log(max(P(i0), ...
    cfg.log_power_floor*pmax));

Lp = log(max(P(ip), ...
    cfg.log_power_floor*pmax));

den = Lm-2*L0+Lp;

if abs(den)<=100*eps(max(abs([Lm,L0,Lp])))
    delta = 0;
else
    delta = 0.5*(Lm-Lp)/den;
end

delta = min(max( ...
    delta,-cfg.subbin_delta_clip), ...
    cfg.subbin_delta_clip);

dc = floor(N/2)+1;
k0 = i0-dc;

eta_hat = k0+delta;

end

%% ========================================================================
function [nu_hat,diag] = ...
    estimate_continuous_ml(x,a,cfg)
% Continuous single-tone ML/LS frequency estimate.
%
% Dechirp:
%   z[n] = x[n] exp(-j*pi*a*n^2)
%
% For fixed nu:
%   c_hat = argmin_c ||z-c exp(j2pi nu n/N)||^2
%
% Thus:
%   nu_hat = argmax |sum z exp(-j2pi nu n/N)|^2.

z = dechirp_signal(x,a);

N = numel(z);
m = 0:N-1;

Y = fftshift(fft(z));
[~,i0] = max(abs(Y));

dc = floor(N/2)+1;
k0 = i0-dc;

[nu_hat,Jhat] = ...
    refine_continuous_frequency( ...
        z,m,N,k0,cfg);

Jint = tone_objective(z,m,N,round(nu_hat));

diag = struct();
diag.coarse_integer_bin = k0;
diag.objective_at_hat = Jhat;
diag.objective_at_nearest_integer = Jint;
diag.objective_gain_vs_integer = ...
    (Jhat-Jint)/max(Jhat,cfg.small_norm_floor);

end

%% ========================================================================
function [nu_hat,Jhat] = ...
    refine_continuous_frequency( ...
        z,m,N,center,cfg)

z = z(:).';
m = m(:).';

lb = center-cfg.ml_search_halfwidth_bins;
ub = center+cfg.ml_search_halfwidth_bins;

ng = cfg.ml_bracket_points;

grid = linspace(lb,ub,ng);
J = zeros(size(grid));

for i = 1:ng
    J(i) = tone_objective( ...
        z,m,N,grid(i));
end

[~,ib] = max(J);

i1 = max(1,ib-1);
i2 = min(ng,ib+1);

local_lb = grid(i1);
local_ub = grid(i2);

if local_ub<=local_lb

    nu_hat = grid(ib);
    Jhat = J(ib);
    return;
end

opts = optimset( ...
    'Display','off', ...
    'TolX',cfg.ml_tolx_bins, ...
    'MaxFunEvals',cfg.ml_max_fun_evals);

obj = @(nu) -tone_objective( ...
    z,m,N,nu);

[nu_hat,fval] = fminbnd( ...
    obj,local_lb,local_ub,opts);

Jhat = -fval;

end

%% ========================================================================
function J = tone_objective(z,m,N,nu)

v = exp(-1j*2*pi*nu*m/N);

q = sum(z.*v);

J = abs(q).^2;

end

%% ========================================================================
function [gate,split] = ...
    model_evidence_gate( ...
        x,a,nu_hat,cfg)
% Parameter-free deterministic evidence gate.
%
% H0: nearest integer-bin tone.
% H1: continuous-frequency tone.
%
% Gate:
%   DeltaBIC > 0
%   AND
%   |fractional estimate| > split-aperture disagreement.

z = dechirp_signal(x,a);

N = numel(z);
m = 0:N-1;

nu_int = round(nu_hat);

[rss0,~] = tone_fit_rss( ...
    z,m,N,nu_int);

[rss1,~] = tone_fit_rss( ...
    z,m,N,nu_hat);

energy = real(sum(abs(z).^2));

rss_floor = ...
    cfg.bic_eps_multiplier * ...
    N * eps(max(energy,1));

rss0b = max(rss0,rss_floor);
rss1b = max(rss1,rss_floor);

bic0 = ...
    N*log(rss0b/N) + ...
    cfg.bic_k_integer*log(N);

bic1 = ...
    N*log(rss1b/N) + ...
    cfg.bic_k_continuous*log(N);

delta_bic = bic0-bic1;

split = split_aperture_diagnostic( ...
    z,m,N,nu_hat,cfg);

frac = fractional_component(nu_hat);

bic_prefers = delta_bic>0;

shift_exceeds_split = ...
    abs(frac) > ...
    split.split_inconsistency_bins;

primary_trigger = ...
    bic_prefers && shift_exceeds_split;

gate = struct();
gate.nu_integer_bins = nu_int;
gate.rss_integer = rss0;
gate.rss_continuous = rss1;
gate.bic_integer = bic0;
gate.bic_continuous = bic1;
gate.delta_bic = delta_bic;
gate.bic_prefers_continuous = bic_prefers;

% Mirror split-aperture diagnostics into the gate structure as well.
% This keeps the function interface robust for callers that only retain
% the first output, while the second output remains available when the
% full split diagnostic is needed.
gate.nu_left_bins = split.nu_left_bins;
gate.nu_right_bins = split.nu_right_bins;
gate.split_inconsistency_bins = split.split_inconsistency_bins;

gate.shift_exceeds_split = shift_exceeds_split;
gate.primary_gate_trigger = primary_trigger;

end

%% ========================================================================
function [rss,c_hat] = ...
    tone_fit_rss(z,m,N,nu)

z = z(:).';
m = m(:).';

a = exp(1j*2*pi*nu*m/N);

den = sum(abs(a).^2);

c_hat = ...
    sum(conj(a).*z) / ...
    max(den,eps);

e = z-c_hat*a;

rss = real(sum(abs(e).^2));

end

%% ========================================================================
function S = ...
    split_aperture_diagnostic( ...
        z,m,N,nu_full,cfg)

n = numel(z);

if n<cfg.split_min_samples

    S = struct();
    S.nu_left_bins = NaN;
    S.nu_right_bins = NaN;
    S.split_inconsistency_bins = Inf;
    return;
end

nL = floor(n/2);

idxL = 1:nL;
idxR = (nL+1):n;

[nuL,~] = ...
    refine_continuous_frequency( ...
        z(idxL),m(idxL),N, ...
        nu_full,cfg);

[nuR,~] = ...
    refine_continuous_frequency( ...
        z(idxR),m(idxR),N, ...
        nu_full,cfg);

S = struct();
S.nu_left_bins = nuL;
S.nu_right_bins = nuR;
S.split_inconsistency_bins = ...
    abs(fractional_error(nuL,nuR));

end

%% ========================================================================
function f = fractional_component(nu)
% Fractional displacement relative to nearest integer bin.
% Range is approximately [-0.5,0.5].
%
% At exact +0.5 the sign is numerically ambiguous, but either +0.5 or
% -0.5 moves the tone to an integer bin and is physically equivalent.

f = nu-round(nu);

end

%% ========================================================================
function e = fractional_error(a,b)
% Error modulo one integer DFT bin.

e = mod((a-b)+0.5,1)-0.5;

end

%% ========================================================================
function [xr,phase] = recenter_signal(x,eta_used)

x = x(:).';

N = numel(x);
m = 0:N-1;

phase = ...
    exp(-1j*2*pi*eta_used*m/N);

xr = x.*phase;

end

%% ========================================================================
function [mask,info] = ...
    build_plateau_tol_mask( ...
        Y,Lwin,cfg)

amp = abs(Y(:).');
N = numel(amp);

amax = max(amp);
gate = cfg.frac_domain_peak_gate*amax;

tol = ...
    cfg.tie_eps_multiplier * ...
    N * eps(max(amax,1));

centers = ...
    plateau_aware_tol( ...
        amp,gate,tol);

half = floor((Lwin-1)/2);

mask = false(1,N);

for k = 1:numel(centers)

    i1 = max(1,centers(k)-half);
    i2 = min(N,centers(k)+half);

    mask(i1:i2) = true;
end

info = struct();
info.raw_indices = centers;
info.raw_detected_bin_count = numel(centers);
info.mask_bin_count = nnz(mask);
info.mask_fraction = mean(mask);
info.tie_tolerance_abs = tol;

end

%% ========================================================================
function pk = ...
    plateau_aware_tol(amp,gate,tol)

amp = amp(:).';
N = numel(amp);

pk = [];

if N==1
    pk = 1;
    return;
end

if amp(1)>=amp(2)-tol && ...
        amp(1)>=gate-tol
    pk(end+1) = 1; %#ok<AGROW>
end

for i = 2:N-1

    ge_left = ...
        amp(i)>=amp(i-1)-tol;

    ge_right = ...
        amp(i)>=amp(i+1)-tol;

    strict_somewhere = ...
        amp(i)>amp(i-1)+tol || ...
        amp(i)>amp(i+1)+tol;

    if ge_left && ge_right && ...
            strict_somewhere && ...
            amp(i)>=gate-tol

        pk(end+1) = i; %#ok<AGROW>
    end
end

if amp(N)>=amp(N-1)-tol && ...
        amp(N)>=gate-tol
    pk(end+1) = N; %#ok<AGROW>
end

pk = unique(pk);

if isempty(pk)

    [~,imax] = max(amp);

    pk = find( ...
        abs(amp-amp(imax))<=tol & ...
        amp>=gate-tol);
end

end

%% ========================================================================
function r = ...
    remove_with_mask(x,a,mask)

Y = matched_lfm_transform(x,a);

Yext = zeros(size(Y));
Yext(mask) = Y(mask);

ext = ...
    inverse_matched_lfm_transform( ...
        Yext,a);

r = x-ext;

end

%% ========================================================================
function [sr,wr] = ...
    apply_fixed_mask_components( ...
        s,w,a,mask)

Ys = matched_lfm_transform(s,a);
Yw = matched_lfm_transform(w,a);

Ysq = zeros(size(Ys));
Ysq(mask) = Ys(mask);

Ywq = zeros(size(Yw));
Ywq(mask) = Yw(mask);

Qs = inverse_matched_lfm_transform( ...
    Ysq,a);

Qw = inverse_matched_lfm_transform( ...
    Ywq,a);

sr = s-Qs;
wr = Qw;

end

%% ========================================================================
function rmin = ...
    recoverability_floor(L0,D0)

if D0>=1-1e-12

    if L0<=1e-12
        rmin = 0;
    else
        rmin = Inf;
    end

else

    rmin = ...
        L0/sqrt(max(1-D0^2,eps));
end

end

%% ========================================================================
function [ok,ratio] = ...
    weak_stage_readiness( ...
        residual,aweak,bweak,cfg)

Y = matched_lfm_transform( ...
    residual,aweak);

amp = abs(Y);
N = numel(amp);

eta = bweak*N;
dc = floor(N/2)+1;

idx_expected = round(dc+eta);
idx_expected = mod(idx_expected-1,N)+1;

cand = [];

for d = -cfg.weak_stage_center_tolerance_bins: ...
        cfg.weak_stage_center_tolerance_bins

    cand(end+1) = ...
        mod(idx_expected-1+d,N)+1; %#ok<AGROW>
end

local_peak = max(amp(cand));
global_peak = max(amp);

ratio = ...
    local_peak / ...
    max(global_peak,cfg.small_norm_floor);

ok = ratio>=cfg.weak_stage_peak_gate;

end

%% ========================================================================
function S = ...
    summarize_strongonly_estimators(T)

modes = unique(string(T.aperture_mode),'stable');
etas = unique(T.true_eta_bins).';

rows = {};

for im = 1:numel(modes)

    for ie = 1:numel(etas)

        M = T( ...
            string(T.aperture_mode)==modes(im) & ...
            abs(T.true_eta_bins-etas(ie))<1e-12,:);

        eold = M.old_parabolic_eta_error_bins;
        eml = M.continuous_ml_eta_error_bins;

        rows(end+1,:) = { ... %#ok<AGROW>
            char(modes(im)),etas(ie),height(M), ...
            sqrt(mean(eold.^2)), ...
            median(abs(eold)), ...
            max(abs(eold)), ...
            sqrt(mean(eml.^2)), ...
            median(abs(eml)), ...
            max(abs(eml)), ...
            median(M.continuous_objective_gain_vs_integer), ...
            mean(M.primary_gate_trigger)};
    end
end

S = cell2table(rows, ...
    'VariableNames',{ ...
    'aperture_mode','true_eta_bins','n', ...
    'old_parabolic_rmse_bins', ...
    'old_parabolic_median_abs_error_bins', ...
    'old_parabolic_max_abs_error_bins', ...
    'continuous_ml_rmse_bins', ...
    'continuous_ml_median_abs_error_bins', ...
    'continuous_ml_max_abs_error_bins', ...
    'median_continuous_objective_gain_vs_integer', ...
    'strongonly_primary_gate_trigger_rate'});

end

%% ========================================================================
function S = summarize_floor(T)

modes = unique(string(T.aperture_mode),'stable');
etas = unique(T.true_eta_bins).';
groups = unique(string(T.group),'stable');
wins = unique(T.window_bins).';

rows = {};

for im = 1:numel(modes)

    for ie = 1:numel(etas)

        for ig = 1:numel(groups)

            for iw = 1:numel(wins)

                M = T( ...
                    string(T.aperture_mode)==modes(im) & ...
                    abs(T.true_eta_bins-etas(ie))<1e-12 & ...
                    string(T.group)==groups(ig) & ...
                    T.window_bins==wins(iw),:);

                r = M.recoverability_floor_rmin;
                rf = r(isfinite(r));

                if isempty(rf)
                    medr = Inf;
                else
                    medr = median(rf);
                end

                rows(end+1,:) = { ... %#ok<AGROW>
                    char(modes(im)),etas(ie), ...
                    char(groups(ig)),wins(iw), ...
                    median(abs(M.eta_used_error_bins)), ...
                    median(M.zero_mismatch_strong_leak_L0), ...
                    median(M.zero_mismatch_weak_loss_D0), ...
                    medr};
            end
        end
    end
end

S = cell2table(rows, ...
    'VariableNames',{ ...
    'aperture_mode','true_eta_bins', ...
    'group','window_bins', ...
    'median_abs_eta_used_error_bins', ...
    'median_zero_mismatch_strong_leak_L0', ...
    'median_zero_mismatch_weak_loss_D0', ...
    'median_recoverability_floor_rmin'});

end

%% ========================================================================
function B = summarize_best_floor(S)

modes = unique(string(S.aperture_mode),'stable');
etas = unique(S.true_eta_bins).';
groups = unique(string(S.group),'stable');

rows = {};

for im = 1:numel(modes)

    for ie = 1:numel(etas)

        for ig = 1:numel(groups)

            M = S( ...
                string(S.aperture_mode)==modes(im) & ...
                abs(S.true_eta_bins-etas(ie))<1e-12 & ...
                string(S.group)==groups(ig),:);

            [bestv,ib] = min( ...
                M.median_recoverability_floor_rmin);

            rows(end+1,:) = { ... %#ok<AGROW>
                char(modes(im)),etas(ie), ...
                char(groups(ig)), ...
                M.window_bins(ib),bestv, ...
                M.median_zero_mismatch_strong_leak_L0(ib), ...
                M.median_zero_mismatch_weak_loss_D0(ib), ...
                M.median_abs_eta_used_error_bins(ib)};
        end
    end
end

B = cell2table(rows, ...
    'VariableNames',{ ...
    'aperture_mode','true_eta_bins', ...
    'group','best_window_bins', ...
    'best_median_rmin', ...
    'best_median_L0', ...
    'best_median_D0', ...
    'median_abs_eta_used_error_bins'});

end

%% ========================================================================
function S = summarize_gate(T)

modes = unique(string(T.aperture_mode),'stable');
etas = unique(T.true_eta_bins).';

rows = {};

for im = 1:numel(modes)

    for ie = 1:numel(etas)

        M = T( ...
            string(T.aperture_mode)==modes(im) & ...
            abs(T.true_eta_bins-etas(ie))<1e-12,:);

        e = M.continuous_mix_eta_error_bins;

        rows(end+1,:) = { ... %#ok<AGROW>
            char(modes(im)),etas(ie),height(M), ...
            sqrt(mean(e.^2)), ...
            median(abs(e)), ...
            local_percentile(abs(e),90), ...
            mean(M.bic_prefers_continuous), ...
            mean(M.shift_exceeds_split), ...
            mean(M.primary_gate_trigger), ...
            median(M.delta_bic), ...
            median(M.split_inconsistency_bins), ...
            median(M.estimated_shift_magnitude_bins)};
    end
end

S = cell2table(rows, ...
    'VariableNames',{ ...
    'aperture_mode','true_eta_bins','n', ...
    'continuous_mix_rmse_bins', ...
    'continuous_mix_median_abs_error_bins', ...
    'continuous_mix_p90_abs_error_bins', ...
    'bic_only_trigger_rate', ...
    'shift_exceeds_split_rate', ...
    'primary_gate_trigger_rate', ...
    'median_delta_bic', ...
    'median_split_inconsistency_bins', ...
    'median_estimated_shift_magnitude_bins'});

end

%% ========================================================================
function S = ...
    summarize_gate_by_contrast(T)

modes = unique(string(T.aperture_mode),'stable');
etas = unique(T.true_eta_bins).';
ratios = unique(T.weak_to_strong_ratio).';

rows = {};

for im = 1:numel(modes)

    for ie = 1:numel(etas)

        for ir = 1:numel(ratios)

            M = T( ...
                string(T.aperture_mode)==modes(im) & ...
                abs(T.true_eta_bins-etas(ie))<1e-12 & ...
                abs(T.weak_to_strong_ratio-ratios(ir))<1e-12,:);

            rows(end+1,:) = { ... %#ok<AGROW>
                char(modes(im)),etas(ie),ratios(ir), ...
                height(M), ...
                mean(M.bic_prefers_continuous), ...
                mean(M.primary_gate_trigger), ...
                median(abs(M.continuous_mix_eta_error_bins)), ...
                local_percentile( ...
                    abs(M.continuous_mix_eta_error_bins),90), ...
                median(M.split_inconsistency_bins)};
        end
    end
end

S = cell2table(rows, ...
    'VariableNames',{ ...
    'aperture_mode','true_eta_bins', ...
    'weak_to_strong_ratio','n', ...
    'bic_only_trigger_rate', ...
    'primary_gate_trigger_rate', ...
    'median_abs_eta_error_bins', ...
    'p90_abs_eta_error_bins', ...
    'median_split_inconsistency_bins'});

end

%% ========================================================================
function S = summarize_practical(T)

modes = unique(string(T.aperture_mode),'stable');
etas = unique(T.true_eta_bins).';
groups = unique(string(T.group),'stable');
wins = unique(T.window_bins).';

rows = {};

for im = 1:numel(modes)

    for ie = 1:numel(etas)

        for ig = 1:numel(groups)

            for iw = 1:numel(wins)

                M = T( ...
                    string(T.aperture_mode)==modes(im) & ...
                    abs(T.true_eta_bins-etas(ie))<1e-12 & ...
                    string(T.group)==groups(ig) & ...
                    T.window_bins==wins(iw),:);

                rows(end+1,:) = { ... %#ok<AGROW>
                    char(modes(im)),etas(ie), ...
                    char(groups(ig)),wins(iw), ...
                    height(M), ...
                    median(M.practical_error_ratio), ...
                    local_percentile( ...
                        M.practical_error_ratio,90), ...
                    mean(M.error_feasible_E_le_1), ...
                    mean(M.weak_stage_success), ...
                    median(M.strong_leak_ratio), ...
                    median(M.weak_projection_loss_ratio), ...
                    median(abs(M.eta_used_error_bins)), ...
                    max(M.identity_abs_error)};
            end
        end
    end
end

S = cell2table(rows, ...
    'VariableNames',{ ...
    'aperture_mode','true_eta_bins', ...
    'group','window_bins','n', ...
    'median_practical_error_ratio', ...
    'p90_practical_error_ratio', ...
    'E_le_1_trial_fraction', ...
    'weak_stage_success_rate', ...
    'median_strong_leak_ratio', ...
    'median_weak_projection_loss_ratio', ...
    'median_abs_eta_used_error_bins', ...
    'maximum_identity_abs_error'});

end

%% ========================================================================
function B = ...
    summarize_best_practical(S)

modes = unique(string(S.aperture_mode),'stable');
etas = unique(S.true_eta_bins).';
groups = unique(string(S.group),'stable');

rows = {};

for im = 1:numel(modes)

    for ie = 1:numel(etas)

        for ig = 1:numel(groups)

            M = S( ...
                string(S.aperture_mode)==modes(im) & ...
                abs(S.true_eta_bins-etas(ie))<1e-12 & ...
                string(S.group)==groups(ig),:);

            [bestE,ib] = min( ...
                M.median_practical_error_ratio);

            [bestFeas,ifz] = max( ...
                M.E_le_1_trial_fraction);

            [bestSucc,is] = max( ...
                M.weak_stage_success_rate);

            rows(end+1,:) = { ... %#ok<AGROW>
                char(modes(im)),etas(ie), ...
                char(groups(ig)), ...
                M.window_bins(ib), ...
                bestE, ...
                M.p90_practical_error_ratio(ib), ...
                M.E_le_1_trial_fraction(ib), ...
                M.weak_stage_success_rate(ib), ...
                M.median_strong_leak_ratio(ib), ...
                M.median_weak_projection_loss_ratio(ib), ...
                M.median_abs_eta_used_error_bins(ib), ...
                M.window_bins(ifz),bestFeas, ...
                M.window_bins(is),bestSucc};
        end
    end
end

B = cell2table(rows, ...
    'VariableNames',{ ...
    'aperture_mode','true_eta_bins','group', ...
    'min_error_window_bins', ...
    'minimum_median_error', ...
    'p90_error_at_min_error_window', ...
    'feasible_fraction_at_min_error_window', ...
    'success_at_min_error_window', ...
    'median_strong_leak_at_min_error_window', ...
    'median_weak_loss_at_min_error_window', ...
    'median_abs_eta_used_error_bins', ...
    'max_feasible_window_bins', ...
    'maximum_E_le_1_trial_fraction', ...
    'max_success_window_bins', ...
    'maximum_weak_stage_success_rate'});

end

%% ========================================================================
function I = ...
    summarize_identity(T,cfg)

groups = unique(string(T.group),'stable');

rows = {};

for ig = 1:numel(groups)

    M = T(string(T.group)==groups(ig),:);

    rows(end+1,:) = { ... %#ok<AGROW>
        char(groups(ig)),height(M), ...
        median(M.identity_abs_error), ...
        max(M.identity_abs_error), ...
        double(max(M.identity_abs_error)<= ...
            cfg.identity_gate)};
end

I = cell2table(rows, ...
    'VariableNames',{ ...
    'group','n', ...
    'median_identity_abs_error', ...
    'maximum_identity_abs_error', ...
    'identity_gate_pass'});

end

%% ========================================================================
function S = ...
    summarize_improvement(B)

modes = unique(string(B.aperture_mode),'stable');
etas = unique(B.true_eta_bins).';

rows = {};

for im = 1:numel(modes)

    for ie = 1:numel(etas)

        mode = modes(im);
        eta = etas(ie);

        e0 = pick_best_error( ...
            B,mode,eta,"G0_Baseline");

        e1 = pick_best_error( ...
            B,mode,eta,"G1_OracleRecenter");

        e2 = pick_best_error( ...
            B,mode,eta,"G2_ContinuousStrongOnly");

        e3 = pick_best_error( ...
            B,mode,eta,"G3_ContinuousMixtureAlways");

        e4 = pick_best_error( ...
            B,mode,eta,"G4_EvidenceGatedMixture");

        rows(end+1,:) = { ... %#ok<AGROW>
            char(mode),eta, ...
            e0,e1,e2,e3,e4, ...
            safe_ratio(e1,e0), ...
            safe_ratio(e2,e0), ...
            safe_ratio(e3,e0), ...
            safe_ratio(e4,e0), ...
            safe_ratio(e4,e3)};
    end
end

S = cell2table(rows, ...
    'VariableNames',{ ...
    'aperture_mode','true_eta_bins', ...
    'baseline_min_error', ...
    'oracle_min_error', ...
    'continuousStrongOnly_min_error', ...
    'continuousMixtureAlways_min_error', ...
    'evidenceGatedMixture_min_error', ...
    'oracle_to_baseline_ratio', ...
    'continuousStrongOnly_to_baseline_ratio', ...
    'continuousMixtureAlways_to_baseline_ratio', ...
    'evidenceGated_to_baseline_ratio', ...
    'evidenceGated_to_alwaysMixture_ratio'});

end

%% ========================================================================
function v = ...
    pick_best_error(B,mode,eta,group)

M = B( ...
    string(B.aperture_mode)==mode & ...
    abs(B.true_eta_bins-eta)<1e-12 & ...
    string(B.group)==group,:);

v = M.minimum_median_error(1);

end

%% ========================================================================
function r = safe_ratio(a,b)

if ~isfinite(a) || ~isfinite(b)
    r = NaN;
elseif abs(b)<=1e-14
    r = double(abs(a)<=1e-14);
else
    r = a/b;
end

end

%% ========================================================================
function D = ...
    build_decision_summary( ...
        ES,GS,BP,IS,cfg)

modes = unique(string(ES.aperture_mode),'stable');

rows = {};

for im = 1:numel(modes)

    mode = modes(im);

    identity_pass = all(IS.identity_gate_pass==1);

    EC = ES( ...
        string(ES.aperture_mode)==mode,:);

    max_cont_rmse = ...
        max(EC.continuous_ml_rmse_bins);

    continuous_solver_pass = ...
        max_cont_rmse <= ...
        cfg.continuous_solver_rmse_gate_bins;

    G0 = GS( ...
        string(GS.aperture_mode)==mode & ...
        abs(GS.true_eta_bins-0)<1e-12,:);

    G5 = GS( ...
        string(GS.aperture_mode)==mode & ...
        abs(GS.true_eta_bins-0.5)<1e-12,:);

    ongrid_bic_trigger = G0.bic_only_trigger_rate(1);
    ongrid_primary_trigger = ...
        G0.primary_gate_trigger_rate(1);

    halfbin_primary_trigger = ...
        G5.primary_gate_trigger_rate(1);

    p0 = pick_best_error( ...
        BP,mode,0,"G0_Baseline");

    p3_0 = pick_best_error( ...
        BP,mode,0,"G3_ContinuousMixtureAlways");

    p4_0 = pick_best_error( ...
        BP,mode,0,"G4_EvidenceGatedMixture");

    p0_half = pick_best_error( ...
        BP,mode,0.5,"G0_Baseline");

    p3_half = pick_best_error( ...
        BP,mode,0.5,"G3_ContinuousMixtureAlways");

    p4_half = pick_best_error( ...
        BP,mode,0.5,"G4_EvidenceGatedMixture");

    gate_suppresses_false_correction = ...
        ongrid_primary_trigger < ...
        ongrid_bic_trigger && ...
        p4_0 <= p3_0;

    gate_retains_offgrid_benefit = ...
        p4_half < p0_half;

    if ~identity_pass

        branch = ...
            "IMPLEMENTATION_IDENTITY_REVIEW";

    elseif ~continuous_solver_pass

        branch = ...
            "CONTINUOUS_ESTIMATOR_NUMERICAL_OR_MODEL_FAILURE";

    elseif gate_suppresses_false_correction && ...
            gate_retains_offgrid_benefit

        branch = ...
            "CONTINUOUS_ESTIMATOR_VALIDATED_AND_EVIDENCE_GATE_PROMISING";

    elseif ~gate_suppresses_false_correction && ...
            gate_retains_offgrid_benefit

        branch = ...
            "CONTINUOUS_ESTIMATOR_WORKS_BUT_FALSE_CORRECTION_GATE_REMAINS_BOTTLENECK";

    elseif gate_suppresses_false_correction && ...
            ~gate_retains_offgrid_benefit

        branch = ...
            "GATE_SUPPRESSES_FALSE_CORRECTION_BUT_IS_TOO_CONSERVATIVE_OFFGRID";

    else

        branch = ...
            "MIXTURE_MODEL_SELECTION_REMAINS_UNRESOLVED";
    end

    rows(end+1,:) = { ... %#ok<AGROW>
        char(mode), ...
        double(identity_pass), ...
        max_cont_rmse, ...
        double(continuous_solver_pass), ...
        ongrid_bic_trigger, ...
        ongrid_primary_trigger, ...
        halfbin_primary_trigger, ...
        p0,p3_0,p4_0, ...
        p0_half,p3_half,p4_half, ...
        double(gate_suppresses_false_correction), ...
        double(gate_retains_offgrid_benefit), ...
        char(branch)};
end

D = cell2table(rows, ...
    'VariableNames',{ ...
    'aperture_mode', ...
    'projection_identity_all_pass', ...
    'maximum_strongonly_continuous_rmse_bins', ...
    'continuous_solver_pass', ...
    'ongrid_bic_only_trigger_rate', ...
    'ongrid_primary_gate_trigger_rate', ...
    'halfbin_primary_gate_trigger_rate', ...
    'ongrid_baseline_min_error', ...
    'ongrid_alwaysMixture_min_error', ...
    'ongrid_gatedMixture_min_error', ...
    'halfbin_baseline_min_error', ...
    'halfbin_alwaysMixture_min_error', ...
    'halfbin_gatedMixture_min_error', ...
    'gate_suppresses_false_correction', ...
    'gate_retains_offgrid_benefit', ...
    'decision_branch'});

end

%% ========================================================================
function q = local_percentile(x,p)

x = sort(x(:));

x = x(isfinite(x));

if isempty(x)
    q = NaN;
    return;
end

if numel(x)==1
    q = x;
    return;
end

r = 1 + (p/100)*(numel(x)-1);

i1 = floor(r);
i2 = ceil(r);

if i1==i2
    q = x(i1);
else
    w = r-i1;
    q = (1-w)*x(i1) + w*x(i2);
end

end

%% ========================================================================
function write_summary( ...
    out_path,cfg,lambda,R0, ...
    ES,BF,GS,BP,IS,D)

fid = fopen(fullfile(out_path,'summary.txt'),'w');

fprintf(fid,'EXP009 PA5G / Continuous Sub-Bin Estimation + Gating\n');
fprintf(fid,'===================================================\n\n');

fprintf(fid,'Purpose\n');
fprintf(fid,'-------\n');
fprintf(fid,['1) remove PA5F deterministic interpolation bias with a ' ...
    'continuous ML/LS estimator;\n']);
fprintf(fid,['2) test a data-driven gate against mixture-induced false ' ...
    'correction.\n\n']);

fprintf(fid,'Physical setup\n');
fprintf(fid,'--------------\n');
fprintf(fid,'lambda=%g m, R0=%g m, PRF=%g Hz\n', ...
    lambda,R0,cfg.prf_hz);
fprintf(fid,'eta=%s bins\n', ...
    mat2str(cfg.fractional_bin_offsets));
fprintf(fid,'windows=%s bins\n\n', ...
    mat2str(cfg.filter_window_length_bins));

fprintf(fid,'Continuous estimator\n');
fprintf(fid,'--------------------\n');
fprintf(fid,['nu_hat = argmax_nu |sum z[n] exp(-j2pi nu n/N)|^2\n']);
fprintf(fid,['search halfwidth=%g bins, bracket points=%d, TolX=%g bins\n\n'], ...
    cfg.ml_search_halfwidth_bins, ...
    cfg.ml_bracket_points, ...
    cfg.ml_tolx_bins);

fprintf(fid,'Evidence gate\n');
fprintf(fid,'-------------\n');
fprintf(fid,['Trigger iff DeltaBIC>0 AND |fractional nu_hat| ' ...
    '> split-aperture disagreement.\n']);
fprintf(fid,['No physical threshold is tuned.\n\n']);

fprintf(fid,'Strong-only estimator summary\n');
fprintf(fid,'-----------------------------\n');
for i=1:height(ES)
    fprintf(fid,[ ...
        '%s eta=%g oldRMSE=%g continuousRMSE=%g gateRate=%g\n'], ...
        ES.aperture_mode{i}, ...
        ES.true_eta_bins(i), ...
        ES.old_parabolic_rmse_bins(i), ...
        ES.continuous_ml_rmse_bins(i), ...
        ES.strongonly_primary_gate_trigger_rate(i));
end

fprintf(fid,'\nBest deterministic floor\n');
fprintf(fid,'------------------------\n');
for i=1:height(BF)
    fprintf(fid,[ ...
        '%s eta=%g %s L=%d rmin=%g L0=%g D0=%g\n'], ...
        BF.aperture_mode{i}, ...
        BF.true_eta_bins(i), ...
        BF.group{i}, ...
        BF.best_window_bins(i), ...
        BF.best_median_rmin(i), ...
        BF.best_median_L0(i), ...
        BF.best_median_D0(i));
end

fprintf(fid,'\nGate summary\n');
fprintf(fid,'------------\n');
for i=1:height(GS)
    fprintf(fid,[ ...
        '%s eta=%g mixRMSE=%g BICrate=%g gateRate=%g ' ...
        'splitMed=%g shiftMed=%g\n'], ...
        GS.aperture_mode{i}, ...
        GS.true_eta_bins(i), ...
        GS.continuous_mix_rmse_bins(i), ...
        GS.bic_only_trigger_rate(i), ...
        GS.primary_gate_trigger_rate(i), ...
        GS.median_split_inconsistency_bins(i), ...
        GS.median_estimated_shift_magnitude_bins(i));
end

fprintf(fid,'\nBest practical summary\n');
fprintf(fid,'----------------------\n');
for i=1:height(BP)
    fprintf(fid,[ ...
        '%s eta=%g %s L=%d medE=%g feasible=%g success=%g\n'], ...
        BP.aperture_mode{i}, ...
        BP.true_eta_bins(i), ...
        BP.group{i}, ...
        BP.min_error_window_bins(i), ...
        BP.minimum_median_error(i), ...
        BP.feasible_fraction_at_min_error_window(i), ...
        BP.success_at_min_error_window(i));
end

fprintf(fid,'\nIdentity\n');
fprintf(fid,'--------\n');
for i=1:height(IS)
    fprintf(fid,'%s maxErr=%g pass=%d\n', ...
        IS.group{i}, ...
        IS.maximum_identity_abs_error(i), ...
        IS.identity_gate_pass(i));
end

fprintf(fid,'\nDecision\n');
fprintf(fid,'--------\n');
for i=1:height(D)
    fprintf(fid,'%s -> %s\n', ...
        D.aperture_mode{i}, ...
        D.decision_branch{i});
end

fprintf(fid,'\nInterpretation discipline\n');
fprintf(fid,'-------------------------\n');
fprintf(fid,['1) Continuous ML/LS is model-derived, not selected after ' ...
    'viewing the PA5G outcome.\n']);
fprintf(fid,['2) The BIC penalty is fixed by model dimension; the split ' ...
    'condition uses internal disagreement, not a tuned threshold.\n']);
fprintf(fid,['3) G2 is not practical because it has access to strong-only ' ...
    'data. It isolates estimator bias.\n']);
fprintf(fid,['4) G4 is the practical deterministic candidate.\n']);
fprintf(fid,['5) Noise, clutter and strong-chirp-rate estimation error remain ' ...
    'OFF until this deterministic gate is audited.\n']);

fclose(fid);

end

%% ========================================================================
function make_figures( ...
    out_path,cfg,ES,GS,CG,BP,PS)

modes = ["Paper1s","BeamDerived"];

%% Fig 1 — old vs continuous strong-only RMSE
fig = figure('Visible',cfg.figure_visible);
hold on;

M = ES(string(ES.aperture_mode)=="BeamDerived",:);
[~,o] = sort(M.true_eta_bins);
M = M(o,:);

h = gobjects(2,1);
h(1) = plot( ...
    M.true_eta_bins, ...
    M.old_parabolic_rmse_bins, ...
    'o-','LineWidth',1.3);

h(2) = plot( ...
    M.true_eta_bins, ...
    M.continuous_ml_rmse_bins, ...
    's-','LineWidth',1.3);

xlabel('True fractional-bin offset |\eta|');
ylabel('Strong-only estimator RMSE (bins)');
title('EXP009 PA5G — Continuous ML Removes Interpolation Bias');
legend(h,{'PA5F log-parabolic','PA5G continuous ML'}, ...
    'Location','best');
grid on;

exportgraphics(fig, ...
    fullfile(out_path,'fig01_strongonly_estimator_rmse.png'), ...
    'Resolution',180);
close(fig);

%% Fig 2 — mixture estimator RMSE
fig = figure('Visible',cfg.figure_visible);
hold on;

h = gobjects(numel(modes),1);

for im = 1:numel(modes)

    M = GS(string(GS.aperture_mode)==modes(im),:);
    [~,o] = sort(M.true_eta_bins);
    M = M(o,:);

    h(im) = plot( ...
        M.true_eta_bins, ...
        M.continuous_mix_rmse_bins, ...
        'o-','LineWidth',1.3);
end

xlabel('True fractional-bin offset |\eta|');
ylabel('Continuous mixture-estimator RMSE (bins)');
title('EXP009 PA5G — Mixture-Induced Continuous-ML Bias');
legend(h,cellstr(modes(:)),'Location','best');
grid on;

exportgraphics(fig, ...
    fullfile(out_path,'fig02_mixture_continuous_rmse.png'), ...
    'Resolution',180);
close(fig);

%% Fig 3 — BIC-only vs primary evidence trigger
fig = figure('Visible',cfg.figure_visible);
hold on;

M = GS(string(GS.aperture_mode)=="BeamDerived",:);
[~,o] = sort(M.true_eta_bins);
M = M(o,:);

h = gobjects(2,1);
h(1) = plot( ...
    M.true_eta_bins, ...
    M.bic_only_trigger_rate, ...
    'o-','LineWidth',1.3);

h(2) = plot( ...
    M.true_eta_bins, ...
    M.primary_gate_trigger_rate, ...
    's-','LineWidth',1.3);

xlabel('True fractional-bin offset |\eta|');
ylabel('Trigger rate');
title('EXP009 PA5G — Model Evidence vs Split-Consistency Gate');
legend(h,{'BIC only','BIC + split-disagreement'}, ...
    'Location','best');
ylim([0 1]);
grid on;

exportgraphics(fig, ...
    fullfile(out_path,'fig03_gate_trigger_vs_eta.png'), ...
    'Resolution',180);
close(fig);

%% Fig 4 — gate trigger vs contrast at eta=0 and eta=0.5
fig = figure('Visible',cfg.figure_visible);
hold on;

etas = [0,0.5];
h = gobjects(numel(etas),1);

for ie = 1:numel(etas)

    M = CG( ...
        string(CG.aperture_mode)=="BeamDerived" & ...
        abs(CG.true_eta_bins-etas(ie))<1e-12,:);

    [~,o] = sort(M.weak_to_strong_ratio);
    M = M(o,:);

    h(ie) = plot( ...
        M.weak_to_strong_ratio, ...
        M.primary_gate_trigger_rate, ...
        'o-','LineWidth',1.3);
end

xlabel('A_w/A_s');
ylabel('Primary evidence-gate trigger rate');
title('EXP009 PA5G — Gate Selectivity vs Contrast');
legend(h,{'True \eta=0','True |\eta|=0.5'}, ...
    'Location','best');
ylim([0 1]);
grid on;

exportgraphics(fig, ...
    fullfile(out_path,'fig04_gate_selectivity_vs_contrast.png'), ...
    'Resolution',180);
close(fig);

%% Fig 5 — best practical error vs eta
fig = figure('Visible',cfg.figure_visible);
hold on;

groups = [ ...
    "G0_Baseline", ...
    "G1_OracleRecenter", ...
    "G2_ContinuousStrongOnly", ...
    "G3_ContinuousMixtureAlways", ...
    "G4_EvidenceGatedMixture"];

h = gobjects(numel(groups),1);

for ig = 1:numel(groups)

    M = BP( ...
        string(BP.aperture_mode)=="BeamDerived" & ...
        string(BP.group)==groups(ig),:);

    [~,o] = sort(M.true_eta_bins);
    M = M(o,:);

    h(ig) = plot( ...
        M.true_eta_bins, ...
        M.minimum_median_error, ...
        'o-','LineWidth',1.3);
end

yline(1,':');

xlabel('True fractional-bin offset |\eta|');
ylabel('Minimum median ||r-w||/||w|| over l');
title('EXP009 PA5G — Practical Error with Evidence-Gated Recentering');
legend(h,cellstr(groups(:)),'Location','best');
grid on;

exportgraphics(fig, ...
    fullfile(out_path,'fig05_best_practical_error_vs_eta.png'), ...
    'Resolution',180);
close(fig);

%% Fig 6 — feasible fraction vs eta
fig = figure('Visible',cfg.figure_visible);
hold on;

show_groups = [ ...
    "G0_Baseline", ...
    "G3_ContinuousMixtureAlways", ...
    "G4_EvidenceGatedMixture"];

h = gobjects(numel(show_groups),1);

for ig = 1:numel(show_groups)

    M = BP( ...
        string(BP.aperture_mode)=="BeamDerived" & ...
        string(BP.group)==show_groups(ig),:);

    [~,o] = sort(M.true_eta_bins);
    M = M(o,:);

    h(ig) = plot( ...
        M.true_eta_bins, ...
        M.maximum_E_le_1_trial_fraction, ...
        'o-','LineWidth',1.3);
end

xlabel('True fractional-bin offset |\eta|');
ylabel('Maximum E\leq1 trial fraction over l');
title('EXP009 PA5G — Feasible Fraction after Gating');
legend(h,cellstr(show_groups(:)),'Location','best');
ylim([0 1]);
grid on;

exportgraphics(fig, ...
    fullfile(out_path,'fig06_feasible_fraction_vs_eta.png'), ...
    'Resolution',180);
close(fig);

%% Fig 7 — eta=0 error vs contrast
fig = figure('Visible',cfg.figure_visible);
hold on;

h = gobjects(numel(show_groups),1);
ratios = unique(PS.window_bins); %#ok<NASGU>

for ig = 1:numel(show_groups)

    % Use the best window for each contrast by returning to trial-level
    % aggregation through PS is not possible because PS is eta/group/window
    % summarized. Instead show the fixed globally best window from BP.
    B = BP( ...
        string(BP.aperture_mode)=="BeamDerived" & ...
        abs(BP.true_eta_bins-0)<1e-12 & ...
        string(BP.group)==show_groups(ig),:);

    Lbest = B.min_error_window_bins(1);

    % PS has no contrast dimension, so represent the on-grid group-level
    % best-window median as a horizontal audit line.
    M = PS( ...
        string(PS.aperture_mode)=="BeamDerived" & ...
        abs(PS.true_eta_bins-0)<1e-12 & ...
        string(PS.group)==show_groups(ig) & ...
        PS.window_bins==Lbest,:);

    xdummy = cfg.weak_to_strong_ratio;
    ydummy = repmat( ...
        M.median_practical_error_ratio(1), ...
        size(xdummy));

    h(ig) = plot( ...
        xdummy,ydummy, ...
        'o-','LineWidth',1.3);
end

xlabel('A_w/A_s');
ylabel('Best-window group median error');
title('EXP009 PA5G — On-Grid False-Correction Audit');
legend(h,cellstr(show_groups(:)),'Location','best');
grid on;

exportgraphics(fig, ...
    fullfile(out_path,'fig07_ongrid_false_correction_audit.png'), ...
    'Resolution',180);
close(fig);

%% Fig 8 — gate split disagreement vs estimated shift
fig = figure('Visible',cfg.figure_visible);
hold on;

M = GS(string(GS.aperture_mode)=="BeamDerived",:);
[~,o] = sort(M.true_eta_bins);
M = M(o,:);

h = gobjects(2,1);

h(1) = plot( ...
    M.true_eta_bins, ...
    M.median_estimated_shift_magnitude_bins, ...
    'o-','LineWidth',1.3);

h(2) = plot( ...
    M.true_eta_bins, ...
    M.median_split_inconsistency_bins, ...
    's-','LineWidth',1.3);

xlabel('True fractional-bin offset |\eta|');
ylabel('Median bin scale');
title('EXP009 PA5G — Estimated Shift vs Internal Split Disagreement');
legend(h,{'Estimated fractional shift','Split disagreement'}, ...
    'Location','best');
grid on;

exportgraphics(fig, ...
    fullfile(out_path,'fig08_shift_vs_split_disagreement.png'), ...
    'Resolution',180);
close(fig);

end
